import { FIREBASE_CONTRACT_SCHEMA_VERSION } from './constants.js'

const field = (type, access, visibility, requirement = 'optional', lifecycle = 'canonical') =>
  Object.freeze({ type, access, visibility, requirement, lifecycle })

// A field's access and visibility classification applies recursively to its
// descendants unless a future contract explicitly defines a child override.

export const USER_CONTRACT = Object.freeze({
  path: 'users/{uid}', documentId: 'firebase_auth_uid', schemaVersion: FIREBASE_CONTRACT_SCHEMA_VERSION,
  fields: Object.freeze({
    uid: field('string', 'trusted_only', 'private_internal', 'required'),
    displayName: field('string', 'owner_writable', 'private_internal', 'required'),
    displayNameNormalized: field('string', 'derived', 'private_internal', 'required'),
    firstName: field('string', 'owner_writable', 'private_internal'),
    lastName: field('string', 'owner_writable', 'private_internal'),
    email: field('string', 'trusted_only', 'private_internal', 'required'),
    emailVerified: field('boolean', 'trusted_only', 'private_internal', 'required'),
    roles: field('string[]', 'owner_writable_limited', 'private_internal', 'required'),
    preferredLocale: field('language_code', 'owner_writable', 'private_internal', 'required'),
    profilePhoto: field('media|null', 'owner_writable', 'private_internal'),
    city: field('string', 'owner_writable', 'private_internal'),
    country: field('string', 'owner_writable', 'private_internal'),
    businessId: field('string|null', 'trusted_only', 'private_internal', 'required'),
    accountStatus: field('account_status', 'trusted_only', 'private_internal', 'required'),
    termsAccepted: field('boolean', 'owner_writable_monotonic', 'private_internal'),
    termsAcceptedAt: field('Timestamp|null', 'owner_writable_monotonic', 'private_internal'),
    termsVersion: field('string|null', 'owner_writable_monotonic', 'private_internal'),
    privacyAccepted: field('boolean', 'owner_writable_monotonic', 'private_internal'),
    privacyAcceptedAt: field('Timestamp|null', 'owner_writable_monotonic', 'private_internal'),
    privacyVersion: field('string|null', 'owner_writable_monotonic', 'private_internal'),
    lastActiveAt: field('Timestamp|null', 'derived', 'private_internal'),
    deletionRequestedAt: field('Timestamp|null', 'owner_writable_request', 'private_internal'),
    deletionScheduledFor: field('Timestamp|null', 'trusted_only', 'private_internal'),
    anonymizedAt: field('Timestamp|null', 'trusted_only', 'private_internal'),
    createdAt: field('Timestamp', 'trusted_only', 'private_internal', 'required'),
    updatedAt: field('Timestamp', 'derived', 'private_internal', 'required'),
    accountType: field('string', 'owner_writable_limited', 'private_internal', 'optional', 'transitional_legacy'),
    preferredLanguage: field('string', 'none', 'private_internal', 'optional', 'transitional_legacy'),
    photoURL: field('string|null', 'owner_writable', 'private_internal', 'optional', 'transitional_legacy'),
    profileCompleted: field('boolean', 'derived', 'private_internal', 'optional', 'transitional_legacy'),
    onboardingCompleted: field('boolean', 'derived', 'private_internal', 'optional', 'transitional_legacy'),
    businessProfileRequired: field('boolean', 'derived', 'private_internal', 'optional', 'transitional_legacy'),
    businessProfileCompleted: field('boolean', 'derived', 'private_internal', 'optional', 'transitional_legacy'),
    isVerified: field('boolean', 'none', 'private_internal', 'optional', 'transitional_legacy'),
    isPremium: field('boolean', 'none', 'private_internal', 'optional', 'transitional_legacy'),
    deletedAt: field('Timestamp|null', 'none', 'private_internal', 'optional', 'transitional_legacy'),
  }),
})

export const BUSINESS_CONTRACT = Object.freeze({
  path: 'businesses/{businessId}', documentId: 'stable_firestore_id',
  newDocumentId: 'opaque_auto_id', legacyDocumentId: 'owner_uid_may_remain_after_audit',
  schemaVersion: FIREBASE_CONTRACT_SCHEMA_VERSION,
  fields: Object.freeze({
    ownerId: field('string', 'trusted_only', 'private_internal', 'required'),
    managerIds: field('string[]', 'trusted_only', 'private_internal', 'required'),
    name: field('string', 'owner_writable', 'public', 'required'),
    nameNormalized: field('string', 'derived', 'private_internal', 'required'),
    slug: field('string', 'derived', 'public', 'required'),
    tagline: field('string', 'owner_writable', 'public'),
    description: field('string', 'owner_writable', 'public'),
    primaryCategoryId: field('string', 'owner_writable_validated', 'public'),
    categoryIds: field('string[]', 'owner_writable_validated', 'public', 'required'),
    serviceAreas: field('identifier[]', 'owner_writable_validated', 'public', 'required'),
    customServiceAreas: field('custom_value_map', 'owner_writable_validated', 'public'),
    serviceRadiusKm: field('number', 'owner_writable_validated', 'public'),
    languages: field('language_identifier[]', 'owner_writable_validated', 'public', 'required'),
    languageLabels: field('custom_value_map', 'owner_writable_validated', 'public'),
    primaryLanguage: field('language_identifier', 'owner_writable_validated', 'public', 'required'),
    location: field('public_location', 'owner_writable', 'public'),
    contact: field('public_contact_projection', 'derived', 'public', 'required'),
    profilePhoto: field('media|null', 'owner_writable', 'public'),
    coverPhoto: field('media|null', 'owner_writable', 'public'),
    galleryImages: field('media[]', 'owner_writable', 'public'),
    galleryCount: field('number', 'derived', 'public', 'required'),
    status: field('business_status', 'trusted_only', 'public', 'required'),
    verificationStatus: field('verification_status', 'trusted_only', 'public', 'required'),
    verifiedAt: field('Timestamp|null', 'trusted_only', 'public'),
    subscription: field('subscription_map', 'trusted_only', 'private_internal', 'required'),
    ratingAverage: field('number', 'derived', 'public', 'required'),
    ratingCount: field('number', 'derived', 'public', 'required'),
    publishedAt: field('Timestamp|null', 'trusted_only', 'public'),
    submittedAt: field('Timestamp|null', 'trusted_only', 'private_internal'),
    deletionRequestedAt: field('Timestamp|null', 'owner_writable_request', 'private_internal'),
    deletedAt: field('Timestamp|null', 'trusted_only', 'private_internal'),
    createdAt: field('Timestamp', 'trusted_only', 'public', 'required'),
    updatedAt: field('Timestamp', 'derived', 'public', 'required'),
    businessName: field('string', 'none', 'public', 'optional', 'transitional_legacy'),
    mainCategory: field('string', 'none', 'public', 'optional', 'transitional_legacy'),
    subcategories: field('string[]', 'none', 'public', 'optional', 'transitional_legacy'),
    phone: field('string', 'none', 'private_internal', 'optional', 'transitional_legacy'),
    email: field('string', 'none', 'private_internal', 'optional', 'transitional_legacy'),
    whatsapp: field('string', 'none', 'private_internal', 'optional', 'transitional_legacy'),
    website: field('string', 'none', 'public', 'optional', 'transitional_legacy'),
    city: field('string', 'none', 'public', 'optional', 'transitional_legacy'),
    province: field('string', 'none', 'public', 'optional', 'transitional_legacy'),
    country: field('string', 'none', 'public', 'optional', 'transitional_legacy'),
    logoURL: field('string|null', 'none', 'public', 'optional', 'transitional_legacy'),
    coverImageURL: field('string|null', 'none', 'public', 'optional', 'transitional_legacy'),
    galleryImageURLs: field('string[]', 'none', 'public', 'optional', 'transitional_legacy'),
    profileCompleted: field('boolean', 'derived', 'private_internal', 'optional', 'transitional_legacy'),
    isActive: field('boolean', 'none', 'private_internal', 'optional', 'transitional_legacy'),
    isVerified: field('boolean', 'none', 'private_internal', 'optional', 'transitional_legacy'),
    isPremium: field('boolean', 'none', 'private_internal', 'optional', 'transitional_legacy'),
    subscriptionTier: field('string', 'none', 'private_internal', 'optional', 'transitional_legacy'),
  }),
})

export const BUSINESS_PRIVATE_CONTRACT = Object.freeze({
  path: 'businessPrivate/{businessId}', documentId: 'matching_business_id', schemaVersion: FIREBASE_CONTRACT_SCHEMA_VERSION,
  fields: Object.freeze({
    ownerId: field('string', 'trusted_only', 'private_internal', 'required'),
    managerIds: field('string[]', 'trusted_only', 'private_internal', 'required'),
    contact: field('private_contact', 'owner_writable', 'private_internal', 'required'),
    visibility: field('contact_visibility', 'owner_writable', 'private_internal', 'required'),
    preferredContactMethod: field('contact_method', 'owner_writable', 'private_internal', 'required'),
    callbackPreferences: field('map', 'owner_writable', 'private_internal'),
    privateAddress: field('map|null', 'owner_writable', 'private_internal'),
    currentRejection: field('moderation_feedback|null', 'trusted_only', 'private_internal'),
    createdAt: field('Timestamp', 'trusted_only', 'private_internal', 'required'),
    updatedAt: field('Timestamp', 'derived', 'private_internal', 'required'),
  }),
})

export const BUSINESS_OWNER_CONTRACT = Object.freeze({
  path: 'businessOwners/{uid}', documentId: 'owner_uid', schemaVersion: FIREBASE_CONTRACT_SCHEMA_VERSION,
  fields: Object.freeze({
    ownerId: field('string', 'trusted_only', 'private_internal', 'required'),
    businessId: field('string', 'trusted_only', 'private_internal', 'required'),
    createdAt: field('Timestamp', 'trusted_only', 'private_internal', 'required'),
    updatedAt: field('Timestamp', 'trusted_only', 'private_internal', 'required'),
  }),
})

export const ACCOUNT_DELETION_REQUEST_CONTRACT = Object.freeze({
  path: 'accountDeletionRequests/{uid}', documentId: 'firebase_auth_uid',
  fields: Object.freeze({
    uid: field('string', 'trusted_only', 'private_internal', 'required'),
    state: field('account_deletion_request_state', 'trusted_only', 'private_internal', 'required'),
    requestedAt: field('Timestamp', 'trusted_only', 'private_internal', 'required'),
    requestedBy: field('string', 'trusted_only', 'private_internal', 'required'),
    cancelledAt: field('Timestamp|null', 'trusted_only', 'private_internal'),
    finalizationStartedAt: field('Timestamp|null', 'trusted_only', 'private_internal'),
    finalizedBy: field('string|null', 'trusted_only', 'private_internal'),
    completedAt: field('Timestamp|null', 'trusted_only', 'private_internal'),
    lastCompletedStep: field('account_deletion_checkpoint|null', 'trusted_only', 'private_internal'),
    failureCode: field('account_deletion_failure_code|null', 'trusted_only', 'private_internal'),
    retryCount: field('number', 'trusted_only', 'private_internal'),
    leaseId: field('string|null', 'trusted_only', 'private_internal'),
    leaseExpiresAt: field('Timestamp|null', 'trusted_only', 'private_internal'),
    cleanupCounts: field('sanitized_count_map|null', 'trusted_only', 'private_internal'),
    retainedConsentEvidence: field('minimal_consent_evidence|null', 'trusted_only', 'private_internal'),
    updatedAt: field('Timestamp', 'trusted_only', 'private_internal', 'required'),
    requestVersion: field('number', 'trusted_only', 'private_internal', 'required'),
  }),
})
