import en from './en.json'
import { createFallbackLocale } from './createFallbackLocale.js'

export default createFallbackLocale(en, {
  marketing: { hero: { activeProfile: "Profil publiczny", previousBusiness: "Poprzednia firma", nextBusiness: "Następna firma", businessPosition: "Firma {{current}} z {{total}}" }, trust: { verified: { title: "Weryfikacja firm", comingSoon: "Wkrótce", description: "Opracowujemy proces weryfikacji, który pomoże klientom rozpoznawać firmy, których tożsamość i dane rejestrowe zostały sprawdzone." } } },
  business: { completion: 'Profil firmy ukończony w {{percent}}%' },
  nav: { primary: 'Główna nawigacja', home: 'Strona główna', findServices: 'Znajdź usługi', join: 'Dołącz do HolaLocal' },
  auth: { logout: 'Wyloguj się' },
  account: { signIn: 'Zaloguj się', getStarted: 'Rozpocznij', navigationLabel: 'Nawigacja konta', profile: 'Mój profil', business: 'Moja firma', messages: 'Wiadomości', greeting: 'Cześć {{name}}', fallback: 'Konto' },
  language: { label: 'Język' },
  earlyAccess: {
    navigation: 'Wczesny dostęp',
    hero: { eyebrow: 'Wczesny dostęp · Costa del Sol i Gibraltar', title: 'Lokalne usługi, prawdziwi ludzie, lepsza komunikacja.', description: 'HolaLocal tworzy zaufane, wielojęzyczne miejsce do znajdowania lokalnych fachowców i bezpośredniego kontaktu z nimi — bez polegania na rozproszonych postach i poleceniach.', customerAction: 'Dołącz jako klient', businessAction: 'Utwórz roboczy profil firmy', note: 'Wczesne profile korzystają z prawdziwego konta HolaLocal i zostaną zachowane w pełnej usłudze. Robocze profile firm nie są publicznie widoczne.' },
    preview: { label: 'Wczesny dostęp do HolaLocal', badge: 'Łączymy lokalną społeczność', title: 'Jedno konto. Dwa sposoby udziału.', customerTitle: 'Szukasz lokalnej pomocy?', customerDescription: 'Ustaw preferencje języka i lokalizacji, aby przygotować się do korzystania z platformy.', businessTitle: 'Oferujesz lokalne usługi?', businessDescription: 'Utwórz prawdziwy profil firmy i zachowaj go prywatnie jako wersję roboczą.' },
    principles: { label: 'Zasady HolaLocal', local: 'Lokalność przede wszystkim', multilingual: 'Wielojęzyczność', privacy: 'Dbałość o prywatność', messaging: 'Bezpośrednie wiadomości HolaLocal' },
    info: { eyebrow: 'Pomóż rozwijać HolaLocal', title: 'Przygotuj się przed otwarciem platformy', description: 'Wczesny dostęp koncentruje się na przydatnych profilach, lokalnych potrzebach i usłudze, której można zaufać.', customers: { title: 'Dla klientów', description: 'Utwórz konto, wybierz język i powiedz nam, gdzie szukasz pomocy.', action: 'Dołącz do wczesnego dostępu' }, businesses: { title: 'Dla firm', description: 'Dodaj usługi, obszar działania, języki i opcjonalne publiczne dane kontaktowe w prywatnej wersji roboczej.', action: 'Utwórz profil roboczy' } },
    cta: { eyebrow: 'Tworzone dla społeczności', title: 'Pomóż kształtować przyszłość lokalnych usług w Hiszpanii.', description: 'Dołącz przed premierą i pomóż stworzyć zaufaną lokalną platformę dla klientów i firm.', action: 'Utwórz konto' },
    roadmap: { eyebrow: 'Co nadchodzi', title: '🚀 Plan rozwoju HolaLocal', description: 'Rozwijamy HolaLocal krok po kroku z pomocą społeczności wczesnego dostępu. Twoja opinia wpływa na każdą nową funkcję.', available: { title: 'Dostępne dzisiaj', items: ['Konta klientów', 'Konta firmowe', 'Profile firm', 'Wielojęzyczna strona', 'Rejestracja do wczesnego dostępu'] }, coming: { title: 'Wkrótce', items: ['Automatyczne tłumaczenie wiadomości', 'Wiadomości klientów i firm', 'Ulubione firmy', 'Weryfikacja firm', 'Recenzje i oceny', 'Aplikacja mobilna', 'Zaawansowane wyszukiwanie i filtry', 'Powiadomienia'] } },
    languageNotice: { title: '🌍 Języki rozwijają się razem z HolaLocal', intro: 'HolaLocal powstaje z myślą o międzynarodowych społecznościach w całej Hiszpanii.', refining: 'Podczas wczesnego dostępu niektóre tłumaczenia mogą nadal zawierać dopracowywane sformułowania.', feedback: 'Twoje uwagi pomagają nam ulepszać tłumaczenia i czynić HolaLocal bardziej przyjaznym dla wszystkich.', selectorNote: 'Niektóre tłumaczenia są nadal dopracowywane podczas wczesnego dostępu.' },
    footer: { description: 'Tworzymy zaufaną, wielojęzyczną platformę łączącą klientów z lokalnymi firmami w całej Hiszpanii.' },
  },
  legalPages: { version: 'Wczesny dostęp · Wersja 1 · Obowiązuje od 4 lipca 2026 r.', privacy: { title: 'Polityka prywatności', description: 'Ta polityka wyjaśnia, jak HolaLocal przetwarza dane osobowe podczas wczesnego dostępu.', audience: 'Dla kogo jest HolaLocal', information: 'Informacje, które możemy zbierać', purpose: 'Dlaczego wykorzystujemy informacje', profiles: 'Profile wczesnego dostępu', providers: 'Dostawcy usług i przechowywanie', visibility: 'Widoczność danych kontaktowych', deletion: 'Usuwanie danych i Twoje wybory', security: 'Bezpieczeństwo', changes: 'Zmiany polityki' }, terms: { title: 'Warunki korzystania', description: 'Te warunki obowiązują podczas tworzenia konta lub korzystania z wczesnego dostępu do HolaLocal.', account: 'Twoje konto', customers: 'Konta klientów', businesses: 'Profile firm', prohibited: 'Zabronione zachowania', messaging: 'Wiadomości i tłumaczenia', changes: 'Zmiany, zawieszenie i usunięcie', availability: 'Dostępność i odpowiedzialność', law: 'Prawo właściwe' }, contact: { description: 'Pytania, opinie i pomocne zgłoszenia błędów są mile widziane podczas tworzenia HolaLocal.', help: 'Jak możemy pomóc', email: 'Napisz do nas', response: 'Czas odpowiedzi może się różnić podczas wczesnego dostępu.', general: 'Pytania ogólne', generalText: 'pytania o HolaLocal i wczesny dostęp.', business: 'Pytania firmowe', businessText: 'pomoc w przygotowaniu profilu firmy.', bugs: 'Zgłoszenia błędów', bugsText: 'opisz, co się stało, używaną stronę i oczekiwany rezultat.', feedback: 'Opinie i sugestie', feedbackText: 'powiedz, jak uczynić HolaLocal bardziej użytecznym lokalnie.', privacy: 'Prywatność lub usunięcie konta', privacyText: 'skontaktuj się z nami z adresu przypisanego do konta, abyśmy mogli zweryfikować prośbę.' } },
  services: { emptyTitle: 'Nie ma jeszcze publicznie widocznych firm.', emptyDescription: 'Zajrzyj wkrótce albo zarejestruj firmę, aby przygotować profil do weryfikacji.', emptyAction: 'Zarejestruj firmę', noReviews: 'Brak recenzji' }, footer: { description: 'Zaufana, wielojęzyczna lokalna społeczność do znajdowania i oferowania usług na Costa del Sol i w Gibraltarze.', platform: 'Platforma', platformLabel: 'Linki platformy', legal: 'Informacje prawne', legalLabel: 'Linki prawne', account: 'Konto', accountLabel: 'Linki konta', privacy: 'Polityka prywatności', terms: 'Warunki', contact: 'Kontakt', language: 'Język', copyright: '© {{year}} HolaLocal', poweredBy: 'Obsługiwane przez PIXORA' },
})
