import en from './en.json'
import { createFallbackLocale } from './createFallbackLocale.js'

export default createFallbackLocale(en, {
  business: { completion: 'Profilul afacerii este completat {{percent}}%' },
  nav: { primary: 'Navigare principală', home: 'Acasă', findServices: 'Găsește servicii', join: 'Alătură-te HolaLocal' }, auth: { logout: 'Deconectare' }, account: { signIn: 'Autentificare', getStarted: 'Începe', navigationLabel: 'Navigarea contului', profile: 'Profilul meu', business: 'Afacerea mea', messages: 'Mesaje', greeting: 'Salut, {{name}}', fallback: 'Cont' }, language: { label: 'Limbă' },
  earlyAccess: {
    navigation: 'Acces timpuriu', hero: { eyebrow: 'Acces timpuriu · Costa del Sol și Gibraltar', title: 'Servicii locale, oameni reali, comunicare mai clară.', description: 'HolaLocal construiește un spațiu de încredere și multilingv în care găsești profesioniști locali și comunici direct cu ei, fără postări și recomandări răspândite.', customerAction: 'Înscrie-te ca client', businessAction: 'Creează un profil de afacere ciornă', note: 'Profilurile timpurii folosesc contul tău real HolaLocal și vor fi păstrate în serviciul complet. Profilurile de afacere ciornă nu sunt publice.' },
    preview: { label: 'Acces timpuriu HolaLocal', badge: 'Comunități locale mai apropiate', title: 'Un cont. Două moduri de a participa.', customerTitle: 'Cauți ajutor local?', customerDescription: 'Setează preferințele de limbă și locație pentru accesul viitor la platformă.', businessTitle: 'Oferi servicii locale?', businessDescription: 'Construiește acum profilul real al afacerii și păstrează-l privat ca ciornă.' },
    principles: { label: 'Principiile HolaLocal', local: 'Prioritate locală', multilingual: 'Multilingv', privacy: 'Grijă pentru confidențialitate', messaging: 'Mesagerie directă HolaLocal' },
    info: { eyebrow: 'Ajută la dezvoltarea HolaLocal', title: 'Pregătește-te înainte de deschiderea platformei', description: 'Accesul timpuriu pune accent pe profiluri utile, nevoi locale și un serviciu de încredere.', customers: { title: 'Pentru clienți', description: 'Creează contul, alege limba și spune-ne unde cauți ajutor.', action: 'Înscrie-te în accesul timpuriu' }, businesses: { title: 'Pentru afaceri', description: 'Adaugă serviciile, zonele, limbile și preferințele opționale de contact public într-o ciornă privată.', action: 'Începe profilul ciornă' } },
    cta: { eyebrow: 'Creat pentru comunitate', title: 'Ajută la modelarea viitorului serviciilor locale din Spania.', description: 'Alătură-te înainte de lansare și ajută la construirea unei platforme locale de încredere pentru clienți și afaceri.', action: 'Creează contul' },
    roadmap: { eyebrow: 'Ce urmează', title: '🚀 Planul HolaLocal', description: 'Construim HolaLocal pas cu pas, cu ajutorul comunității de acces timpuriu. Feedbackul tău modelează fiecare funcție nouă.', available: { title: 'Disponibil astăzi', items: ['Conturi de clienți', 'Conturi de afaceri', 'Profiluri de afaceri', 'Site multilingv', 'Înregistrare pentru acces timpuriu'] }, coming: { title: 'În curând', items: ['Traducerea automată a mesajelor', 'Mesagerie între clienți și afaceri', 'Afaceri favorite', 'Verificarea afacerilor', 'Recenzii și evaluări', 'Aplicație mobilă', 'Căutare și filtrare avansată', 'Notificări'] } },
    languageNotice: { title: '🌍 Limbile cresc odată cu HolaLocal', intro: 'HolaLocal este construit pentru comunitățile internaționale din Spania.', refining: 'În timpul accesului timpuriu, unele traduceri pot conține formulări care sunt încă îmbunătățite.', feedback: 'Feedbackul tău ne ajută să îmbunătățim traducerile și să facem HolaLocal mai primitor pentru toți.', selectorNote: 'Unele traduceri sunt încă îmbunătățite în timpul accesului timpuriu.' }, footer: { description: 'Construim o platformă multilingvă de încredere care conectează clienții cu afaceri locale din întreaga Spanie.' },
  },
  legalPages: { version: 'Acces timpuriu · Versiunea 1 · În vigoare din 4 iulie 2026', privacy: { title: 'Politica de confidențialitate', description: 'Această politică explică modul în care HolaLocal gestionează datele personale în timpul accesului timpuriu.', audience: 'Cui se adresează HolaLocal', information: 'Informații pe care le putem colecta', purpose: 'De ce folosim informațiile', profiles: 'Profiluri de acces timpuriu', providers: 'Furnizori și stocare', visibility: 'Vizibilitatea datelor de contact', deletion: 'Ștergerea și opțiunile tale', security: 'Securitate', changes: 'Modificări ale politicii' }, terms: { title: 'Termeni de utilizare', description: 'Acești termeni se aplică atunci când creezi un cont sau folosești accesul timpuriu HolaLocal.', account: 'Contul tău', customers: 'Conturi de clienți', businesses: 'Profiluri de afaceri', prohibited: 'Comportament interzis', messaging: 'Mesagerie și traducere', changes: 'Modificări, suspendare și eliminare', availability: 'Disponibilitate și responsabilitate', law: 'Legea aplicabilă' }, contact: { description: 'Întrebările, feedbackul și rapoartele utile de erori sunt binevenite în timp ce construim HolaLocal.', help: 'Cum te putem ajuta', email: 'Trimite-ne un email', response: 'Timpul de răspuns poate varia în timpul accesului timpuriu.', general: 'Întrebări generale', generalText: 'întrebări despre HolaLocal și accesul timpuriu.', business: 'Întrebări pentru afaceri', businessText: 'ajutor pentru pregătirea unui profil de afacere.', bugs: 'Rapoarte de erori', bugsText: 'spune-ne ce s-a întâmplat, pagina folosită și rezultatul așteptat.', feedback: 'Feedback și sugestii', feedbackText: 'spune-ne cum poate deveni HolaLocal mai util local.', privacy: 'Confidențialitate sau ștergerea contului', privacyText: 'contactează-ne de la adresa contului pentru a verifica solicitarea.' } }, services: { emptyTitle: 'Încă nu există afaceri listate public.', emptyDescription: 'Revino curând sau înregistrează-ți afacerea pentru a pregăti un profil pentru verificare.', emptyAction: 'Înregistrează o afacere' }, footer: { description: 'O comunitate locală de încredere, multilingvă, pentru a găsi și oferi servicii locale în Costa del Sol și Gibraltar.', platform: 'Platformă', platformLabel: 'Linkuri platformă', legal: 'Legal', legalLabel: 'Linkuri legale', account: 'Cont', accountLabel: 'Linkuri cont', privacy: 'Politica de confidențialitate', terms: 'Termeni', contact: 'Contact', language: 'Limbă', copyright: '© {{year}} HolaLocal', poweredBy: 'Creat de PIXORA' },
})
