import { savedBusinessEnglishTranslations } from '../savedBusinessEnglishTranslations.js'

const translations = {
  cs: ['Uložit firmu', 'Uloženo', 'Ukládání…', 'Odebrat z uložených', 'Odebírání…', 'Kontrola uloženého stavu…', 'Zkusit znovu', 'Nepodařilo se ověřit, zda je firma uložena. Zkuste to znovu.', 'Firmu se nepodařilo uložit. Zkuste to znovu.', 'Firmu se nepodařilo odebrat z uložených. Zkuste to znovu.', 'Uložit na později', 'Přihlaste se a ukládejte firmy', 'Přihlaste se nebo si vytvořte účet a uložte si tuto firmu. Poté se vrátíte na tuto stránku.'],
  da: ['Gem virksomhed', 'Gemt', 'Gemmer…', 'Fjern fra gemte', 'Fjerner…', 'Kontrollerer gemt status…', 'Prøv igen', 'Vi kunne ikke kontrollere, om virksomheden er gemt. Prøv igen.', 'Vi kunne ikke gemme virksomheden. Prøv igen.', 'Vi kunne ikke fjerne virksomheden fra gemte. Prøv igen.', 'Gem til senere', 'Log ind for at gemme virksomheder', 'Log ind eller opret en konto for at gemme denne virksomhed. Du vender tilbage til denne side bagefter.'],
  de: ['Unternehmen speichern', 'Gespeichert', 'Wird gespeichert…', 'Aus Gespeicherten entfernen', 'Wird entfernt…', 'Gespeicherten Status prüfen…', 'Erneut versuchen', 'Wir konnten nicht prüfen, ob dieses Unternehmen gespeichert ist. Bitte versuche es erneut.', 'Dieses Unternehmen konnte nicht gespeichert werden. Bitte versuche es erneut.', 'Dieses Unternehmen konnte nicht aus den gespeicherten entfernt werden. Bitte versuche es erneut.', 'Für später speichern', 'Anmelden, um Unternehmen zu speichern', 'Melde dich an oder erstelle ein Konto, um dieses Unternehmen zu speichern. Anschließend kehrst du zu dieser Seite zurück.'],
  es: ['Guardar negocio', 'Guardado', 'Guardando…', 'Eliminar de guardados', 'Eliminando…', 'Comprobando estado…', 'Reintentar', 'No pudimos comprobar si este negocio está guardado. Inténtalo de nuevo.', 'No pudimos guardar este negocio. Inténtalo de nuevo.', 'No pudimos eliminar este negocio de guardados. Inténtalo de nuevo.', 'Guardar para más tarde', 'Inicia sesión para guardar negocios', 'Inicia sesión o crea una cuenta para guardar este negocio. Después volverás a esta página.'],
  fi: ['Tallenna yritys', 'Tallennettu', 'Tallennetaan…', 'Poista tallennetuista', 'Poistetaan…', 'Tarkistetaan tallennustilaa…', 'Yritä uudelleen', 'Emme voineet tarkistaa, onko yritys tallennettu. Yritä uudelleen.', 'Yritystä ei voitu tallentaa. Yritä uudelleen.', 'Yritystä ei voitu poistaa tallennetuista. Yritä uudelleen.', 'Tallenna myöhemmäksi', 'Kirjaudu sisään tallentaaksesi yrityksiä', 'Kirjaudu sisään tai luo tili tallentaaksesi tämän yrityksen. Palaat sen jälkeen tälle sivulle.'],
  fr: ['Enregistrer l’entreprise', 'Enregistré', 'Enregistrement…', 'Retirer des entreprises enregistrées', 'Suppression…', 'Vérification de l’enregistrement…', 'Réessayer', 'Impossible de vérifier si cette entreprise est enregistrée. Réessayez.', 'Impossible d’enregistrer cette entreprise. Réessayez.', 'Impossible de retirer cette entreprise des enregistrements. Réessayez.', 'Enregistrer pour plus tard', 'Connectez-vous pour enregistrer des entreprises', 'Connectez-vous ou créez un compte pour enregistrer cette entreprise. Vous reviendrez ensuite sur cette page.'],
  hu: ['Vállalkozás mentése', 'Mentve', 'Mentés…', 'Eltávolítás a mentettek közül', 'Eltávolítás…', 'Mentési állapot ellenőrzése…', 'Újra', 'Nem sikerült ellenőrizni, hogy a vállalkozás mentve van-e. Próbáld újra.', 'Nem sikerült menteni a vállalkozást. Próbáld újra.', 'Nem sikerült eltávolítani a vállalkozást a mentettek közül. Próbáld újra.', 'Mentés későbbre', 'Jelentkezz be vállalkozások mentéséhez', 'Jelentkezz be vagy hozz létre fiókot a vállalkozás mentéséhez. Ezután visszatérsz erre az oldalra.'],
  it: ['Salva attività', 'Salvata', 'Salvataggio…', 'Rimuovi dai salvati', 'Rimozione…', 'Verifica dello stato…', 'Riprova', 'Non è stato possibile verificare se questa attività è salvata. Riprova.', 'Non è stato possibile salvare questa attività. Riprova.', 'Non è stato possibile rimuovere questa attività dai salvati. Riprova.', 'Salva per dopo', 'Accedi per salvare le attività', 'Accedi o crea un account per salvare questa attività. In seguito tornerai a questa pagina.'],
  nl: ['Bedrijf opslaan', 'Opgeslagen', 'Opslaan…', 'Uit opgeslagen verwijderen', 'Verwijderen…', 'Opgeslagen status controleren…', 'Opnieuw proberen', 'We konden niet controleren of dit bedrijf is opgeslagen. Probeer het opnieuw.', 'We konden dit bedrijf niet opslaan. Probeer het opnieuw.', 'We konden dit bedrijf niet uit opgeslagen verwijderen. Probeer het opnieuw.', 'Bewaar voor later', 'Log in om bedrijven op te slaan', 'Log in of maak een account aan om dit bedrijf op te slaan. Daarna keer je terug naar deze pagina.'],
  no: ['Lagre bedrift', 'Lagret', 'Lagrer…', 'Fjern fra lagrede', 'Fjerner…', 'Kontrollerer lagret status…', 'Prøv igjen', 'Vi kunne ikke kontrollere om bedriften er lagret. Prøv igjen.', 'Vi kunne ikke lagre bedriften. Prøv igjen.', 'Vi kunne ikke fjerne bedriften fra lagrede. Prøv igjen.', 'Lagre til senere', 'Logg inn for å lagre bedrifter', 'Logg inn eller opprett en konto for å lagre denne bedriften. Du kommer tilbake til denne siden etterpå.'],
  pl: ['Zapisz firmę', 'Zapisano', 'Zapisywanie…', 'Usuń z zapisanych', 'Usuwanie…', 'Sprawdzanie zapisu…', 'Spróbuj ponownie', 'Nie udało się sprawdzić, czy firma jest zapisana. Spróbuj ponownie.', 'Nie udało się zapisać firmy. Spróbuj ponownie.', 'Nie udało się usunąć firmy z zapisanych. Spróbuj ponownie.', 'Zapisz na później', 'Zaloguj się, aby zapisywać firmy', 'Zaloguj się lub utwórz konto, aby zapisać tę firmę. Potem wrócisz na tę stronę.'],
  pt: ['Guardar empresa', 'Guardada', 'A guardar…', 'Remover das guardadas', 'A remover…', 'A verificar estado…', 'Tentar novamente', 'Não foi possível verificar se esta empresa está guardada. Tente novamente.', 'Não foi possível guardar esta empresa. Tente novamente.', 'Não foi possível remover esta empresa das guardadas. Tente novamente.', 'Guardar para mais tarde', 'Inicie sessão para guardar empresas', 'Inicie sessão ou crie uma conta para guardar esta empresa. Depois regressará a esta página.'],
  ro: ['Salvează afacerea', 'Salvată', 'Se salvează…', 'Elimină din salvate', 'Se elimină…', 'Se verifică starea…', 'Încearcă din nou', 'Nu am putut verifica dacă afacerea este salvată. Încearcă din nou.', 'Nu am putut salva afacerea. Încearcă din nou.', 'Nu am putut elimina afacerea din cele salvate. Încearcă din nou.', 'Salvează pentru mai târziu', 'Autentifică-te pentru a salva afaceri', 'Autentifică-te sau creează un cont pentru a salva această afacere. Apoi vei reveni la această pagină.'],
  sk: ['Uložiť firmu', 'Uložené', 'Ukladanie…', 'Odstrániť z uložených', 'Odstraňovanie…', 'Kontrola uloženého stavu…', 'Skúsiť znova', 'Nepodarilo sa overiť, či je firma uložená. Skúste to znova.', 'Firmu sa nepodarilo uložiť. Skúste to znova.', 'Firmu sa nepodarilo odstrániť z uložených. Skúste to znova.', 'Uložiť na neskôr', 'Prihláste sa a ukladajte firmy', 'Prihláste sa alebo si vytvorte účet a uložte si túto firmu. Potom sa vrátite na túto stránku.'],
  sv: ['Spara företag', 'Sparat', 'Sparar…', 'Ta bort från sparade', 'Tar bort…', 'Kontrollerar sparad status…', 'Försök igen', 'Vi kunde inte kontrollera om företaget är sparat. Försök igen.', 'Vi kunde inte spara företaget. Försök igen.', 'Vi kunde inte ta bort företaget från sparade. Försök igen.', 'Spara till senare', 'Logga in för att spara företag', 'Logga in eller skapa ett konto för att spara företaget. Därefter återgår du till den här sidan.'],
  uk: ['Зберегти компанію', 'Збережено', 'Збереження…', 'Видалити зі збережених', 'Видалення…', 'Перевірка стану…', 'Спробувати ще раз', 'Не вдалося перевірити, чи збережено компанію. Спробуйте ще раз.', 'Не вдалося зберегти компанію. Спробуйте ще раз.', 'Не вдалося видалити компанію зі збережених. Спробуйте ще раз.', 'Зберегти на потім', 'Увійдіть, щоб зберігати компанії', 'Увійдіть або створіть обліковий запис, щоб зберегти цю компанію. Після цього ви повернетеся на цю сторінку.'],
}

const keys = ['save', 'saved', 'saving', 'remove', 'removing', 'checking', 'retry', 'loadFailed', 'saveFailed', 'removeFailed', 'authEyebrow', 'authTitle', 'authDescription']

const pageTranslations = {
  es: ['Negocios guardados', 'Negocios guardados', 'Consulta y gestiona los negocios que has guardado.', 'Tu cuenta', 'Negocios guardados', 'Reúne negocios locales útiles y vuelve a sus perfiles públicos.', 'Cargando negocios guardados…', 'No pudimos cargar tus negocios guardados. Inténtalo de nuevo.', 'Aún no hay negocios guardados', 'Guarda negocios mientras exploras servicios y aparecerán aquí.', 'Explorar servicios', 'Abrir negocio', 'Eliminar {{name}} de negocios guardados', 'Negocios guardados', 'Negocio no disponible', 'Este anuncio ya no está disponible públicamente. Puedes eliminarlo de tus negocios guardados.', 'Cargar más', 'Cargando más…', 'No pudimos cargar más negocios guardados. Inténtalo de nuevo.'],
  fr: ['Entreprises enregistrées', 'Entreprises enregistrées', 'Consultez et gérez les entreprises que vous avez enregistrées.', 'Votre compte', 'Entreprises enregistrées', 'Regroupez les entreprises locales utiles et retrouvez leurs profils publics.', 'Chargement des entreprises enregistrées…', 'Impossible de charger vos entreprises enregistrées. Réessayez.', 'Aucune entreprise enregistrée', 'Enregistrez des entreprises en parcourant les services ; elles apparaîtront ici.', 'Parcourir les services', 'Ouvrir l’entreprise', 'Retirer {{name}} des entreprises enregistrées', 'Entreprises enregistrées', 'Entreprise indisponible', 'Cette annonce n’est plus publique. Vous pouvez la retirer de vos entreprises enregistrées.', 'Afficher plus', 'Chargement…', 'Impossible de charger davantage d’entreprises. Réessayez.'],
  de: ['Gespeicherte Unternehmen', 'Gespeicherte Unternehmen', 'Gespeicherte Unternehmen ansehen und verwalten.', 'Dein Konto', 'Gespeicherte Unternehmen', 'Bewahre nützliche lokale Unternehmen auf und kehre zu ihren öffentlichen Profilen zurück.', 'Gespeicherte Unternehmen werden geladen…', 'Gespeicherte Unternehmen konnten nicht geladen werden. Bitte erneut versuchen.', 'Noch keine Unternehmen gespeichert', 'Speichere Unternehmen beim Durchsuchen der Dienstleistungen; sie erscheinen dann hier.', 'Dienstleistungen durchsuchen', 'Unternehmen öffnen', '{{name}} aus gespeicherten Unternehmen entfernen', 'Gespeicherte Unternehmen', 'Unternehmen nicht verfügbar', 'Dieser Eintrag ist nicht mehr öffentlich verfügbar. Du kannst ihn aus deinen gespeicherten Unternehmen entfernen.', 'Mehr laden', 'Weitere werden geladen…', 'Weitere gespeicherte Unternehmen konnten nicht geladen werden. Bitte erneut versuchen.'],
  nl: ['Opgeslagen bedrijven', 'Opgeslagen bedrijven', 'Bekijk en beheer de bedrijven die je hebt opgeslagen.', 'Je account', 'Opgeslagen bedrijven', 'Bewaar nuttige lokale bedrijven bij elkaar en keer terug naar hun openbare profielen.', 'Opgeslagen bedrijven laden…', 'We konden je opgeslagen bedrijven niet laden. Probeer het opnieuw.', 'Nog geen bedrijven opgeslagen', 'Sla bedrijven op tijdens het zoeken naar diensten; ze verschijnen hier.', 'Diensten bekijken', 'Bedrijf openen', '{{name}} uit opgeslagen bedrijven verwijderen', 'Opgeslagen bedrijven', 'Bedrijf niet beschikbaar', 'Deze vermelding is niet meer openbaar beschikbaar. Je kunt deze uit je opgeslagen bedrijven verwijderen.', 'Meer laden', 'Meer laden…', 'We konden niet meer opgeslagen bedrijven laden. Probeer het opnieuw.'],
  pt: ['Empresas guardadas', 'Empresas guardadas', 'Veja e faça a gestão das empresas que guardou.', 'A sua conta', 'Empresas guardadas', 'Mantenha empresas locais úteis reunidas e volte aos seus perfis públicos.', 'A carregar empresas guardadas…', 'Não foi possível carregar as empresas guardadas. Tente novamente.', 'Ainda não há empresas guardadas', 'Guarde empresas ao explorar serviços e elas aparecerão aqui.', 'Explorar serviços', 'Abrir empresa', 'Remover {{name}} das empresas guardadas', 'Empresas guardadas', 'Empresa indisponível', 'Este anúncio já não está disponível publicamente. Pode removê-lo das empresas guardadas.', 'Carregar mais', 'A carregar mais…', 'Não foi possível carregar mais empresas guardadas. Tente novamente.'],
  it: ['Attività salvate', 'Attività salvate', 'Visualizza e gestisci le attività che hai salvato.', 'Il tuo account', 'Attività salvate', 'Riunisci le attività locali utili e torna ai loro profili pubblici.', 'Caricamento delle attività salvate…', 'Non è stato possibile caricare le attività salvate. Riprova.', 'Nessuna attività salvata', 'Salva le attività mentre esplori i servizi e appariranno qui.', 'Esplora i servizi', 'Apri attività', 'Rimuovi {{name}} dalle attività salvate', 'Attività salvate', 'Attività non disponibile', 'Questo annuncio non è più disponibile pubblicamente. Puoi rimuoverlo dalle attività salvate.', 'Carica altro', 'Caricamento…', 'Non è stato possibile caricare altre attività. Riprova.'],
  pl: ['Zapisane firmy', 'Zapisane firmy', 'Przeglądaj zapisane firmy i zarządzaj nimi.', 'Twoje konto', 'Zapisane firmy', 'Zachowaj przydatne lokalne firmy i wracaj do ich publicznych profili.', 'Wczytywanie zapisanych firm…', 'Nie udało się wczytać zapisanych firm. Spróbuj ponownie.', 'Brak zapisanych firm', 'Zapisuj firmy podczas przeglądania usług, a pojawią się tutaj.', 'Przeglądaj usługi', 'Otwórz firmę', 'Usuń {{name}} z zapisanych firm', 'Zapisane firmy', 'Firma niedostępna', 'Ta oferta nie jest już publicznie dostępna. Możesz usunąć ją z zapisanych firm.', 'Wczytaj więcej', 'Wczytywanie…', 'Nie udało się wczytać kolejnych zapisanych firm. Spróbuj ponownie.'],
  ro: ['Afaceri salvate', 'Afaceri salvate', 'Vezi și gestionează afacerile salvate.', 'Contul tău', 'Afaceri salvate', 'Păstrează afacerile locale utile împreună și revino la profilurile lor publice.', 'Se încarcă afacerile salvate…', 'Nu am putut încărca afacerile salvate. Încearcă din nou.', 'Nicio afacere salvată', 'Salvează afaceri în timp ce explorezi serviciile și vor apărea aici.', 'Explorează serviciile', 'Deschide afacerea', 'Elimină {{name}} din afacerile salvate', 'Afaceri salvate', 'Afacere indisponibilă', 'Această listare nu mai este disponibilă public. O poți elimina din afacerile salvate.', 'Încarcă mai multe', 'Se încarcă…', 'Nu am putut încărca mai multe afaceri salvate. Încearcă din nou.'],
  cs: ['Uložené firmy', 'Uložené firmy', 'Prohlížejte a spravujte uložené firmy.', 'Váš účet', 'Uložené firmy', 'Mějte užitečné místní firmy pohromadě a vraťte se k jejich veřejným profilům.', 'Načítání uložených firem…', 'Uložené firmy se nepodařilo načíst. Zkuste to znovu.', 'Zatím žádné uložené firmy', 'Ukládejte firmy při procházení služeb a zobrazí se zde.', 'Procházet služby', 'Otevřít firmu', 'Odebrat {{name}} z uložených firem', 'Uložené firmy', 'Firma není dostupná', 'Tato nabídka již není veřejně dostupná. Můžete ji odebrat z uložených firem.', 'Načíst další', 'Načítání…', 'Další uložené firmy se nepodařilo načíst. Zkuste to znovu.'],
  sk: ['Uložené firmy', 'Uložené firmy', 'Zobrazte a spravujte uložené firmy.', 'Váš účet', 'Uložené firmy', 'Majte užitočné miestne firmy pokope a vráťte sa k ich verejným profilom.', 'Načítavajú sa uložené firmy…', 'Uložené firmy sa nepodarilo načítať. Skúste to znova.', 'Zatiaľ žiadne uložené firmy', 'Ukladajte firmy pri prehliadaní služieb a zobrazia sa tu.', 'Prehliadať služby', 'Otvoriť firmu', 'Odstrániť {{name}} z uložených firiem', 'Uložené firmy', 'Firma nie je dostupná', 'Táto ponuka už nie je verejne dostupná. Môžete ju odstrániť z uložených firiem.', 'Načítať ďalšie', 'Načítavanie…', 'Ďalšie uložené firmy sa nepodarilo načítať. Skúste to znova.'],
  hu: ['Mentett vállalkozások', 'Mentett vállalkozások', 'A mentett vállalkozások megtekintése és kezelése.', 'A fiókod', 'Mentett vállalkozások', 'Tartsd együtt a hasznos helyi vállalkozásokat, és térj vissza nyilvános profiljukhoz.', 'Mentett vállalkozások betöltése…', 'Nem sikerült betölteni a mentett vállalkozásokat. Próbáld újra.', 'Még nincs mentett vállalkozás', 'Ments vállalkozásokat a szolgáltatások böngészése közben, és itt jelennek meg.', 'Szolgáltatások böngészése', 'Vállalkozás megnyitása', '{{name}} eltávolítása a mentett vállalkozások közül', 'Mentett vállalkozások', 'A vállalkozás nem elérhető', 'Ez a hirdetés már nem nyilvános. Eltávolíthatod a mentett vállalkozások közül.', 'Továbbiak betöltése', 'Betöltés…', 'Nem sikerült további mentett vállalkozásokat betölteni. Próbáld újra.'],
  uk: ['Збережені компанії', 'Збережені компанії', 'Переглядайте збережені компанії та керуйте ними.', 'Ваш обліковий запис', 'Збережені компанії', 'Зберігайте корисні місцеві компанії разом і повертайтеся до їхніх публічних профілів.', 'Завантаження збережених компаній…', 'Не вдалося завантажити збережені компанії. Спробуйте ще раз.', 'Збережених компаній ще немає', 'Зберігайте компанії під час перегляду послуг — вони з’являться тут.', 'Переглянути послуги', 'Відкрити компанію', 'Видалити {{name}} зі збережених компаній', 'Збережені компанії', 'Компанія недоступна', 'Ця пропозиція більше не доступна публічно. Її можна видалити зі збережених.', 'Завантажити ще', 'Завантаження…', 'Не вдалося завантажити більше збережених компаній. Спробуйте ще раз.'],
  sv: ['Sparade företag', 'Sparade företag', 'Visa och hantera de företag du har sparat.', 'Ditt konto', 'Sparade företag', 'Samla användbara lokala företag och återvänd till deras offentliga profiler.', 'Läser in sparade företag…', 'Vi kunde inte läsa in dina sparade företag. Försök igen.', 'Inga sparade företag ännu', 'Spara företag när du utforskar tjänster så visas de här.', 'Utforska tjänster', 'Öppna företag', 'Ta bort {{name}} från sparade företag', 'Sparade företag', 'Företaget är inte tillgängligt', 'Den här annonsen är inte längre offentlig. Du kan ta bort den från sparade företag.', 'Läs in fler', 'Läser in…', 'Vi kunde inte läsa in fler sparade företag. Försök igen.'],
  da: ['Gemte virksomheder', 'Gemte virksomheder', 'Se og administrer de virksomheder, du har gemt.', 'Din konto', 'Gemte virksomheder', 'Saml nyttige lokale virksomheder, og vend tilbage til deres offentlige profiler.', 'Indlæser gemte virksomheder…', 'Vi kunne ikke indlæse dine gemte virksomheder. Prøv igen.', 'Ingen gemte virksomheder endnu', 'Gem virksomheder, mens du udforsker tjenester, så vises de her.', 'Udforsk tjenester', 'Åbn virksomhed', 'Fjern {{name}} fra gemte virksomheder', 'Gemte virksomheder', 'Virksomheden er ikke tilgængelig', 'Denne annonce er ikke længere offentlig. Du kan fjerne den fra gemte virksomheder.', 'Indlæs flere', 'Indlæser…', 'Vi kunne ikke indlæse flere gemte virksomheder. Prøv igen.'],
  fi: ['Tallennetut yritykset', 'Tallennetut yritykset', 'Tarkastele ja hallitse tallentamiasi yrityksiä.', 'Tilisi', 'Tallennetut yritykset', 'Pidä hyödylliset paikalliset yritykset yhdessä ja palaa niiden julkisiin profiileihin.', 'Tallennettuja yrityksiä ladataan…', 'Tallennettuja yrityksiä ei voitu ladata. Yritä uudelleen.', 'Ei vielä tallennettuja yrityksiä', 'Tallenna yrityksiä palveluja selatessasi, niin ne näkyvät täällä.', 'Selaa palveluja', 'Avaa yritys', 'Poista {{name}} tallennetuista yrityksistä', 'Tallennetut yritykset', 'Yritys ei ole saatavilla', 'Tämä ilmoitus ei ole enää julkisesti saatavilla. Voit poistaa sen tallennetuista yrityksistä.', 'Lataa lisää', 'Ladataan…', 'Lisää tallennettuja yrityksiä ei voitu ladata. Yritä uudelleen.'],
  no: ['Lagrede bedrifter', 'Lagrede bedrifter', 'Se og administrer bedriftene du har lagret.', 'Kontoen din', 'Lagrede bedrifter', 'Samle nyttige lokale bedrifter og gå tilbake til de offentlige profilene deres.', 'Laster lagrede bedrifter…', 'Vi kunne ikke laste inn de lagrede bedriftene. Prøv igjen.', 'Ingen lagrede bedrifter ennå', 'Lagre bedrifter mens du utforsker tjenester, så vises de her.', 'Utforsk tjenester', 'Åpne bedrift', 'Fjern {{name}} fra lagrede bedrifter', 'Lagrede bedrifter', 'Bedriften er ikke tilgjengelig', 'Denne oppføringen er ikke lenger offentlig tilgjengelig. Du kan fjerne den fra lagrede bedrifter.', 'Last inn flere', 'Laster…', 'Vi kunne ikke laste inn flere lagrede bedrifter. Prøv igjen.'],
}

const pageKeys = ['navigation', 'metadataTitle', 'metadataDescription', 'eyebrow', 'title', 'description', 'loading', 'initialError', 'emptyTitle', 'emptyDescription', 'browseServices', 'openBusiness', 'removeLabel', 'itemsLabel', 'unavailable', 'unavailableDescription', 'loadMore', 'loadingMore', 'loadMoreError']

export const savedBusinessTranslations = {
  en: savedBusinessEnglishTranslations,
  ...Object.fromEntries(
    Object.entries(translations).map(([locale, values]) => [locale, {
      savedBusinesses: {
        ...Object.fromEntries(keys.slice(0, 10).map((key, index) => [key, values[index]])),
        authPrompt: {
          eyebrow: values[10],
          title: values[11],
          description: values[12],
        },
        page: Object.fromEntries(pageKeys.map((key, index) => [key, pageTranslations[locale][index]])),
      },
    }]),
  ),
}
