const taxonomy = (groups, services) => ({ services: { taxonomy: { groups, services } } })

export const serviceTaxonomyTranslations = Object.freeze({
  en: taxonomy(
    { homeProperty: 'Home & Property', professionalServices: 'Professional Services', healthBeautyLifestyle: 'Health, Beauty & Lifestyle', learningFamily: 'Learning & Family', pets: 'Pets', otherLocalServices: 'Other Local Services' },
    { plumber: 'Plumber', electrician: 'Electrician', cleaner: 'Cleaner', gardener: 'Gardener', builderRenovation: 'Builder & Renovation', painterDecorator: 'Painter & Decorator', handyman: 'Handyman', airConditioning: 'Air Conditioning', poolServices: 'Pool Services', pestControl: 'Pest Control', locksmith: 'Locksmith', removals: 'Removals', lawyer: 'Lawyer', accountant: 'Accountant', translatorInterpreter: 'Translator & Interpreter', graphicDesigner: 'Graphic Designer', webDesignerDeveloper: 'Web Designer & Developer', photographer: 'Photographer', marketing: 'Marketing', businessConsultant: 'Business Consultant', personalTrainer: 'Personal Trainer', hairdresser: 'Hairdresser', beautyServices: 'Beauty Services', massageWellness: 'Massage & Wellness', nutrition: 'Nutrition', yogaFitness: 'Yoga & Fitness', tutor: 'Tutor', languageTeacher: 'Language Teacher', musicTeacher: 'Music Teacher', childcareBabysitting: 'Childcare & Babysitting', dogWalker: 'Dog Walker', petSitter: 'Pet Sitter', petGroomer: 'Pet Groomer', dogTrainer: 'Dog Trainer', otherLocalService: 'Other Local Service' },
  ),
  es: taxonomy(
    { homeProperty: 'Hogar y propiedad', professionalServices: 'Servicios profesionales', healthBeautyLifestyle: 'Salud, belleza y bienestar', learningFamily: 'Aprendizaje y familia', pets: 'Mascotas', otherLocalServices: 'Otros servicios locales' },
    { plumber: 'Fontanero', electrician: 'Electricista', cleaner: 'Profesional de limpieza', gardener: 'Jardinero', builderRenovation: 'Construcción y reformas', painterDecorator: 'Pintor y decorador', handyman: 'Manitas', airConditioning: 'Aire acondicionado', poolServices: 'Servicios de piscinas', pestControl: 'Control de plagas', locksmith: 'Cerrajero', removals: 'Mudanzas', lawyer: 'Abogado', accountant: 'Contable', translatorInterpreter: 'Traductor e intérprete', graphicDesigner: 'Diseñador gráfico', webDesignerDeveloper: 'Diseñador y desarrollador web', photographer: 'Fotógrafo', marketing: 'Marketing', businessConsultant: 'Consultor empresarial', personalTrainer: 'Entrenador personal', hairdresser: 'Peluquero', beautyServices: 'Servicios de belleza', massageWellness: 'Masajes y bienestar', nutrition: 'Nutrición', yogaFitness: 'Yoga y fitness', tutor: 'Profesor particular', languageTeacher: 'Profesor de idiomas', musicTeacher: 'Profesor de música', childcareBabysitting: 'Cuidado infantil y canguro', dogWalker: 'Paseador de perros', petSitter: 'Cuidador de mascotas', petGroomer: 'Peluquero de mascotas', dogTrainer: 'Adiestrador canino', otherLocalService: 'Otro servicio local' },
  ),
  fr: taxonomy(
    { homeProperty: 'Maison et propriété', professionalServices: 'Services professionnels', healthBeautyLifestyle: 'Santé, beauté et bien-être', learningFamily: 'Apprentissage et famille', pets: 'Animaux', otherLocalServices: 'Autres services locaux' },
    { plumber: 'Plombier', electrician: 'Électricien', cleaner: 'Professionnel du nettoyage', gardener: 'Jardinier', builderRenovation: 'Construction et rénovation', painterDecorator: 'Peintre et décorateur', handyman: 'Bricoleur', airConditioning: 'Climatisation', poolServices: 'Services de piscine', pestControl: 'Lutte antiparasitaire', locksmith: 'Serrurier', removals: 'Déménagement', lawyer: 'Avocat', accountant: 'Comptable', translatorInterpreter: 'Traducteur et interprète', graphicDesigner: 'Graphiste', webDesignerDeveloper: 'Concepteur et développeur web', photographer: 'Photographe', marketing: 'Marketing', businessConsultant: 'Conseiller d’entreprise', personalTrainer: 'Coach personnel', hairdresser: 'Coiffeur', beautyServices: 'Services de beauté', massageWellness: 'Massage et bien-être', nutrition: 'Nutrition', yogaFitness: 'Yoga et fitness', tutor: 'Professeur particulier', languageTeacher: 'Professeur de langues', musicTeacher: 'Professeur de musique', childcareBabysitting: 'Garde d’enfants et baby-sitting', dogWalker: 'Promeneur de chiens', petSitter: 'Garde d’animaux', petGroomer: 'Toiletteur pour animaux', dogTrainer: 'Éducateur canin', otherLocalService: 'Autre service local' },
  ),
  de: taxonomy(
    { homeProperty: 'Haus und Grundstück', professionalServices: 'Professionelle Dienstleistungen', healthBeautyLifestyle: 'Gesundheit, Schönheit und Lebensstil', learningFamily: 'Lernen und Familie', pets: 'Haustiere', otherLocalServices: 'Andere lokale Dienstleistungen' },
    { plumber: 'Installateur', electrician: 'Elektriker', cleaner: 'Reinigungskraft', gardener: 'Gärtner', builderRenovation: 'Bau und Renovierung', painterDecorator: 'Maler und Dekorateur', handyman: 'Handwerker', airConditioning: 'Klimaanlagen', poolServices: 'Poolservice', pestControl: 'Schädlingsbekämpfung', locksmith: 'Schlüsseldienst', removals: 'Umzüge', lawyer: 'Rechtsanwalt', accountant: 'Buchhalter', translatorInterpreter: 'Übersetzer und Dolmetscher', graphicDesigner: 'Grafikdesigner', webDesignerDeveloper: 'Webdesigner und -entwickler', photographer: 'Fotograf', marketing: 'Marketing', businessConsultant: 'Unternehmensberater', personalTrainer: 'Personal Trainer', hairdresser: 'Friseur', beautyServices: 'Kosmetikdienstleistungen', massageWellness: 'Massage und Wellness', nutrition: 'Ernährungsberatung', yogaFitness: 'Yoga und Fitness', tutor: 'Nachhilfelehrer', languageTeacher: 'Sprachlehrer', musicTeacher: 'Musiklehrer', childcareBabysitting: 'Kinderbetreuung und Babysitting', dogWalker: 'Hundeausführer', petSitter: 'Tiersitter', petGroomer: 'Tierfriseur', dogTrainer: 'Hundetrainer', otherLocalService: 'Andere lokale Dienstleistung' },
  ),
  nl: taxonomy(
    { homeProperty: 'Huis en woning', professionalServices: 'Professionele diensten', healthBeautyLifestyle: 'Gezondheid, schoonheid en lifestyle', learningFamily: 'Leren en gezin', pets: 'Huisdieren', otherLocalServices: 'Andere lokale diensten' },
    { plumber: 'Loodgieter', electrician: 'Elektricien', cleaner: 'Schoonmaker', gardener: 'Tuinman', builderRenovation: 'Bouw en renovatie', painterDecorator: 'Schilder en decorateur', handyman: 'Klusjesman', airConditioning: 'Airconditioning', poolServices: 'Zwembaddiensten', pestControl: 'Ongediertebestrijding', locksmith: 'Slotenmaker', removals: 'Verhuizingen', lawyer: 'Advocaat', accountant: 'Boekhouder', translatorInterpreter: 'Vertaler en tolk', graphicDesigner: 'Grafisch ontwerper', webDesignerDeveloper: 'Webdesigner en -ontwikkelaar', photographer: 'Fotograaf', marketing: 'Marketing', businessConsultant: 'Bedrijfsadviseur', personalTrainer: 'Personal trainer', hairdresser: 'Kapper', beautyServices: 'Schoonheidsdiensten', massageWellness: 'Massage en wellness', nutrition: 'Voedingsadvies', yogaFitness: 'Yoga en fitness', tutor: 'Bijlesdocent', languageTeacher: 'Taaldocent', musicTeacher: 'Muziekdocent', childcareBabysitting: 'Kinderopvang en oppas', dogWalker: 'Hondenuitlater', petSitter: 'Dierenoppas', petGroomer: 'Dierentrimmer', dogTrainer: 'Hondentrainer', otherLocalService: 'Andere lokale dienst' },
  ),
  pt: taxonomy(
    { homeProperty: 'Casa e propriedade', professionalServices: 'Serviços profissionais', healthBeautyLifestyle: 'Saúde, beleza e estilo de vida', learningFamily: 'Aprendizagem e família', pets: 'Animais de estimação', otherLocalServices: 'Outros serviços locais' },
    { plumber: 'Canalizador', electrician: 'Eletricista', cleaner: 'Profissional de limpeza', gardener: 'Jardineiro', builderRenovation: 'Construção e renovação', painterDecorator: 'Pintor e decorador', handyman: 'Faz-tudo', airConditioning: 'Ar condicionado', poolServices: 'Serviços de piscina', pestControl: 'Controlo de pragas', locksmith: 'Serralheiro', removals: 'Mudanças', lawyer: 'Advogado', accountant: 'Contabilista', translatorInterpreter: 'Tradutor e intérprete', graphicDesigner: 'Designer gráfico', webDesignerDeveloper: 'Designer e programador web', photographer: 'Fotógrafo', marketing: 'Marketing', businessConsultant: 'Consultor empresarial', personalTrainer: 'Treinador pessoal', hairdresser: 'Cabeleireiro', beautyServices: 'Serviços de beleza', massageWellness: 'Massagem e bem-estar', nutrition: 'Nutrição', yogaFitness: 'Yoga e fitness', tutor: 'Explicador', languageTeacher: 'Professor de línguas', musicTeacher: 'Professor de música', childcareBabysitting: 'Cuidados infantis e babysitting', dogWalker: 'Passeador de cães', petSitter: 'Cuidador de animais', petGroomer: 'Tosquiador de animais', dogTrainer: 'Treinador de cães', otherLocalService: 'Outro serviço local' },
  ),
  pl: taxonomy(
    { homeProperty: 'Dom i nieruchomość', professionalServices: 'Usługi profesjonalne', healthBeautyLifestyle: 'Zdrowie, uroda i styl życia', learningFamily: 'Nauka i rodzina', pets: 'Zwierzęta', otherLocalServices: 'Inne usługi lokalne' },
    { plumber: 'Hydraulik', electrician: 'Elektryk', cleaner: 'Sprzątanie', gardener: 'Ogrodnik', builderRenovation: 'Budowa i remonty', painterDecorator: 'Malarz i dekorator', handyman: 'Złota rączka', airConditioning: 'Klimatyzacja', poolServices: 'Usługi basenowe', pestControl: 'Zwalczanie szkodników', locksmith: 'Ślusarz', removals: 'Przeprowadzki', lawyer: 'Prawnik', accountant: 'Księgowy', translatorInterpreter: 'Tłumacz pisemny i ustny', graphicDesigner: 'Grafik', webDesignerDeveloper: 'Projektant i programista stron internetowych', photographer: 'Fotograf', marketing: 'Marketing', businessConsultant: 'Doradca biznesowy', personalTrainer: 'Trener personalny', hairdresser: 'Fryzjer', beautyServices: 'Usługi kosmetyczne', massageWellness: 'Masaż i wellness', nutrition: 'Dietetyka', yogaFitness: 'Joga i fitness', tutor: 'Korepetytor', languageTeacher: 'Nauczyciel języków', musicTeacher: 'Nauczyciel muzyki', childcareBabysitting: 'Opieka nad dziećmi', dogWalker: 'Wyprowadzanie psów', petSitter: 'Opiekun zwierząt', petGroomer: 'Groomer zwierząt', dogTrainer: 'Trener psów', otherLocalService: 'Inna usługa lokalna' },
  ),
  ro: taxonomy(
    { homeProperty: 'Casă și proprietate', professionalServices: 'Servicii profesionale', healthBeautyLifestyle: 'Sănătate, frumusețe și stil de viață', learningFamily: 'Educație și familie', pets: 'Animale de companie', otherLocalServices: 'Alte servicii locale' },
    { plumber: 'Instalator', electrician: 'Electrician', cleaner: 'Servicii de curățenie', gardener: 'Grădinar', builderRenovation: 'Construcții și renovări', painterDecorator: 'Zugrav și decorator', handyman: 'Meșter pentru reparații', airConditioning: 'Aer condiționat', poolServices: 'Servicii pentru piscine', pestControl: 'Combaterea dăunătorilor', locksmith: 'Lăcătuș', removals: 'Mutări', lawyer: 'Avocat', accountant: 'Contabil', translatorInterpreter: 'Traducător și interpret', graphicDesigner: 'Designer grafic', webDesignerDeveloper: 'Designer și dezvoltator web', photographer: 'Fotograf', marketing: 'Marketing', businessConsultant: 'Consultant de afaceri', personalTrainer: 'Antrenor personal', hairdresser: 'Coafor', beautyServices: 'Servicii de înfrumusețare', massageWellness: 'Masaj și wellness', nutrition: 'Nutriție', yogaFitness: 'Yoga și fitness', tutor: 'Meditator', languageTeacher: 'Profesor de limbi străine', musicTeacher: 'Profesor de muzică', childcareBabysitting: 'Îngrijirea copiilor și babysitting', dogWalker: 'Plimbător de câini', petSitter: 'Îngrijitor de animale', petGroomer: 'Cosmetician pentru animale', dogTrainer: 'Dresor de câini', otherLocalService: 'Alt serviciu local' },
  ),
  cs: taxonomy(
    { homeProperty: 'Dům a nemovitost', professionalServices: 'Profesionální služby', healthBeautyLifestyle: 'Zdraví, krása a životní styl', learningFamily: 'Vzdělávání a rodina', pets: 'Domácí mazlíčci', otherLocalServices: 'Ostatní místní služby' },
    { plumber: 'Instalatér', electrician: 'Elektrikář', cleaner: 'Úklidové služby', gardener: 'Zahradník', builderRenovation: 'Stavba a renovace', painterDecorator: 'Malíř a dekoratér', handyman: 'Hodinový manžel', airConditioning: 'Klimatizace', poolServices: 'Bazénové služby', pestControl: 'Hubení škůdců', locksmith: 'Zámečník', removals: 'Stěhování', lawyer: 'Právník', accountant: 'Účetní', translatorInterpreter: 'Překladatel a tlumočník', graphicDesigner: 'Grafický designér', webDesignerDeveloper: 'Webdesignér a vývojář', photographer: 'Fotograf', marketing: 'Marketing', businessConsultant: 'Firemní poradce', personalTrainer: 'Osobní trenér', hairdresser: 'Kadeřník', beautyServices: 'Kosmetické služby', massageWellness: 'Masáže a wellness', nutrition: 'Výživové poradenství', yogaFitness: 'Jóga a fitness', tutor: 'Doučování', languageTeacher: 'Učitel jazyků', musicTeacher: 'Učitel hudby', childcareBabysitting: 'Péče o děti a hlídání', dogWalker: 'Venčení psů', petSitter: 'Hlídání zvířat', petGroomer: 'Psí a zvířecí salon', dogTrainer: 'Trenér psů', otherLocalService: 'Jiná místní služba' },
  ),
  sk: taxonomy(
    { homeProperty: 'Dom a nehnuteľnosť', professionalServices: 'Profesionálne služby', healthBeautyLifestyle: 'Zdravie, krása a životný štýl', learningFamily: 'Vzdelávanie a rodina', pets: 'Domáce zvieratá', otherLocalServices: 'Ostatné miestne služby' },
    { plumber: 'Inštalatér', electrician: 'Elektrikár', cleaner: 'Upratovacie služby', gardener: 'Záhradník', builderRenovation: 'Stavba a renovácia', painterDecorator: 'Maliar a dekoratér', handyman: 'Domáci majster', airConditioning: 'Klimatizácia', poolServices: 'Bazénové služby', pestControl: 'Hubenie škodcov', locksmith: 'Zámočník', removals: 'Sťahovanie', lawyer: 'Právnik', accountant: 'Účtovník', translatorInterpreter: 'Prekladateľ a tlmočník', graphicDesigner: 'Grafický dizajnér', webDesignerDeveloper: 'Webdizajnér a vývojár', photographer: 'Fotograf', marketing: 'Marketing', businessConsultant: 'Podnikateľský poradca', personalTrainer: 'Osobný tréner', hairdresser: 'Kaderník', beautyServices: 'Kozmetické služby', massageWellness: 'Masáže a wellness', nutrition: 'Výživové poradenstvo', yogaFitness: 'Joga a fitness', tutor: 'Doučovateľ', languageTeacher: 'Učiteľ jazykov', musicTeacher: 'Učiteľ hudby', childcareBabysitting: 'Starostlivosť o deti a opatrovanie', dogWalker: 'Venčenie psov', petSitter: 'Opatrovateľ zvierat', petGroomer: 'Salón pre zvieratá', dogTrainer: 'Tréner psov', otherLocalService: 'Iná miestna služba' },
  ),
  hu: taxonomy(
    { homeProperty: 'Otthon és ingatlan', professionalServices: 'Szakmai szolgáltatások', healthBeautyLifestyle: 'Egészség, szépség és életmód', learningFamily: 'Tanulás és család', pets: 'Háziállatok', otherLocalServices: 'Egyéb helyi szolgáltatások' },
    { plumber: 'Vízvezeték-szerelő', electrician: 'Villanyszerelő', cleaner: 'Takarító', gardener: 'Kertész', builderRenovation: 'Építés és felújítás', painterDecorator: 'Festő és dekoratőr', handyman: 'Ezermester', airConditioning: 'Légkondicionálás', poolServices: 'Medenceszolgáltatások', pestControl: 'Kártevőirtás', locksmith: 'Lakatos', removals: 'Költöztetés', lawyer: 'Ügyvéd', accountant: 'Könyvelő', translatorInterpreter: 'Fordító és tolmács', graphicDesigner: 'Grafikus', webDesignerDeveloper: 'Webdesigner és -fejlesztő', photographer: 'Fotós', marketing: 'Marketing', businessConsultant: 'Üzleti tanácsadó', personalTrainer: 'Személyi edző', hairdresser: 'Fodrász', beautyServices: 'Szépségápolási szolgáltatások', massageWellness: 'Masszázs és wellness', nutrition: 'Táplálkozási tanácsadás', yogaFitness: 'Jóga és fitnesz', tutor: 'Magántanár', languageTeacher: 'Nyelvtanár', musicTeacher: 'Zenetanár', childcareBabysitting: 'Gyermekfelügyelet és bébiszitter', dogWalker: 'Kutyasétáltató', petSitter: 'Állatfelügyelő', petGroomer: 'Kisállatkozmetikus', dogTrainer: 'Kutyakiképző', otherLocalService: 'Egyéb helyi szolgáltatás' },
  ),
  uk: taxonomy(
    { homeProperty: 'Дім і нерухомість', professionalServices: 'Професійні послуги', healthBeautyLifestyle: 'Здоров’я, краса та стиль життя', learningFamily: 'Навчання та сім’я', pets: 'Домашні тварини', otherLocalServices: 'Інші місцеві послуги' },
    { plumber: 'Сантехнік', electrician: 'Електрик', cleaner: 'Прибирання', gardener: 'Садівник', builderRenovation: 'Будівництво та ремонт', painterDecorator: 'Маляр і декоратор', handyman: 'Майстер на всі руки', airConditioning: 'Кондиціонування', poolServices: 'Обслуговування басейнів', pestControl: 'Боротьба зі шкідниками', locksmith: 'Слюсар', removals: 'Переїзди', lawyer: 'Юрист', accountant: 'Бухгалтер', translatorInterpreter: 'Перекладач усний і письмовий', graphicDesigner: 'Графічний дизайнер', webDesignerDeveloper: 'Вебдизайнер і розробник', photographer: 'Фотограф', marketing: 'Маркетинг', businessConsultant: 'Бізнес-консультант', personalTrainer: 'Персональний тренер', hairdresser: 'Перукар', beautyServices: 'Послуги краси', massageWellness: 'Масаж і велнес', nutrition: 'Харчування', yogaFitness: 'Йога та фітнес', tutor: 'Репетитор', languageTeacher: 'Викладач мов', musicTeacher: 'Викладач музики', childcareBabysitting: 'Догляд за дітьми та няня', dogWalker: 'Вигул собак', petSitter: 'Догляд за тваринами', petGroomer: 'Грумер тварин', dogTrainer: 'Кінолог', otherLocalService: 'Інша місцева послуга' },
  ),
  it: taxonomy(
    { homeProperty: 'Casa e proprietà', professionalServices: 'Servizi professionali', healthBeautyLifestyle: 'Salute, bellezza e stile di vita', learningFamily: 'Apprendimento e famiglia', pets: 'Animali domestici', otherLocalServices: 'Altri servizi locali' },
    { plumber: 'Idraulico', electrician: 'Elettricista', cleaner: 'Addetto alle pulizie', gardener: 'Giardiniere', builderRenovation: 'Edilizia e ristrutturazioni', painterDecorator: 'Imbianchino e decoratore', handyman: 'Tuttofare', airConditioning: 'Aria condizionata', poolServices: 'Servizi per piscine', pestControl: 'Disinfestazione', locksmith: 'Fabbro', removals: 'Traslochi', lawyer: 'Avvocato', accountant: 'Commercialista', translatorInterpreter: 'Traduttore e interprete', graphicDesigner: 'Graphic designer', webDesignerDeveloper: 'Web designer e sviluppatore', photographer: 'Fotografo', marketing: 'Marketing', businessConsultant: 'Consulente aziendale', personalTrainer: 'Personal trainer', hairdresser: 'Parrucchiere', beautyServices: 'Servizi di bellezza', massageWellness: 'Massaggi e benessere', nutrition: 'Nutrizione', yogaFitness: 'Yoga e fitness', tutor: 'Insegnante privato', languageTeacher: 'Insegnante di lingue', musicTeacher: 'Insegnante di musica', childcareBabysitting: 'Assistenza bambini e babysitting', dogWalker: 'Dog walker', petSitter: 'Pet sitter', petGroomer: 'Toelettatore per animali', dogTrainer: 'Addestratore cinofilo', otherLocalService: 'Altro servizio locale' },
  ),
  sv: taxonomy(
    { homeProperty: 'Hem och fastighet', professionalServices: 'Professionella tjänster', healthBeautyLifestyle: 'Hälsa, skönhet och livsstil', learningFamily: 'Lärande och familj', pets: 'Husdjur', otherLocalServices: 'Andra lokala tjänster' },
    { plumber: 'Rörmokare', electrician: 'Elektriker', cleaner: 'Städare', gardener: 'Trädgårdsmästare', builderRenovation: 'Bygg och renovering', painterDecorator: 'Målare och dekoratör', handyman: 'Allt-i-allo', airConditioning: 'Luftkonditionering', poolServices: 'Poolservice', pestControl: 'Skadedjursbekämpning', locksmith: 'Låssmed', removals: 'Flyttjänster', lawyer: 'Jurist', accountant: 'Redovisningskonsult', translatorInterpreter: 'Översättare och tolk', graphicDesigner: 'Grafisk designer', webDesignerDeveloper: 'Webbdesigner och utvecklare', photographer: 'Fotograf', marketing: 'Marknadsföring', businessConsultant: 'Företagskonsult', personalTrainer: 'Personlig tränare', hairdresser: 'Frisör', beautyServices: 'Skönhetstjänster', massageWellness: 'Massage och wellness', nutrition: 'Kostrådgivning', yogaFitness: 'Yoga och fitness', tutor: 'Privatlärare', languageTeacher: 'Språklärare', musicTeacher: 'Musiklärare', childcareBabysitting: 'Barnomsorg och barnpassning', dogWalker: 'Hundrastare', petSitter: 'Djurvakt', petGroomer: 'Hund- och djurfrisör', dogTrainer: 'Hundtränare', otherLocalService: 'Annan lokal tjänst' },
  ),
  da: taxonomy(
    { homeProperty: 'Hjem og ejendom', professionalServices: 'Professionelle tjenester', healthBeautyLifestyle: 'Sundhed, skønhed og livsstil', learningFamily: 'Læring og familie', pets: 'Kæledyr', otherLocalServices: 'Andre lokale tjenester' },
    { plumber: 'VVS-installatør', electrician: 'Elektriker', cleaner: 'Rengøringshjælp', gardener: 'Gartner', builderRenovation: 'Byggeri og renovering', painterDecorator: 'Maler og dekoratør', handyman: 'Handyman', airConditioning: 'Aircondition', poolServices: 'Poolservice', pestControl: 'Skadedyrsbekæmpelse', locksmith: 'Låsesmed', removals: 'Flytning', lawyer: 'Advokat', accountant: 'Bogholder', translatorInterpreter: 'Oversætter og tolk', graphicDesigner: 'Grafisk designer', webDesignerDeveloper: 'Webdesigner og -udvikler', photographer: 'Fotograf', marketing: 'Marketing', businessConsultant: 'Virksomhedsrådgiver', personalTrainer: 'Personlig træner', hairdresser: 'Frisør', beautyServices: 'Skønhedsbehandlinger', massageWellness: 'Massage og wellness', nutrition: 'Ernæringsrådgivning', yogaFitness: 'Yoga og fitness', tutor: 'Privatlærer', languageTeacher: 'Sproglærer', musicTeacher: 'Musiklærer', childcareBabysitting: 'Børnepasning og babysitting', dogWalker: 'Hundelufter', petSitter: 'Dyrepasser', petGroomer: 'Dyrefrisør', dogTrainer: 'Hundetræner', otherLocalService: 'Anden lokal tjeneste' },
  ),
  fi: taxonomy(
    { homeProperty: 'Koti ja kiinteistö', professionalServices: 'Asiantuntijapalvelut', healthBeautyLifestyle: 'Terveys, kauneus ja elämäntapa', learningFamily: 'Oppiminen ja perhe', pets: 'Lemmikit', otherLocalServices: 'Muut paikalliset palvelut' },
    { plumber: 'Putkiasentaja', electrician: 'Sähköasentaja', cleaner: 'Siivooja', gardener: 'Puutarhuri', builderRenovation: 'Rakentaminen ja remontointi', painterDecorator: 'Maalari ja sisustaja', handyman: 'Yleismies', airConditioning: 'Ilmastointi', poolServices: 'Allaspalvelut', pestControl: 'Tuholaistorjunta', locksmith: 'Lukkoseppä', removals: 'Muuttopalvelut', lawyer: 'Lakimies', accountant: 'Kirjanpitäjä', translatorInterpreter: 'Kääntäjä ja tulkki', graphicDesigner: 'Graafinen suunnittelija', webDesignerDeveloper: 'Verkkosuunnittelija ja -kehittäjä', photographer: 'Valokuvaaja', marketing: 'Markkinointi', businessConsultant: 'Yrityskonsultti', personalTrainer: 'Personal trainer', hairdresser: 'Kampaaja', beautyServices: 'Kauneuspalvelut', massageWellness: 'Hieronta ja hyvinvointi', nutrition: 'Ravitsemusneuvonta', yogaFitness: 'Jooga ja kuntoilu', tutor: 'Yksityisopettaja', languageTeacher: 'Kieltenopettaja', musicTeacher: 'Musiikinopettaja', childcareBabysitting: 'Lastenhoito ja lapsenvahti', dogWalker: 'Koiranulkoiluttaja', petSitter: 'Lemmikinhoitaja', petGroomer: 'Lemmikkien trimmaaja', dogTrainer: 'Koirankouluttaja', otherLocalService: 'Muu paikallinen palvelu' },
  ),
  no: taxonomy(
    { homeProperty: 'Hjem og eiendom', professionalServices: 'Profesjonelle tjenester', healthBeautyLifestyle: 'Helse, skjønnhet og livsstil', learningFamily: 'Læring og familie', pets: 'Kjæledyr', otherLocalServices: 'Andre lokale tjenester' },
    { plumber: 'Rørlegger', electrician: 'Elektriker', cleaner: 'Renholder', gardener: 'Gartner', builderRenovation: 'Bygg og oppussing', painterDecorator: 'Maler og dekoratør', handyman: 'Vaktmester og altmuligmann', airConditioning: 'Klimaanlegg', poolServices: 'Bassengtjenester', pestControl: 'Skadedyrbekjempelse', locksmith: 'Låsesmed', removals: 'Flytting', lawyer: 'Advokat', accountant: 'Regnskapsfører', translatorInterpreter: 'Oversetter og tolk', graphicDesigner: 'Grafisk designer', webDesignerDeveloper: 'Webdesigner og -utvikler', photographer: 'Fotograf', marketing: 'Markedsføring', businessConsultant: 'Bedriftsrådgiver', personalTrainer: 'Personlig trener', hairdresser: 'Frisør', beautyServices: 'Skjønnhetsbehandlinger', massageWellness: 'Massasje og velvære', nutrition: 'Ernæringsveiledning', yogaFitness: 'Yoga og trening', tutor: 'Privatlærer', languageTeacher: 'Språklærer', musicTeacher: 'Musikklærer', childcareBabysitting: 'Barnepass og babysitting', dogWalker: 'Hundelufter', petSitter: 'Dyrepasser', petGroomer: 'Dyrefrisør', dogTrainer: 'Hundetrener', otherLocalService: 'Annen lokal tjeneste' },
  ),
})
