function pack(d) {
  return { accountDeletion: {
    request: {
      eyebrow: d[0], title: d[1], description: d[2], open: d[3], dialogTitle: d[4],
      warning: d[5], password: d[6], confirm: d[7], confirmationRequired: d[8],
      submit: d[9], submitting: d[10], ownedBusinessBlock: d[11],
    },
    status: {
      title: d[12], description: d[13], noDeletionYet: d[14], cancel: d[15], cancelling: d[16],
    },
    errors: {
      recentAuth: d[17], ownershipConflict: d[18], request: d[19], cancel: d[20],
      load: d[21], logout: d[22],
    },
  } }
}

export const accountDeletionTranslations = Object.fromEntries(Object.entries({
  es:['Eliminación de cuenta','Eliminar tu cuenta','Solicita la eliminación de la cuenta con asistencia administrativa.','Solicitar eliminación','Solicitar eliminación de cuenta','El acceso normal quedará restringido mientras la solicitud esté pendiente. Esta solicitud no elimina datos.','Contraseña actual','Entiendo que el acceso quedará restringido durante la revisión.','Introduce tu contraseña y confirma para continuar.','Enviar solicitud','Enviando…','Resuelve primero tus {{count}} negocio(s) en propiedad.','Eliminación solicitada','Hemos recibido la solicitud y el acceso normal está restringido durante la revisión.','Puede que todavía no se haya eliminado ningún dato.','Cancelar solicitud','Cancelando…','Vuelve a identificarte con tu contraseña.','Los datos de propiedad del negocio requieren revisión administrativa.','No se pudo enviar la solicitud. No se eliminó ningún dato.','No se pudo cancelar la solicitud.','No se pudo cargar el estado.','No se pudo cerrar la sesión.'],
  fr:['Suppression du compte','Supprimer votre compte','Demandez la suppression assistée par un administrateur.','Demander la suppression','Demander la suppression du compte','L’accès normal sera limité pendant l’examen. Cette demande ne supprime aucune donnée.','Mot de passe actuel','Je comprends que mon accès sera limité pendant l’examen.','Saisissez votre mot de passe et confirmez.','Envoyer la demande','Envoi…','Réglez d’abord vos {{count}} entreprise(s) détenue(s).','Suppression demandée','Votre demande a été reçue et l’accès normal est limité pendant son traitement.','Aucune donnée n’a nécessairement encore été supprimée.','Annuler la demande','Annulation…','Reconnectez-vous avec votre mot de passe.','Les données de propriété nécessitent un examen administratif.','Impossible d’envoyer la demande. Aucune donnée n’a été supprimée.','Impossible d’annuler la demande.','Impossible de charger l’état.','Impossible de vous déconnecter.'],
  de:['Kontolöschung','Konto löschen','Beantragen Sie eine administrativ unterstützte Kontolöschung.','Löschung beantragen','Kontolöschung beantragen','Der normale Kontozugriff wird während der Prüfung eingeschränkt. Diese Anfrage löscht keine Daten.','Aktuelles Passwort','Ich verstehe, dass mein Zugriff während der Prüfung eingeschränkt wird.','Passwort eingeben und bestätigen.','Antrag senden','Wird gesendet…','Klären Sie zuerst Ihre {{count}} Unternehmen.','Kontolöschung beantragt','Ihr Antrag ist eingegangen; der normale Zugriff ist während der Bearbeitung eingeschränkt.','Möglicherweise wurden noch keine Daten gelöscht.','Antrag stornieren','Wird storniert…','Melden Sie sich erneut mit Ihrem Passwort an.','Die Eigentumsdaten müssen administrativ geprüft werden.','Antrag fehlgeschlagen. Es wurden keine Daten gelöscht.','Stornierung fehlgeschlagen.','Status konnte nicht geladen werden.','Abmeldung fehlgeschlagen.'],
  nl:['Account verwijderen','Je account verwijderen','Vraag accountverwijdering met beheerderbegeleiding aan.','Verwijdering aanvragen','Accountverwijdering aanvragen','Normale toegang wordt beperkt tijdens de beoordeling. Dit verzoek verwijdert geen gegevens.','Huidig wachtwoord','Ik begrijp dat mijn toegang tijdens de beoordeling wordt beperkt.','Voer je wachtwoord in en bevestig.','Verzoek indienen','Indienen…','Los eerst je {{count}} bedrijf/bedrijven op.','Verwijdering aangevraagd','Je verzoek is ontvangen en normale toegang is tijdens verwerking beperkt.','Er zijn mogelijk nog geen gegevens verwijderd.','Verzoek annuleren','Annuleren…','Meld je opnieuw aan met je wachtwoord.','De eigendomsgegevens vereisen controle door een beheerder.','Het verzoek kon niet worden ingediend. Er zijn geen gegevens verwijderd.','Het verzoek kon niet worden geannuleerd.','De status kon niet worden geladen.','Afmelden is mislukt.'],
  pt:['Eliminação da conta','Eliminar a sua conta','Solicite a eliminação assistida por um administrador.','Pedir eliminação','Pedir eliminação da conta','O acesso normal ficará limitado durante a análise. Este pedido não elimina dados.','Palavra-passe atual','Compreendo que o acesso ficará limitado durante a análise.','Introduza a palavra-passe e confirme.','Enviar pedido','A enviar…','Resolva primeiro as suas {{count}} empresas.','Eliminação solicitada','O pedido foi recebido e o acesso normal está limitado durante o processamento.','Os dados podem ainda não ter sido eliminados.','Cancelar pedido','A cancelar…','Inicie sessão novamente com a palavra-passe.','Os dados de propriedade requerem análise administrativa.','Não foi possível enviar o pedido. Nenhum dado foi eliminado.','Não foi possível cancelar o pedido.','Não foi possível carregar o estado.','Não foi possível terminar sessão.'],
  it:['Eliminazione account','Elimina il tuo account','Richiedi l’eliminazione assistita da un amministratore.','Richiedi eliminazione','Richiedi eliminazione account','L’accesso normale sarà limitato durante la revisione. Questa richiesta non elimina dati.','Password attuale','Comprendo che l’accesso sarà limitato durante la revisione.','Inserisci la password e conferma.','Invia richiesta','Invio…','Risolvi prima le tue {{count}} attività.','Eliminazione richiesta','La richiesta è stata ricevuta e l’accesso normale è limitato durante l’elaborazione.','I dati potrebbero non essere ancora stati eliminati.','Annulla richiesta','Annullamento…','Accedi di nuovo con la password.','I dati di proprietà richiedono revisione amministrativa.','Impossibile inviare la richiesta. Nessun dato è stato eliminato.','Impossibile annullare la richiesta.','Impossibile caricare lo stato.','Impossibile disconnettersi.'],
  pl:['Usunięcie konta','Usuń konto','Poproś o usunięcie konta z pomocą administratora.','Poproś o usunięcie','Poproś o usunięcie konta','Normalny dostęp zostanie ograniczony podczas weryfikacji. Ten wniosek nie usuwa danych.','Aktualne hasło','Rozumiem, że dostęp zostanie ograniczony podczas weryfikacji.','Wpisz hasło i potwierdź.','Wyślij wniosek','Wysyłanie…','Najpierw rozwiąż sprawę {{count}} posiadanych firm.','Zażądano usunięcia','Wniosek otrzymano; normalny dostęp jest ograniczony podczas obsługi.','Dane mogły jeszcze nie zostać usunięte.','Anuluj wniosek','Anulowanie…','Zaloguj się ponownie hasłem.','Dane własności wymagają przeglądu administratora.','Nie udało się wysłać wniosku. Nie usunięto danych.','Nie udało się anulować wniosku.','Nie udało się wczytać stanu.','Nie udało się wylogować.'],
  ro:['Ștergerea contului','Șterge contul','Solicită ștergerea asistată de administrator.','Solicită ștergerea','Solicită ștergerea contului','Accesul normal va fi restricționat în timpul verificării. Cererea nu șterge date.','Parola actuală','Înțeleg că accesul va fi restricționat în timpul verificării.','Introdu parola și confirmă.','Trimite cererea','Se trimite…','Rezolvă mai întâi cele {{count}} afaceri deținute.','Ștergere solicitată','Cererea a fost primită, iar accesul normal este restricționat în timpul procesării.','Este posibil ca datele să nu fi fost încă șterse.','Anulează cererea','Se anulează…','Autentifică-te din nou cu parola.','Datele de proprietate necesită verificare administrativă.','Cererea nu a putut fi trimisă. Nu s-au șters date.','Cererea nu a putut fi anulată.','Starea nu a putut fi încărcată.','Deconectarea a eșuat.'],
  cs:['Smazání účtu','Smazat účet','Požádejte o smazání účtu s pomocí správce.','Požádat o smazání','Požádat o smazání účtu','Běžný přístup bude během kontroly omezen. Tato žádost data nemaže.','Aktuální heslo','Rozumím, že můj přístup bude během kontroly omezen.','Zadejte heslo a potvrďte.','Odeslat žádost','Odesílání…','Nejprve vyřešte svých {{count}} podniků.','Smazání vyžádáno','Žádost byla přijata a běžný přístup je během zpracování omezen.','Žádná data zatím nemusela být smazána.','Zrušit žádost','Rušení…','Přihlaste se znovu pomocí hesla.','Údaje o vlastnictví vyžadují kontrolu správce.','Žádost se nepodařilo odeslat. Žádná data nebyla smazána.','Žádost se nepodařilo zrušit.','Stav se nepodařilo načíst.','Odhlášení se nezdařilo.'],
  sk:['Odstránenie účtu','Odstrániť účet','Požiadajte o odstránenie účtu s pomocou správcu.','Požiadať o odstránenie','Požiadať o odstránenie účtu','Bežný prístup bude počas kontroly obmedzený. Táto žiadosť údaje neodstráni.','Aktuálne heslo','Rozumiem, že prístup bude počas kontroly obmedzený.','Zadajte heslo a potvrďte.','Odoslať žiadosť','Odosielanie…','Najprv vyriešte svojich {{count}} podnikov.','Odstránenie vyžiadané','Žiadosť bola prijatá a bežný prístup je počas spracovania obmedzený.','Údaje ešte nemuseli byť odstránené.','Zrušiť žiadosť','Rušenie…','Prihláste sa znova pomocou hesla.','Údaje o vlastníctve vyžadujú kontrolu správcu.','Žiadosť sa nepodarilo odoslať. Žiadne údaje neboli odstránené.','Žiadosť sa nepodarilo zrušiť.','Stav sa nepodarilo načítať.','Odhlásenie zlyhalo.'],
  hu:['Fióktörlés','Fiók törlése','Kérje a rendszergazda által segített fióktörlést.','Törlés kérése','Fióktörlés kérése','A normál hozzáférés a felülvizsgálat alatt korlátozott lesz. A kérés nem töröl adatot.','Jelenlegi jelszó','Megértem, hogy a hozzáférésem korlátozott lesz.','Adja meg jelszavát és erősítse meg.','Kérés elküldése','Küldés…','Előbb rendezze a tulajdonában lévő {{count}} vállalkozást.','Törlés kérve','A kérést megkaptuk; a normál hozzáférés a feldolgozás alatt korlátozott.','Lehetséges, hogy még nem töröltünk adatot.','Kérés visszavonása','Visszavonás…','Jelentkezzen be újra a jelszavával.','A tulajdonosi adatok rendszergazdai ellenőrzést igényelnek.','A kérés nem küldhető el. Nem töröltünk adatot.','A kérés nem vonható vissza.','Az állapot nem tölthető be.','A kijelentkezés sikertelen.'],
  uk:['Видалення облікового запису','Видалити обліковий запис','Запросіть видалення за участю адміністратора.','Запросити видалення','Запросити видалення облікового запису','Звичайний доступ буде обмежено на час перевірки. Цей запит не видаляє дані.','Поточний пароль','Я розумію, що доступ буде обмежено на час перевірки.','Введіть пароль і підтвердьте.','Надіслати запит','Надсилання…','Спочатку вирішіть питання щодо {{count}} ваших компаній.','Видалення запитано','Запит отримано, звичайний доступ обмежено на час обробки.','Дані ще могли не бути видалені.','Скасувати запит','Скасування…','Увійдіть знову за допомогою пароля.','Дані власності потребують перевірки адміністратора.','Не вдалося надіслати запит. Дані не видалено.','Не вдалося скасувати запит.','Не вдалося завантажити стан.','Не вдалося вийти.'],
  sv:['Kontoradering','Radera ditt konto','Begär administratörsassisterad kontoradering.','Begär radering','Begär kontoradering','Normal åtkomst begränsas under granskningen. Begäran raderar inga data.','Nuvarande lösenord','Jag förstår att åtkomsten begränsas under granskningen.','Ange lösenord och bekräfta.','Skicka begäran','Skickar…','Lös först dina {{count}} ägda företag.','Radering begärd','Begäran har tagits emot och normal åtkomst är begränsad under behandlingen.','Inga data behöver ha raderats ännu.','Avbryt begäran','Avbryter…','Logga in igen med lösenordet.','Ägaruppgifterna kräver administrativ granskning.','Begäran kunde inte skickas. Inga data raderades.','Begäran kunde inte avbrytas.','Status kunde inte läsas in.','Utloggningen misslyckades.'],
  da:['Sletning af konto','Slet din konto','Anmod om administrativt assisteret kontosletning.','Anmod om sletning','Anmod om kontosletning','Normal adgang begrænses under gennemgangen. Anmodningen sletter ingen data.','Nuværende adgangskode','Jeg forstår, at adgangen begrænses under gennemgangen.','Indtast adgangskoden og bekræft.','Send anmodning','Sender…','Afklar først dine {{count}} ejede virksomheder.','Sletning anmodet','Anmodningen er modtaget, og normal adgang er begrænset under behandlingen.','Ingen data er nødvendigvis slettet endnu.','Annuller anmodning','Annullerer…','Log ind igen med din adgangskode.','Ejeroplysningerne kræver administrativ gennemgang.','Anmodningen kunne ikke sendes. Ingen data blev slettet.','Anmodningen kunne ikke annulleres.','Status kunne ikke indlæses.','Log ud mislykkedes.'],
  fi:['Tilin poistaminen','Poista tilisi','Pyydä ylläpitäjän avustamaa tilin poistamista.','Pyydä poistamista','Pyydä tilin poistamista','Normaalia käyttöä rajoitetaan tarkistuksen aikana. Pyyntö ei poista tietoja.','Nykyinen salasana','Ymmärrän, että käyttöä rajoitetaan tarkistuksen aikana.','Anna salasana ja vahvista.','Lähetä pyyntö','Lähetetään…','Ratkaise ensin omistamasi {{count}} yritystä.','Poistamista pyydetty','Pyyntö on vastaanotettu ja normaalia käyttöä on rajoitettu käsittelyn aikana.','Tietoja ei välttämättä ole vielä poistettu.','Peruuta pyyntö','Peruutetaan…','Kirjaudu uudelleen salasanallasi.','Omistustiedot vaativat ylläpitäjän tarkistuksen.','Pyyntöä ei voitu lähettää. Tietoja ei poistettu.','Pyyntöä ei voitu peruuttaa.','Tilaa ei voitu ladata.','Uloskirjautuminen epäonnistui.'],
  no:['Sletting av konto','Slett kontoen din','Be om administratorassistert kontosletting.','Be om sletting','Be om kontosletting','Normal tilgang begrenses under gjennomgangen. Forespørselen sletter ingen data.','Nåværende passord','Jeg forstår at tilgangen begrenses under gjennomgangen.','Skriv inn passordet og bekreft.','Send forespørsel','Sender…','Avklar først dine {{count}} eide virksomheter.','Sletting forespurt','Forespørselen er mottatt, og normal tilgang er begrenset under behandlingen.','Ingen data er nødvendigvis slettet ennå.','Avbryt forespørsel','Avbryter…','Logg inn igjen med passordet.','Eieropplysningene krever administrativ gjennomgang.','Forespørselen kunne ikke sendes. Ingen data ble slettet.','Forespørselen kunne ikke avbrytes.','Status kunne ikke lastes.','Utlogging mislyktes.'],
}).map(([code, values]) => [code, pack(values)]))
