export const deletionDisclosureTranslations = {
  "es": {
    "privacy": [
      "Cuando se elimina una cuenta, HolaLocal elimina el perfil activo y los archivos multimedia personales asociados al perfil. Pueden conservarse registros limitados para mantener los registros adecuados del servicio y la integridad y seguridad de la plataforma. Estos pueden incluir las versiones aceptadas de los Términos y la Política de Privacidad y sus fechas de aceptación, informes existentes de moderación, seguridad o abuso, y conversaciones y mensajes históricos. Los informes pueden incluir información personal introducida por usuarios en campos de texto libre.",
      "Los identificadores históricos de usuario de Firebase pueden permanecer en estos registros como identificadores estructurales seudónimos. No son anónimos. HolaLocal no los utiliza para restaurar ni mostrar el antiguo perfil, nombre, avatar u otra información de perfil eliminada. Cuando la información conservada se anonimiza posteriormente, deja de identificar a la persona; un identificador seudónimo conservado no debe tratarse como anónimo.",
      "Nuestra política es conservar las conversaciones mientras al menos un participante mantenga una cuenta y el historial siga siendo necesario. Esto no significa haber iniciado sesión recientemente. Evaluamos por separado las solicitudes de supresión, incluidos los datos personales dentro de los mensajes.",
      "Para reportes que no sean de reseñas, nuestra política es eliminar los datos personales 90 días después de su resolución, salvo una necesidad concreta, documentada y vigente. Cada excepción tiene un motivo, un responsable, una próxima fecha de revisión y una condición de finalización. Una revisión vencida no termina ni renueva automáticamente la conservación. La política de reportes de reseñas no cambia.",
      "Se conservan los registros de aceptación y reconocimiento de las cuentas existentes. Tras eliminar una cuenta, nuestra política es conservar solo pruebas mínimas justificadas por una necesidad concreta y documentada, con fecha de revisión, y eliminarlas cuando termine esa necesidad.",
      "Los nuevos controles de conservación están preparados, pero la limpieza destructiva no está habilitada. Estos criterios no significan que funcione una limpieza automática. La limpieza programada de reportes de reseñas es independiente y también sigue deshabilitada."
    ],
    "request": "Al eliminar tu cuenta se eliminan el perfil de la cuenta y sus archivos multimedia. Pueden conservarse registros limitados, incluidos registros de consentimiento, informes de moderación o seguridad y conversaciones históricas, según se explica en la"
  },
  "fr": {
    "privacy": [
      "Lorsqu’un compte est supprimé, HolaLocal supprime le profil actif et les médias personnels associés au profil. Des dossiers limités peuvent subsister afin de préserver les dossiers de service appropriés ainsi que l’intégrité et la sécurité de la plateforme. Ils peuvent comprendre les versions des Conditions et de la Politique de confidentialité acceptées et leurs dates d’acceptation, les signalements existants de modération, de sécurité ou d’abus, ainsi que l’historique des conversations et messages. Les signalements peuvent contenir des informations personnelles saisies par les utilisateurs dans des champs de texte libre.",
      "Les anciens identifiants utilisateur Firebase peuvent rester dans ces dossiers comme identifiants structurels pseudonymes. Ils ne sont pas anonymes. HolaLocal ne les utilise pas pour restaurer ou afficher l’ancien profil, le nom, l’avatar ou d’autres informations de profil supprimées. Lorsque des informations conservées sont ensuite anonymisées, elles n’identifient plus l’utilisateur ; un identifiant pseudonyme conservé ne doit pas être considéré comme anonyme.",
      "Notre politique est de conserver les conversations tant qu’au moins un participant conserve un compte et que l’historique reste nécessaire. Cela ne signifie pas une connexion récente. Nous examinons séparément les demandes d’effacement, y compris les données personnelles dans le texte des messages.",
      "Pour les signalements autres que ceux concernant des avis, notre politique est de supprimer les données personnelles 90 jours après résolution, sauf besoin précis, documenté et toujours valable. Chaque exception comporte un motif, un responsable, une prochaine date de réexamen et une condition de fin. Un réexamen en retard ne met pas fin à la conservation et ne la renouvelle pas automatiquement. La politique des signalements d’avis reste inchangée.",
      "Les preuves d’acceptation et de prise de connaissance des comptes existants sont préservées. Après suppression du compte, notre politique est de ne conserver que les preuves minimales justifiées par un besoin précis et documenté, avec une date de réexamen, puis de les supprimer lorsque ce besoin prend fin.",
      "Les nouveaux contrôles de conservation sont préparés, mais la suppression destructive n’est pas activée. Ces critères ne signifient pas qu’une suppression automatique fonctionne. Le nettoyage programmé des signalements d’avis est distinct et reste également désactivé."
    ],
    "request": "La suppression de votre compte retire votre profil et ses médias. Des dossiers limités peuvent subsister, notamment les preuves de consentement, les signalements de modération ou de sécurité et l’historique des conversations, comme expliqué dans la"
  },
  "de": {
    "privacy": [
      "Wenn ein Konto gelöscht wird, entfernt HolaLocal das aktive Kontoprofil und die zugehörigen persönlichen Profilmedien. Begrenzte Datensätze können bestehen bleiben, um angemessene Dienstaufzeichnungen sowie die Integrität und Sicherheit der Plattform zu erhalten. Dazu können die akzeptierten Versionen der Nutzungsbedingungen und Datenschutzrichtlinie mit den jeweiligen Annahmezeitpunkten, vorhandene Moderations-, Sicherheits- oder Missbrauchsmeldungen sowie historische Unterhaltungen und Nachrichten gehören. Meldungen können personenbezogene Angaben enthalten, die Nutzer in Freitextfelder eingegeben haben.",
      "Frühere Firebase-Benutzerkennungen können in diesen Datensätzen als pseudonyme strukturelle Kennungen verbleiben. Sie sind nicht anonym. HolaLocal verwendet sie nicht, um das frühere Profil, den Namen, Avatar oder andere entfernte Profilinformationen wiederherzustellen oder anzuzeigen. Werden gespeicherte Informationen später anonymisiert, identifizieren sie den Nutzer nicht mehr; eine gespeicherte pseudonyme Kennung darf nicht als anonym behandelt werden.",
      "Unsere Richtlinie ist, Gesprächsverläufe aufzubewahren, solange mindestens ein Teilnehmer ein Konto behält und der Verlauf benötigt wird. Gemeint ist keine kürzlich erfolgte Anmeldung. Löschanträge prüfen wir gesondert, auch hinsichtlich personenbezogener Angaben im Nachrichtentext.",
      "Bei Meldungen, die keine Kundenbewertungen betreffen, sieht unsere Richtlinie die Entfernung personenbezogener Daten 90 Tage nach Abschluss vor, außer bei einem konkreten dokumentierten fortbestehenden Bedarf. Jede Ausnahme hat einen Grund, eine verantwortliche prüfende Person, einen nächsten Prüftermin und eine Endbedingung. Eine überfällige Prüfung beendet oder verlängert die Aufbewahrung nicht automatisch. Die Richtlinie für Bewertungsmeldungen bleibt unverändert.",
      "Bestätigungsnachweise bestehender Konten bleiben erhalten. Nach Kontolöschung sollen nur minimale Nachweise für einen konkreten dokumentierten Bedarf mit Prüftermin aufbewahrt und nach Wegfall des Bedarfs entfernt werden.",
      "Die neuen Aufbewahrungsfunktionen sind vorbereitet; destruktive Bereinigung ist nicht aktiviert. Diese Kriterien bedeuten nicht, dass automatische Bereinigung läuft. Die geplante Bereinigung von Bewertungsmeldungen ist getrennt und ebenfalls deaktiviert."
    ],
    "request": "Beim Löschen Ihres Kontos werden Ihr Kontoprofil und Ihre Profilmedien entfernt. Begrenzte Datensätze können bestehen bleiben, darunter Einwilligungsnachweise, Moderations- oder Sicherheitsmeldungen und historische Unterhaltungen, wie erläutert in der"
  },
  "nl": {
    "privacy": [
      "Wanneer een account wordt verwijderd, verwijdert HolaLocal het actieve accountprofiel en de bijbehorende persoonlijke profielmedia. Beperkte gegevens kunnen bewaard blijven om passende dienstregistraties en de integriteit en veiligheid van het platform te behouden. Dit kan gaan om de geaccepteerde versies van de Voorwaarden en het Privacybeleid met de bijbehorende acceptatietijdstippen, bestaande moderatie-, veiligheids- of misbruikmeldingen en historische gesprekken en berichten. Meldingen kunnen persoonlijke informatie bevatten die gebruikers in vrije tekstvelden hebben ingevoerd.",
      "Historische Firebase-gebruikers-ID’s kunnen in deze gegevens blijven staan als pseudonieme structurele identificatoren. Ze zijn niet anoniem. HolaLocal gebruikt ze niet om het voormalige profiel, de naam, avatar of andere verwijderde profielinformatie te herstellen of te tonen. Wanneer bewaarde informatie later wordt geanonimiseerd, identificeert die de gebruiker niet meer; een bewaarde pseudonieme identificator mag niet als anoniem worden behandeld.",
      "Ons beleid is gespreksgeschiedenis te bewaren zolang ten minste één deelnemer een account behoudt en de geschiedenis nodig blijft. Dit betekent niet dat iemand recent heeft ingelogd. Wij beoordelen verwijderingsverzoeken afzonderlijk, inclusief persoonsgegevens in berichttekst.",
      "Voor meldingen die niet over beoordelingen gaan, is ons beleid persoonsgegevens 90 dagen na afhandeling te verwijderen, behalve bij een specifieke gedocumenteerde voortdurende noodzaak. Elke uitzondering heeft een reden, verantwoordelijke beoordelaar, volgende beoordelingsdatum en eindvoorwaarde. Een te late beoordeling beëindigt of verlengt bewaring niet automatisch. Het beleid voor meldingen over beoordelingen blijft ongewijzigd.",
      "Bestaande aanvaardings- en bevestigingsgegevens van accounts blijven behouden. Na accountverwijdering bewaren wij volgens ons beleid alleen minimaal bewijs voor een specifieke gedocumenteerde noodzaak, met beoordelingsdatum, en verwijderen dit wanneer de noodzaak eindigt.",
      "De nieuwe bewaarbeheerfuncties zijn voorbereid, maar destructieve opschoning is niet ingeschakeld. Deze criteria betekenen niet dat automatische opschoning werkt. Geplande opschoning van beoordelingsmeldingen is afzonderlijk en blijft ook uitgeschakeld."
    ],
    "request": "Als je je account verwijdert, worden je accountprofiel en profielmedia verwijderd. Beperkte gegevens kunnen bewaard blijven, waaronder toestemmingsregistraties, moderatie- of veiligheidsmeldingen en historische gesprekken, zoals uitgelegd in het"
  },
  "pt": {
    "privacy": [
      "Quando uma conta é eliminada, a HolaLocal remove o perfil ativo e os ficheiros pessoais associados ao perfil. Podem permanecer registos limitados para preservar registos adequados do serviço e a integridade e segurança da plataforma. Estes podem incluir as versões aceites dos Termos e da Política de Privacidade e as respetivas datas de aceitação, denúncias existentes de moderação, segurança ou abuso, e conversas e mensagens históricas. As denúncias podem incluir informações pessoais introduzidas pelos utilizadores em campos de texto livre.",
      "Os identificadores históricos de utilizador do Firebase podem permanecer nesses registos como identificadores estruturais pseudónimos. Não são anónimos. A HolaLocal não os utiliza para restaurar ou apresentar o antigo perfil, nome, avatar ou outras informações de perfil removidas. Quando informações conservadas são posteriormente anonimizadas, deixam de identificar o utilizador; um identificador pseudónimo conservado não deve ser tratado como anónimo.",
      "A nossa política é conservar conversas enquanto pelo menos um participante mantiver uma conta e o histórico continuar a ser necessário. Isto não significa um início de sessão recente. Avaliamos separadamente pedidos de apagamento, incluindo dados pessoais no texto das mensagens.",
      "Para denúncias que não sejam de avaliações, a nossa política é remover dados pessoais 90 dias após a resolução, salvo uma necessidade específica, documentada e ainda existente. Cada exceção tem motivo, responsável, próxima data de revisão e condição de fim. Uma revisão atrasada não termina nem renova automaticamente a conservação. A política de denúncias de avaliações mantém-se.",
      "Os registos de aceitação e tomada de conhecimento das contas existentes são preservados. Após apagar uma conta, a nossa política é conservar apenas provas mínimas justificadas por uma necessidade específica documentada, com data de revisão, e removê-las quando essa necessidade terminar.",
      "Os novos controlos estão preparados, mas a limpeza destrutiva não está ativada. Estes critérios não significam que exista limpeza automática em funcionamento. A limpeza agendada de denúncias de avaliações é separada e continua igualmente desativada."
    ],
    "request": "A eliminação da conta remove o perfil e os respetivos ficheiros multimédia. Podem permanecer registos limitados, incluindo registos de consentimento, denúncias de moderação ou segurança e conversas históricas, conforme explicado na"
  },
  "it": {
    "privacy": [
      "Quando un account viene eliminato, HolaLocal rimuove il profilo attivo e i contenuti multimediali personali associati al profilo. Possono rimanere registrazioni limitate per preservare adeguati registri del servizio e l’integrità e la sicurezza della piattaforma. Possono includere le versioni accettate dei Termini e dell’Informativa sulla privacy con le relative date di accettazione, segnalazioni esistenti di moderazione, sicurezza o abuso, e conversazioni e messaggi storici. Le segnalazioni possono contenere informazioni personali inserite dagli utenti in campi di testo libero.",
      "Gli identificativi utente Firebase storici possono rimanere in tali registrazioni come identificativi strutturali pseudonimi. Non sono anonimi. HolaLocal non li utilizza per ripristinare o mostrare il precedente profilo, nome, avatar o altre informazioni di profilo rimosse. Quando le informazioni conservate vengono successivamente anonimizzate, non identificano più l’utente; un identificativo pseudonimo conservato non deve essere considerato anonimo.",
      "La nostra politica è conservare le conversazioni finché almeno un partecipante mantiene un account e la cronologia resta necessaria. Non significa un accesso recente. Valutiamo separatamente le richieste di cancellazione, inclusi i dati personali nel testo dei messaggi.",
      "Per le segnalazioni diverse da quelle sulle recensioni, la nostra politica è eliminare i dati personali 90 giorni dopo la risoluzione, salvo una necessità specifica documentata ancora presente. Ogni eccezione ha un motivo, un responsabile, una prossima data di verifica e una condizione di cessazione. Una verifica scaduta non termina né rinnova automaticamente la conservazione. La politica delle segnalazioni sulle recensioni resta invariata.",
      "Le prove di accettazione e presa visione degli account esistenti sono preservate. Dopo la cancellazione dell’account, la nostra politica è conservare solo prove minime giustificate da una necessità specifica documentata, con una data di verifica, ed eliminarle quando tale necessità termina.",
      "I nuovi controlli sono predisposti, ma la pulizia distruttiva non è abilitata. Questi criteri non significano che sia operativa una pulizia automatica. La pulizia programmata delle segnalazioni sulle recensioni è separata e rimane anch’essa disabilitata."
    ],
    "request": "L’eliminazione dell’account rimuove il profilo e i relativi contenuti multimediali. Possono rimanere registrazioni limitate, tra cui consensi, segnalazioni di moderazione o sicurezza e conversazioni storiche, come spiegato nell’"
  },
  "pl": {
    "privacy": [
      "Po usunięciu konta HolaLocal usuwa aktywny profil konta i powiązane osobiste multimedia profilowe. Ograniczone rejestry mogą pozostać w celu zachowania odpowiedniej dokumentacji usługi oraz integralności i bezpieczeństwa platformy. Mogą one obejmować zaakceptowane wersje Regulaminu i Polityki prywatności wraz z datami akceptacji, istniejące zgłoszenia moderacyjne, dotyczące bezpieczeństwa lub nadużyć oraz historyczne rozmowy i wiadomości. Zgłoszenia mogą zawierać dane osobowe wpisane przez użytkowników w polach tekstowych.",
      "Historyczne identyfikatory użytkownika Firebase mogą pozostać w tych rejestrach jako pseudonimowe identyfikatory strukturalne. Nie są anonimowe. HolaLocal nie używa ich do odtwarzania ani wyświetlania dawnego profilu, imienia i nazwiska, awatara ani innych usuniętych informacji profilowych. Jeżeli zachowane informacje zostaną później zanonimizowane, przestają identyfikować użytkownika; zachowanego pseudonimowego identyfikatora nie należy traktować jako anonimowego.",
      "Nasza polityka zakłada przechowywanie rozmów, dopóki co najmniej jeden uczestnik zachowuje konto, a historia pozostaje potrzebna. Nie oznacza to niedawnego logowania. Wnioski o usunięcie rozpatrujemy osobno, także w odniesieniu do danych osobowych w treści wiadomości.",
      "W przypadku zgłoszeń innych niż dotyczące opinii nasza polityka zakłada usunięcie danych osobowych 90 dni po rozstrzygnięciu, chyba że istnieje konkretna udokumentowana dalsza potrzeba. Każdy wyjątek ma powód, odpowiedzialnego recenzenta, kolejny termin przeglądu i warunek zakończenia. Zaległy przegląd nie kończy ani nie odnawia automatycznie przechowywania. Polityka zgłoszeń opinii pozostaje bez zmian.",
      "Zachowujemy dotychczasowe potwierdzenia istniejących kont. Po usunięciu konta nasza polityka przewiduje zachowanie tylko minimalnych dowodów uzasadnionych konkretną udokumentowaną potrzebą, z terminem przeglądu, i usunięcie ich po ustaniu tej potrzeby.",
      "Nowe mechanizmy retencji są przygotowane, ale destrukcyjne usuwanie nie jest włączone. Te kryteria nie oznaczają działania automatycznego usuwania. Zaplanowane usuwanie zgłoszeń opinii jest odrębne i także pozostaje wyłączone."
    ],
    "request": "Usunięcie konta usuwa profil konta i multimedia profilowe. Ograniczone rejestry mogą pozostać, w tym rejestry zgód, zgłoszenia moderacyjne lub dotyczące bezpieczeństwa oraz historyczne rozmowy, zgodnie z wyjaśnieniem w"
  },
  "ro": {
    "privacy": [
      "Când un cont este șters, HolaLocal elimină profilul activ și fișierele media personale asociate profilului. Pot rămâne evidențe limitate pentru a păstra înregistrările corespunzătoare ale serviciului și integritatea și siguranța platformei. Acestea pot include versiunile acceptate ale Termenilor și Politicii de confidențialitate și momentele acceptării, rapoarte existente de moderare, siguranță sau abuz și conversații și mesaje istorice. Rapoartele pot include informații personale introduse de utilizatori în câmpuri de text liber.",
      "Identificatorii istorici de utilizator Firebase pot rămâne în aceste evidențe ca identificatori structurali pseudonimi. Nu sunt anonimi. HolaLocal nu îi folosește pentru a restaura sau afișa fostul profil, numele, avatarul ori alte informații de profil eliminate. Dacă informațiile păstrate sunt ulterior anonimizate, acestea nu mai identifică utilizatorul; un identificator pseudonim păstrat nu trebuie tratat ca anonim.",
      "Politica noastră este să păstrăm conversațiile cât timp cel puțin un participant păstrează un cont și istoricul rămâne necesar. Aceasta nu înseamnă autentificare recentă. Evaluăm separat cererile de ștergere, inclusiv datele personale din textul mesajelor.",
      "Pentru raportările care nu privesc recenzii, politica noastră este eliminarea datelor personale la 90 de zile după soluționare, cu excepția unei nevoi specifice documentate încă existente. Fiecare excepție are motiv, responsabil, următoare dată de revizuire și condiție de încetare. O revizuire restantă nu încheie și nu reînnoiește automat păstrarea. Politica raportărilor de recenzii rămâne neschimbată.",
      "Dovezile de acceptare și luare la cunoștință ale conturilor existente sunt păstrate. După ștergerea contului, politica noastră este să păstrăm numai dovezi minime justificate de o nevoie specifică documentată, cu dată de revizuire, și să le eliminăm când nevoia încetează.",
      "Noile controale sunt pregătite, dar ștergerea distructivă nu este activată. Aceste criterii nu înseamnă că ștergerea automată funcționează. Curățarea programată a raportărilor de recenzii este separată și rămâne de asemenea dezactivată."
    ],
    "request": "Ștergerea contului elimină profilul și fișierele media ale profilului. Pot rămâne evidențe limitate, inclusiv evidențe de consimțământ, rapoarte de moderare sau siguranță și conversații istorice, conform explicațiilor din"
  },
  "cs": {
    "privacy": [
      "Po smazání účtu HolaLocal odstraní aktivní profil účtu a související osobní profilová média. Omezené záznamy mohou zůstat zachovány kvůli odpovídající evidenci služby a integritě a bezpečnosti platformy. Mohou zahrnovat přijaté verze Podmínek a Zásad ochrany osobních údajů s časy přijetí, existující hlášení o moderování, bezpečnosti nebo zneužití a historické konverzace a zprávy. Hlášení mohou obsahovat osobní údaje zadané uživateli do polí s volným textem.",
      "Historické identifikátory uživatele Firebase mohou v těchto záznamech zůstat jako pseudonymní strukturální identifikátory. Nejsou anonymní. HolaLocal je nepoužívá k obnovení ani zobrazení dřívějšího profilu, jména, avatara nebo jiných odstraněných profilových údajů. Pokud jsou uchované informace později anonymizovány, přestanou uživatele identifikovat; uchovaný pseudonymní identifikátor se nesmí považovat za anonymní.",
      "Naší zásadou je uchovávat konverzace, dokud alespoň jeden účastník má účet a historie je nadále potřebná. Neznamená to nedávné přihlášení. Žádosti o výmaz posuzujeme samostatně, včetně osobních údajů v textu zpráv.",
      "U hlášení nesouvisejících s recenzemi je naší zásadou odstranit osobní údaje 90 dní po vyřešení, kromě konkrétní zdokumentované trvající potřeby. Každá výjimka má důvod, odpovědného posuzovatele, další datum kontroly a podmínku ukončení. Kontrola po termínu uchování automaticky neukončí ani neobnoví. Zásady hlášení recenzí se nemění.",
      "Potvrzení stávajících účtů zachováváme. Po odstranění účtu je naší zásadou uchovávat pouze minimální důkazy odůvodněné konkrétní zdokumentovanou potřebou, s datem kontroly, a odstranit je po zániku této potřeby.",
      "Nové nástroje jsou připraveny, ale destruktivní čištění není zapnuto. Tato kritéria neznamenají, že automatické čištění funguje. Plánované čištění hlášení recenzí je samostatné a rovněž zůstává vypnuté."
    ],
    "request": "Smazáním účtu se odstraní profil účtu a profilová média. Omezené záznamy mohou zůstat zachovány, včetně záznamů souhlasu, hlášení o moderování nebo bezpečnosti a historických konverzací, jak vysvětlují"
  },
  "sk": {
    "privacy": [
      "Po odstránení účtu HolaLocal odstráni aktívny profil účtu a súvisiace osobné profilové médiá. Obmedzené záznamy môžu zostať zachované na udržanie primeraných záznamov služby a integrity a bezpečnosti platformy. Môžu zahŕňať prijaté verzie Podmienok a Zásad ochrany osobných údajov s časmi prijatia, existujúce hlásenia o moderovaní, bezpečnosti alebo zneužití a historické konverzácie a správy. Hlásenia môžu obsahovať osobné údaje zadané používateľmi do polí s voľným textom.",
      "Historické identifikátory používateľa Firebase môžu v týchto záznamoch zostať ako pseudonymné štrukturálne identifikátory. Nie sú anonymné. HolaLocal ich nepoužíva na obnovenie ani zobrazenie bývalého profilu, mena, avatara alebo iných odstránených profilových údajov. Ak sa uchované informácie neskôr anonymizujú, prestanú identifikovať používateľa; uchovaný pseudonymný identifikátor sa nesmie považovať za anonymný.",
      "Našou zásadou je uchovávať konverzácie, kým aspoň jeden účastník má účet a história je naďalej potrebná. Neznamená to nedávne prihlásenie. Žiadosti o vymazanie posudzujeme samostatne vrátane osobných údajov v texte správ.",
      "Pri hláseniach nesúvisiacich s recenziami je našou zásadou odstrániť osobné údaje 90 dní po vyriešení, okrem konkrétnej zdokumentovanej trvajúcej potreby. Každá výnimka má dôvod, zodpovedného posudzovateľa, ďalší dátum kontroly a podmienku ukončenia. Kontrola po termíne uchovávanie automaticky neukončí ani neobnoví. Zásady hlásení recenzií sa nemenia.",
      "Potvrdenia existujúcich účtov zachovávame. Po odstránení účtu je našou zásadou uchovávať iba minimálne dôkazy odôvodnené konkrétnou zdokumentovanou potrebou, s dátumom kontroly, a odstrániť ich po zániku tejto potreby.",
      "Nové nástroje sú pripravené, ale deštruktívne čistenie nie je zapnuté. Tieto kritériá neznamenajú fungovanie automatického čistenia. Plánované čistenie hlásení recenzií je samostatné a tiež zostáva vypnuté."
    ],
    "request": "Odstránením účtu sa odstráni profil účtu a profilové médiá. Obmedzené záznamy môžu zostať zachované vrátane záznamov súhlasu, hlásení o moderovaní alebo bezpečnosti a historických konverzácií, ako vysvetľujú"
  },
  "hu": {
    "privacy": [
      "A fiók törlésekor a HolaLocal eltávolítja az aktív fiókprofilt és a kapcsolódó személyes profilmédiát. Korlátozott nyilvántartások megmaradhatnak a megfelelő szolgáltatási nyilvántartás, valamint a platform integritásának és biztonságának fenntartása érdekében. Ide tartozhatnak az elfogadott Felhasználási feltételek és Adatvédelmi szabályzat verziói és elfogadási időpontjai, a meglévő moderációs, biztonsági vagy visszaélési jelentések, valamint a korábbi beszélgetések és üzenetek. A jelentések a felhasználók által szabad szöveges mezőkbe írt személyes adatokat is tartalmazhatnak.",
      "A korábbi Firebase felhasználói azonosítók ezekben a nyilvántartásokban álnevesített strukturális azonosítóként maradhatnak meg. Nem névtelenek. A HolaLocal nem használja őket a törölt felhasználó korábbi profiljának, nevének, avatarjának vagy más eltávolított profiladatának helyreállítására vagy megjelenítésére. Ha a megőrzött információkat később anonimizálják, azok többé nem azonosítják a felhasználót; a megőrzött álnevesített azonosító nem kezelhető anonimként.",
      "Irányelvünk szerint addig őrizzük a beszélgetéseket, amíg legalább az egyik résztvevőnek van fiókja, és az előzményekre szükség van. Ez nem jelent közelmúltbeli bejelentkezést. A törlési kérelmeket külön vizsgáljuk, az üzenetszövegben szereplő személyes adatokat is beleértve.",
      "A nem értékelésekkel kapcsolatos bejelentéseknél irányelvünk a személyes adatok eltávolítása a lezárást követő 90 nap után, kivéve konkrét, dokumentált, fennálló szükség esetén. Minden kivételhez indok, felelős felülvizsgáló, következő felülvizsgálati dátum és megszűnési feltétel tartozik. A lejárt felülvizsgálat nem szünteti meg és nem újítja meg automatikusan a megőrzést. Az értékelési bejelentésekre vonatkozó szabály változatlan.",
      "A meglévő fiókok elfogadási és tudomásulvételi bizonyítékait megőrizzük. Fióktörlés után irányelvünk csak konkrét, dokumentált szükség által indokolt minimális bizonyíték megőrzése felülvizsgálati dátummal, majd annak törlése a szükség megszűnésekor.",
      "Az új megőrzési vezérlők előkészültek, de a végleges törlés nincs engedélyezve. Ezek a feltételek nem jelentik automatikus törlés működését. Az értékelési bejelentések ütemezett törlése különálló és szintén kikapcsolt."
    ],
    "request": "A fiók törlése eltávolítja a fiókprofilt és a profilmédiát. Korlátozott nyilvántartások megmaradhatnak, például hozzájárulási adatok, moderációs vagy biztonsági jelentések és korábbi beszélgetések, az alábbiak szerint:"
  },
  "uk": {
    "privacy": [
      "Після видалення облікового запису HolaLocal видаляє активний профіль і пов’язані особисті медіафайли профілю. Обмежені записи можуть зберігатися для підтримання належних службових записів, цілісності та безпеки платформи. До них можуть належати прийняті версії Умов і Політики конфіденційності та час їх прийняття, наявні звіти про модерацію, безпеку чи зловживання, а також історичні розмови й повідомлення. Звіти можуть містити особисту інформацію, яку користувачі ввели у поля вільного тексту.",
      "Історичні ідентифікатори користувача Firebase можуть залишатися в цих записах як псевдонімні структурні ідентифікатори. Вони не є анонімними. HolaLocal не використовує їх для відновлення чи показу колишнього профілю, імені, аватара або іншої видаленої інформації профілю. Якщо збережену інформацію згодом анонімізують, вона більше не ідентифікує користувача; збережений псевдонімний ідентифікатор не можна вважати анонімним.",
      "Наша політика — зберігати історію розмов, доки хоча б один учасник має обліковий запис і історія залишається потрібною. Це не означає нещодавній вхід. Запити на видалення розглядаємо окремо, зокрема щодо персональних даних у тексті повідомлень.",
      "Для скарг, не пов’язаних із відгуками, наша політика — видаляти персональні дані через 90 днів після вирішення, крім конкретної документованої потреби, що зберігається. Кожен виняток має причину, відповідального, дату наступного перегляду та умову завершення. Прострочений перегляд не припиняє і не поновлює збереження автоматично. Політика скарг на відгуки не змінюється.",
      "Підтвердження наявних облікових записів зберігаються. Після видалення облікового запису наша політика — залишати лише мінімальні докази для конкретної документованої потреби з датою перегляду та видаляти їх після завершення цієї потреби.",
      "Нові засоби зберігання підготовлено, але незворотне очищення не ввімкнено. Ці критерії не означають, що автоматичне очищення працює. Заплановане очищення скарг на відгуки є окремим і також залишається вимкненим."
    ],
    "request": "Видалення облікового запису видаляє профіль і медіафайли профілю. Обмежені записи можуть залишатися, зокрема записи згоди, звіти про модерацію чи безпеку та історичні розмови, як пояснено в"
  },
  "sv": {
    "privacy": [
      "När ett konto raderas tar HolaLocal bort den aktiva kontoprofilen och tillhörande personliga profilmedia. Begränsade poster kan finnas kvar för att bevara lämpliga tjänsteposter samt plattformens integritet och säkerhet. De kan omfatta accepterade versioner av Villkoren och Integritetspolicyn med respektive tidpunkter för godkännande, befintliga modererings-, säkerhets- eller missbruksrapporter samt historiska konversationer och meddelanden. Rapporter kan innehålla personuppgifter som användare har skrivit i fritextfält.",
      "Historiska Firebase-användaridentifierare kan finnas kvar i dessa poster som pseudonyma strukturella identifierare. De är inte anonyma. HolaLocal använder dem inte för att återställa eller visa den raderade användarens tidigare profil, namn, avatar eller annan borttagen profilinformation. Om sparad information senare anonymiseras identifierar den inte längre användaren; en sparad pseudonym identifierare får inte behandlas som anonym.",
      "Vår policy är att behålla samtal så länge minst en deltagare har kvar ett konto och historiken fortfarande behövs. Det betyder inte nylig inloggning. Vi bedömer raderingsbegäranden separat, även personuppgifter i meddelandetext.",
      "För rapporter som inte gäller omdömen är vår policy att ta bort personuppgifter 90 dagar efter avslut, utom vid ett specifikt dokumenterat kvarstående behov. Varje undantag har ett skäl, en ansvarig granskare, nästa granskningsdatum och ett slutvillkor. En försenad granskning avslutar eller förnyar inte bevarandet automatiskt. Policyn för omdömesrapporter är oförändrad.",
      "Befintliga kontons godkännande- och bekräftelseuppgifter bevaras. Efter kontoradering är vår policy att endast behålla minimala bevis för ett specifikt dokumenterat behov, med granskningsdatum, och ta bort dem när behovet upphör.",
      "De nya kontrollerna är förberedda, men destruktiv rensning är inte aktiverad. Dessa kriterier betyder inte att automatisk rensning körs. Schemalagd rensning av omdömesrapporter är separat och också fortsatt avstängd."
    ],
    "request": "När du raderar kontot tas kontoprofilen och profilmedierna bort. Begränsade poster kan finnas kvar, bland annat samtyckesposter, modererings- eller säkerhetsrapporter och historiska konversationer, enligt förklaringen i"
  },
  "da": {
    "privacy": [
      "Når en konto slettes, fjerner HolaLocal den aktive kontoprofil og tilknyttede personlige profilmedier. Begrænsede registreringer kan forblive for at bevare passende tjenesteregistreringer samt platformens integritet og sikkerhed. De kan omfatte accepterede versioner af Vilkårene og Privatlivspolitikken med tidspunkter for accept, eksisterende moderations-, sikkerheds- eller misbrugsrapporter samt historiske samtaler og beskeder. Rapporter kan indeholde personoplysninger, som brugere har indtastet i fritekstfelter.",
      "Historiske Firebase-brugeridentifikatorer kan forblive i disse registreringer som pseudonyme strukturelle identifikatorer. De er ikke anonyme. HolaLocal bruger dem ikke til at gendanne eller vise den slettede brugers tidligere profil, navn, avatar eller andre fjernede profiloplysninger. Hvis bevarede oplysninger senere anonymiseres, identificerer de ikke længere brugeren; en bevaret pseudonym identifikator må ikke behandles som anonym.",
      "Vores politik er at beholde samtaler, så længe mindst én deltager beholder en konto, og historikken stadig er nødvendig. Det betyder ikke nyligt login. Vi vurderer sletningsanmodninger særskilt, også personoplysninger i beskedteksten.",
      "For rapporter, der ikke vedrører anmeldelser, er vores politik at fjerne personoplysninger 90 dage efter afslutning, undtagen ved et konkret dokumenteret fortsat behov. Hver undtagelse har en grund, ansvarlig kontrollant, næste gennemgangsdato og afslutningsbetingelse. En forsinket gennemgang afslutter eller fornyer ikke opbevaring automatisk. Politikken for anmeldelsesrapporter er uændret.",
      "Eksisterende kontis accept- og bekræftelsesoplysninger bevares. Efter kontosletning er vores politik kun at beholde minimale beviser for et konkret dokumenteret behov med gennemgangsdato og fjerne dem, når behovet ophører.",
      "De nye kontroller er forberedt, men destruktiv oprydning er ikke aktiveret. Disse kriterier betyder ikke, at automatisk oprydning kører. Planlagt oprydning i anmeldelsesrapporter er særskilt og fortsat også deaktiveret."
    ],
    "request": "Når du sletter din konto, fjernes kontoprofilen og profilmedierne. Begrænsede registreringer kan forblive, herunder samtykkeregistreringer, moderations- eller sikkerhedsrapporter og historiske samtaler, som forklaret i"
  },
  "fi": {
    "privacy": [
      "Kun tili poistetaan, HolaLocal poistaa aktiivisen tiliprofiilin ja siihen liittyvän henkilökohtaisen profiilimedian. Rajallisia tietueita voidaan säilyttää asianmukaisten palvelutietojen sekä alustan eheyden ja turvallisuuden ylläpitämiseksi. Niihin voivat kuulua hyväksyttyjen käyttöehtojen ja tietosuojakäytännön versiot ja hyväksymisajankohdat, olemassa olevat moderointi-, turvallisuus- tai väärinkäytösraportit sekä historialliset keskustelut ja viestit. Raportit voivat sisältää käyttäjien vapaisiin tekstikenttiin syöttämiä henkilötietoja.",
      "Historialliset Firebase-käyttäjätunnisteet voivat jäädä näihin tietueisiin pseudonyymeinä rakenteellisina tunnisteina. Ne eivät ole anonyymejä. HolaLocal ei käytä niitä poistetun käyttäjän entisen profiilin, nimen, avatarin tai muiden poistettujen profiilitietojen palauttamiseen tai näyttämiseen. Jos säilytetyt tiedot myöhemmin anonymisoidaan, ne eivät enää tunnista käyttäjää; säilytettyä pseudonyymiä tunnistetta ei saa käsitellä anonyyminä.",
      "Käytäntömme on säilyttää keskustelut niin kauan kuin vähintään yhdellä osallistujalla on tili ja historiaa edelleen tarvitaan. Tämä ei tarkoita äskettäistä kirjautumista. Arvioimme poistopyynnöt erikseen, myös viestitekstin henkilötiedot.",
      "Muita kuin arvosteluja koskevissa ilmoituksissa käytäntömme on poistaa henkilötiedot 90 päivää ratkaisun jälkeen, ellei ole erityistä dokumentoitua jatkuvaa tarvetta. Jokaisella poikkeuksella on syy, vastuullinen arvioija, seuraava tarkistuspäivä ja päättymisehto. Myöhästynyt tarkistus ei automaattisesti lopeta tai uusi säilyttämistä. Arvosteluilmoitusten käytäntö ei muutu.",
      "Olemassa olevien tilien hyväksyntä- ja kuittausmerkinnät säilytetään. Tilin poistamisen jälkeen käytäntömme on säilyttää vain erityisen dokumentoidun tarpeen perustelemat vähimmäistodisteet tarkistuspäivineen ja poistaa ne tarpeen päättyessä.",
      "Uudet hallintatoiminnot on valmisteltu, mutta tuhoavaa poistoa ei ole otettu käyttöön. Nämä perusteet eivät tarkoita automaattisen poiston toimivan. Arvosteluilmoitusten ajastettu poisto on erillinen ja myös edelleen pois käytöstä."
    ],
    "request": "Tilin poistaminen poistaa tiliprofiilin ja profiilimedian. Rajallisia tietueita voidaan säilyttää, mukaan lukien suostumustiedot, moderointi- tai turvallisuusraportit ja historialliset keskustelut, kuten selitetään kohdassa"
  },
  "no": {
    "privacy": [
      "Når en konto slettes, fjerner HolaLocal den aktive kontoprofilen og tilknyttede personlige profilmedier. Begrensede registre kan bli værende for å bevare passende tjenesteregistre og plattformens integritet og sikkerhet. Disse kan omfatte aksepterte versjoner av Vilkårene og Personvernerklæringen med tidspunktene for aksept, eksisterende modererings-, sikkerhets- eller misbruksrapporter og historiske samtaler og meldinger. Rapporter kan inneholde personopplysninger som brukere har skrevet i fritekstfelt.",
      "Historiske Firebase-brukeridentifikatorer kan bli værende i disse registrene som pseudonyme strukturelle identifikatorer. De er ikke anonyme. HolaLocal bruker dem ikke til å gjenopprette eller vise den slettede brukerens tidligere profil, navn, avatar eller andre fjernede profilopplysninger. Hvis bevarte opplysninger senere anonymiseres, identifiserer de ikke lenger brukeren; en bevart pseudonym identifikator må ikke behandles som anonym.",
      "Vår policy er å beholde samtaler så lenge minst én deltaker beholder en konto og historikken fortsatt trengs. Dette betyr ikke nylig innlogging. Vi vurderer sletteforespørsler separat, også personopplysninger i meldingstekst.",
      "For rapporter som ikke gjelder anmeldelser er vår policy å fjerne personopplysninger 90 dager etter avslutning, unntatt ved et konkret dokumentert fortsatt behov. Hvert unntak har en grunn, ansvarlig gjennomgåer, neste gjennomgangsdato og sluttvilkår. En forsinket gjennomgang avslutter eller fornyer ikke bevaring automatisk. Policyen for anmeldelsesrapporter er uendret.",
      "Eksisterende kontoers aksept- og bekreftelsesopplysninger bevares. Etter kontosletting er vår policy å beholde bare minimale bevis for et konkret dokumentert behov, med gjennomgangsdato, og fjerne dem når behovet opphører.",
      "De nye kontrollene er klargjort, men destruktiv opprydding er ikke aktivert. Disse kriteriene betyr ikke at automatisk opprydding kjører. Planlagt opprydding i anmeldelsesrapporter er separat og fortsatt også deaktivert."
    ],
    "request": "Når du sletter kontoen, fjernes kontoprofilen og profilmediene. Begrensede registre kan bli værende, blant annet samtykkeregistre, modererings- eller sikkerhetsrapporter og historiske samtaler, som forklart i"
  }
}
