export const deletionDisclosureEnglishTranslations = {
  "privacy": [
    "When an account is deleted, HolaLocal removes the active account profile and associated personal profile media. Limited records may remain to preserve appropriate service records and the integrity and safety of the platform. These may include the Terms and Privacy Policy versions accepted and their acceptance timestamps, existing moderation, safety or abuse reports, and historic conversations and messages. Reports may include personal information that users entered in free-text fields.",
    "Historic Firebase user identifiers may remain in these records as pseudonymous structural identifiers. They are not anonymous. HolaLocal does not use them to restore or display the deleted user’s former profile, name, avatar or other removed profile information. Where retained information is later anonymised, it no longer identifies the user; a retained pseudonymous identifier must not be treated as anonymous.",
    "Our retention policy is to keep conversation history while at least one participant retains an account and the history remains needed. This does not mean recent login activity. We assess erasure requests separately, including personal information within message text.",
    "For non-review reports, our policy is to remove personal information 90 days after resolution, except for a specific documented ongoing need. Each preservation exception has a reason, responsible reviewer, next review date and ending condition. An overdue review does not automatically end or renew preservation. The separate customer-review report policy remains unchanged.",
    "Existing account acknowledgment records are preserved. After account deletion, our policy is to retain only minimal acknowledgment evidence justified by a specific documented need, with a review date, and remove it when that need ends.",
    "The new retention controls are prepared but destructive cleanup is not enabled. These policy criteria do not mean automated cleanup is operating. Scheduled customer-review report cleanup is separate and also remains disabled."
  ],
  "request": "Deleting your account removes your account profile and profile media. Limited records may remain, including consent records, moderation or safety reports, and historic conversation records, as explained in the"
}
