import { reviewPrivacySection, reviewTermsSection } from './reviewDisclosureTranslations.js'
import { deletionDisclosureEnglishTranslations } from './deletionDisclosureEnglishTranslations.js'

export const englishReviewAvailability = "Customer reviews and public review translation are not yet available. The review policy below is prepared for launch; scheduled report cleanup is not yet running."

const termsSections = [
  { key: 'platform', title: 'The HolaLocal platform', paragraphs: ['HolaLocal is a developing local marketplace. Features may be changed, paused or removed as the service evolves. By taking part, you agree to use the service responsibly and understand that the experience will continue to improve.'] },
  { key: 'account', title: 'Your account', paragraphs: ["You must provide accurate account information, protect your password and tell us promptly if you suspect unauthorised access. Do not share access in a way that compromises another person or the platform."] },
  { key: 'customers', title: 'Customer accounts', paragraphs: ['Customer accounts are for finding local services, managing preferences and contacting businesses. Customers must communicate respectfully and independently check that a business is suitable, qualified and insured where relevant before agreeing to work.'] },
  { key: 'businesses', title: 'Business profiles', paragraphs: ['Businesses and professionals may prepare profiles describing their services, coverage, languages and contact preferences. You must have authority to represent the business and keep all details, images, qualifications and claims accurate and current.', 'Business owners can save a private draft and submit it for review. Only approved, active listings are public. A returned profile can be corrected and submitted again. Email verification, business verification and publication are separate; creating an account does not guarantee publication or verification.'] },
  reviewTermsSection('en', englishReviewAvailability, "When reviews are available, each customer may have one current review per business. Submissions and edits require moderation before publication. An existing published version remains visible while an edit awaits a decision; withdrawal removes it from public view. Each account may submit or edit reviews five times and report published reviews ten times in a rolling 24 hours. Identical retries do not count twice, and withdrawal remains available. A resolved report is not reopened automatically; a new report may concern currently published content. Questions about a moderation decision can be sent to <email>hello@holalocal.es</email>."),
  { key: 'prohibited', title: 'Prohibited behaviour', paragraphs: ['You must not use HolaLocal to:'], items: ['abuse, threaten, harass or discriminate against another person;', 'send spam, misleading promotions or unwanted repeated messages;', 'run scams, impersonate others or create fake business profiles;', 'offer illegal, unsafe or deliberately misleading services;', 'upload harmful content or interfere with the platform’s security or operation; or', 'use another person’s personal information without permission or a lawful reason.'] },
  { key: 'messaging', title: 'Messaging and translation', paragraphs: ["HolaLocal messaging is the platform’s core contact method and cannot be disabled by a business. Optional public contact channels may also be available. HolaLocal stores messages for the conversation participants. Messages are not public reviews or business-listing content. Private-message translation is currently disabled; the separate public-review translation policy does not apply to private messages. Avoid including unnecessary sensitive information, and confirm important arrangements directly with the other participant. Automated translations can be inaccurate, so users should confirm prices, addresses, dates, safety instructions and other important details directly with each other."] },
  { key: 'changes', title: 'Changes, suspension and removal', paragraphs: ['We may change the platform during development. We may restrict, suspend or remove accounts, profiles or content where reasonably necessary to protect users, investigate reports, comply with law or enforce these terms. Serious or repeated misuse may result in permanent removal.'] },
  {"key": "discovery-pricing", "title": "Finding businesses and current pricing", "paragraphs": ["The directory starts with recently published eligible businesses, newest first. Search, service, area and language filters narrow the loaded results without using payment as a ranking score. The loaded directory is limited and is not an exhaustive list of all businesses. Business profiles are free during Early Access. Customers and businesses agree prices and payment for their services directly; creating a profile does not enrol you in a paid subscription."]},
  { key: 'availability', title: 'Availability and responsibility', paragraphs: ['We do not guarantee that HolaLocal will always be available, error-free or launch on a particular date. HolaLocal helps people discover and communicate with independent businesses; it does not employ those businesses or become a party to agreements between users.', 'To the extent permitted by law, HolaLocal is not responsible for indirect losses or for the quality, safety, legality or outcome of services arranged between users. Nothing in these terms excludes rights or liability that cannot legally be excluded, including applicable consumer rights.'] },
  { key: 'law', title: 'Governing law', paragraphs: ['These terms are governed by the laws of Spain. Any mandatory consumer protections and rights to bring a claim in another competent court remain unaffected.'] },
  { key: 'contact', title: 'Contact', paragraphs: ["HolaLocal is operated personally by Craig Evans. HolaLocal is the name of the platform.", 'Questions about these terms can be sent to <email>hello@holalocal.es</email>.'] },
]

const privacySections = [
  reviewPrivacySection('en', englishReviewAvailability),
  { key: 'audience', title: 'Who HolaLocal is for', paragraphs: ['HolaLocal is being developed for customers looking for local services and for businesses and self-employed professionals offering services across Spain. HolaLocal lets people create real accounts, manage profiles and connect through the local marketplace.'] },
  { key: 'information', title: 'Information we may collect', items: ['Account details, such as your name, email address, account role and login information.', 'Customer profile details, including your preferred language and general location.', 'Business profile details, including business name, services, service areas, languages and description.', 'Contact preferences and optional business phone, email and WhatsApp details.', 'Business logos, profile images and work images where uploads are supported.', 'Messages, reports and information you choose to submit through platform features.', 'Technical and security data, such as device, browser, authentication, error and activity information.'], paragraphs: ['We do not ask you to provide information that is not reasonably needed for the service.'] },
  { key: 'purpose', title: 'Why we use information', paragraphs: ['We use information to create and protect accounts, provide profile and messaging features, prepare business listings, remember language and location preferences, respond to support requests, prevent abuse, investigate reports and improve the HolaLocal experience.'] },
  { key: 'profiles', title: 'Business and customer profiles', paragraphs: ['Business owners can save a private draft and submit it for review. Only approved, active listings are public. A returned profile can be corrected and submitted again. Email verification, business verification and publication are separate; creating an account does not guarantee publication or verification.'] },
  { key: 'providers', title: 'Service providers and storage', paragraphs: ["HolaLocal uses Google Firebase for authentication, Firestore database storage and file storage, and Vercel for website hosting. Public-review translation is prepared using Google Cloud Translation as described separately. An EU location for one service does not mean all provider operations take place in the EU."] },
  {"key": "messaging", "title": "Private messages", "paragraphs": ["HolaLocal stores messages for the conversation participants. Messages are not public reviews or business-listing content. Private-message translation is currently disabled; the separate public-review translation policy does not apply to private messages. Avoid including unnecessary sensitive information, and confirm important arrangements directly with the other participant."]},
  {"key": "browser-storage", "title": "Browser storage", "paragraphs": ["The website uses browser storage for sign-in and your selected website language. The language preference remains until you change it or clear browser storage. Accepting the Terms or acknowledging this Privacy Policy is not consent to optional analytics or marketing.", "Business profile views and contact actions also generate usage counts. A random token in session storage helps avoid counting the same profile view repeatedly. This is separate from Firebase Analytics."]},
  { key: 'visibility', title: 'Contact visibility', paragraphs: ['HolaLocal messaging is the core contact method. Businesses may optionally add a phone number, email address or WhatsApp number and control whether each is shown publicly. Hidden contact values are not included in public business-profile data. Businesses should only publish contact information they are comfortable sharing.'] },
  { key: 'deletion', title: 'Deletion and your choices', paragraphs: [
    "You can request account deletion from Profile where that control is available, or contact <email>hello@holalocal.es</email> for account deletion and other privacy requests. We may need to verify your identity; contact us if you cannot access your account email. Subject to applicable law, you may request access, correction, erasure, restriction or portability of your data and object to processing. You may complain to <authority>AEPD</authority> or another competent data-protection authority.",
    ...deletionDisclosureEnglishTranslations.privacy,
  ] },
  {"key": "cloud-retention", "title": "Cloud backups and logs", "paragraphs": ["Current cloud settings retain daily database backups for 30 days, soft-deleted files for 7 days, ordinary cloud logs for 30 days and required cloud audit logs for 400 days. Removing information from the live service does not immediately remove retained backup or log copies."]},
  { key: 'security', title: 'Security', paragraphs: ['We use reasonable technical and organisational safeguards, including access controls and protected authentication. No online service can promise absolute security, so please use a strong password and contact us if you believe your account has been compromised.'] },
  { key: 'changes', title: 'Policy changes', paragraphs: ['HolaLocal will continue to evolve. We may update this policy when features, providers or legal requirements change. The version and effective date at the top will identify the current policy, and material changes will be communicated where appropriate.'] },
  { key: 'contact', title: 'Contact', paragraphs: ["HolaLocal is operated personally by Craig Evans. HolaLocal is the name of the platform.", 'Questions about privacy or this policy can be sent to <email>hello@holalocal.es</email>.'] },
]

export const englishLegalPages = {
  revisionNotice: "Draft update · Not yet effective",
  terms: { sections: termsSections },
  privacy: { sections: privacySections },
}
