import { deletionDisclosureEnglishTranslations } from './deletionDisclosureEnglishTranslations.js'

const termsSections = [
  { key: 'platform', title: 'The HolaLocal platform', paragraphs: ['HolaLocal is a developing local marketplace. Features may be changed, paused or removed as the service evolves. By taking part, you agree to use the service responsibly and understand that the experience will continue to improve.'] },
  { key: 'account', title: 'Your account', paragraphs: ['You must provide accurate account information, protect your password and tell us promptly if you suspect unauthorised access. You are responsible for activity carried out through your account. Do not share access in a way that compromises another person or the platform.'] },
  { key: 'customers', title: 'Customer accounts', paragraphs: ['Customer accounts are for finding local services, managing preferences and contacting businesses. Customers must communicate respectfully and independently check that a business is suitable, qualified and insured where relevant before agreeing to work.'] },
  { key: 'businesses', title: 'Business profiles', paragraphs: ['Businesses and professionals may prepare profiles describing their services, coverage, languages and contact preferences. You must have authority to represent the business and keep all details, images, qualifications and claims accurate and current.', 'Draft business profiles are not public listings, approvals, endorsements or verified statuses. Publishing and review processes may be introduced or updated, and we may ask for further information before a profile becomes public.'] },
  { key: 'prohibited', title: 'Prohibited behaviour', paragraphs: ['You must not use HolaLocal to:'], items: ['abuse, threaten, harass or discriminate against another person;', 'send spam, misleading promotions or unwanted repeated messages;', 'run scams, impersonate others or create fake business profiles;', 'offer illegal, unsafe or deliberately misleading services;', 'upload harmful content or interfere with the platform’s security or operation; or', 'use another person’s personal information without permission or a lawful reason.'] },
  { key: 'messaging', title: 'Messaging and translation', paragraphs: ['HolaLocal messaging is the platform’s core contact method and cannot be disabled by a business. Optional public contact channels may also be available. Translation features may be added or improved later. Automated translations can be inaccurate, so users should confirm prices, addresses, dates, safety instructions and other important details directly with each other.'] },
  { key: 'changes', title: 'Changes, suspension and removal', paragraphs: ['We may change the platform during development. We may restrict, suspend or remove accounts, profiles or content where reasonably necessary to protect users, investigate reports, comply with law or enforce these terms. Serious or repeated misuse may result in permanent removal.'] },
  { key: 'availability', title: 'Availability and responsibility', paragraphs: ['We do not guarantee that HolaLocal will always be available, error-free or launch on a particular date. HolaLocal helps people discover and communicate with independent businesses; it does not employ those businesses or become a party to agreements between users.', 'To the extent permitted by law, HolaLocal is not responsible for indirect losses or for the quality, safety, legality or outcome of services arranged between users. Nothing in these terms excludes rights or liability that cannot legally be excluded, including applicable consumer rights.'] },
  { key: 'law', title: 'Governing law', paragraphs: ['These terms are governed by the laws of Spain. Any mandatory consumer protections and rights to bring a claim in another competent court remain unaffected.'] },
  { key: 'contact', title: 'Contact', paragraphs: ['Questions about these terms can be sent to <email>hello@holalocal.es</email>.'] },
]

const privacySections = [
  { key: 'audience', title: 'Who HolaLocal is for', paragraphs: ['HolaLocal is being developed for customers looking for local services and for businesses and self-employed professionals offering services across Spain. HolaLocal lets people create real accounts, manage profiles and connect through the local marketplace.'] },
  { key: 'information', title: 'Information we may collect', items: ['Account details, such as your name, email address, account role and login information.', 'Customer profile details, including your preferred language and general location.', 'Business profile details, including business name, services, service areas, languages and description.', 'Contact preferences and optional business phone, email and WhatsApp details.', 'Business logos, profile images and work images where uploads are supported.', 'Messages, reports and information you choose to submit through platform features.', 'Technical and security data, such as device, browser, authentication, error and activity information.'], paragraphs: ['We do not ask you to provide information that is not reasonably needed for the service.'] },
  { key: 'purpose', title: 'Why we use information', paragraphs: ['We use information to create and protect accounts, provide profile and messaging features, prepare business listings, remember language and location preferences, respond to support requests, prevent abuse, investigate reports and improve the HolaLocal experience.'] },
  { key: 'profiles', title: 'Business and customer profiles', paragraphs: ['New business profiles may remain private and marked as drafts until marketplace publishing becomes available. Creating a draft does not guarantee publication or verification. We will explain any additional publishing choices before making a draft profile public.'] },
  { key: 'providers', title: 'Service providers and storage', paragraphs: ['HolaLocal uses cloud services, including Firebase services for authentication, database and file storage, together with website hosting and operational providers. These providers process information only to support the platform and are subject to their own security and privacy terms. Data may be processed outside your country with appropriate safeguards where required.'] },
  { key: 'visibility', title: 'Contact visibility', paragraphs: ['HolaLocal messaging is the core contact method. Businesses may optionally add a phone number, email address or WhatsApp number and control whether each is shown publicly. Hidden contact values are not included in public business-profile data. Businesses should only publish contact information they are comfortable sharing.'] },
  { key: 'deletion', title: 'Deletion and your choices', paragraphs: [
    'You may ask us to correct your information or request account deletion by emailing <email>hello@holalocal.es</email> from the address associated with your account. Use the subject “Privacy or account deletion request”. We may need to verify your identity.',
    ...deletionDisclosureEnglishTranslations.privacy,
  ] },
  { key: 'security', title: 'Security', paragraphs: ['We use reasonable technical and organisational safeguards, including access controls and protected authentication. No online service can promise absolute security, so please use a strong password and contact us if you believe your account has been compromised.'] },
  { key: 'changes', title: 'Policy changes', paragraphs: ['HolaLocal will continue to evolve. We may update this policy when features, providers or legal requirements change. The version and effective date at the top will identify the current policy, and material changes will be communicated where appropriate.'] },
  { key: 'contact', title: 'Contact', paragraphs: ['Questions about privacy or this policy can be sent to <email>hello@holalocal.es</email>.'] },
]

export const englishLegalPages = {
  terms: { sections: termsSections },
  privacy: { sections: privacySections },
}
