import {chromium} from 'playwright'
import assert from 'node:assert/strict'
import {resolve} from 'node:path'
const browser=await chromium.launch({args:['--disable-dev-shm-usage']})
async function login(email){const c=await browser.newContext({viewport:{width:390,height:900}});await c.route('**/*',r=>/^http:\/\/127\.0\.0\.1:/.test(r.request().url())?r.continue():r.abort());const p=await c.newPage();await p.goto('http://127.0.0.1:4175/login');await p.locator('input[type=email]').fill(email);await p.locator('input[type=password]').fill('BrowserSmoke!234');await p.getByRole('button',{name:'Log in',exact:true}).click();await p.waitForURL(u=>!u.pathname.includes('/login'));return p}
try{
 const customer=await login('customer.browser@example.invalid')
 const requested=await customer.evaluate(async()=>{const m=await import('/src/firebase/functionsClient.js');return (await m.requestAccountDeletionCallable({})).data});assert.equal(requested.ok,true)
 const admin=await login('admin.browser@example.invalid');await admin.goto('http://127.0.0.1:4175/admin/account-deletions');const card=admin.locator('.admin-deletion-card').first();await card.waitFor();await admin.screenshot({path:resolve('../../../review-evidence/admin-visual-preview/deletions-populated-390.png'),fullPage:true});await card.click();const dialog=admin.getByRole('dialog');await dialog.waitFor();assert.equal(await dialog.evaluate(n=>n.scrollWidth<=n.clientWidth),true)
 await dialog.locator('.button--danger').click();await admin.getByRole('dialog').waitFor();await admin.screenshot({path:resolve('../../../review-evidence/admin-visual-preview/deletion-confirm-390.png')});await admin.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();await admin.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();assert.equal(await card.evaluate(n=>n===document.activeElement),true)
 await card.click();await admin.getByRole('dialog').locator('.button--danger').click();await admin.getByRole('dialog').locator('.button--danger').click();await admin.getByRole('dialog').waitFor({state:'hidden'});await admin.waitForTimeout(2000);await admin.reload();await admin.getByRole('button',{name:'Include completed and cancelled'}).click();await admin.getByText('Completed',{exact:true}).waitFor();console.log('PASS real synthetic account deletion: request, populated queue, cancel, focus restore, finalize and reload.')
}finally{await browser.close()}
