// Run only against scripts/runCustomerReviewDemo.mjs. Synthetic data and loopback services only.
import assert from 'node:assert/strict'
import {chromium} from 'playwright'
import {createRequire} from 'node:module'
import {resolve} from 'node:path'
import {mkdir} from 'node:fs/promises'
const root=resolve(import.meta.dirname,'../../../..')
const require=createRequire(resolve(root,'functions/package.json'))
for(const key of ['GOOGLE_APPLICATION_CREDENTIALS','FIREBASE_TOKEN','GOOGLE_OAUTH_ACCESS_TOKEN'])assert.ok(!process.env[key])
const hub=await fetch('http://127.0.0.1:4400/emulators',{redirect:'error'}).then(r=>r.json())
for(const [name,port] of Object.entries({auth:9099,firestore:8080,functions:5001,storage:9199}))assert.deepEqual([hub[name]?.host,hub[name]?.port],['127.0.0.1',port])
process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080';process.env.FIREBASE_AUTH_EMULATOR_HOST='127.0.0.1:9099'
const {initializeApp}=require('firebase-admin/app'),{getFirestore,Timestamp}=require('firebase-admin/firestore')
const db=getFirestore(initializeApp({projectId:'demo-holalocal-functions'}))
for(const id of ['customer','reporter','admin'])await db.doc(`users/review-demo-${id}-v1`).update({firstName:'Private',lastName:'Account',displayName:'PRIVATE ACCOUNT NAME',displayNameNormalized:'private account name',city:'Málaga',country:'Spain',profileCompleted:true})
const evidence=resolve(root,'../review-evidence/policy-browser');await mkdir(evidence,{recursive:true})
const b=await chromium.launch({headless:true,args:['--disable-dev-shm-usage']})
const errors=[]
async function pageFor(role,width=390){
 const context=await b.newContext({viewport:{width,height:900}})
 await context.route('**/*',route=>/^http:\/\/127\.0\.0\.1:/.test(route.request().url())?route.continue():route.abort())
 const p=await context.newPage();p.setDefaultTimeout(20000);p.on('pageerror',e=>errors.push(e.message))
 await p.goto('http://127.0.0.1:4190/login',{waitUntil:'domcontentloaded'})
 await p.locator('input[type=email]').fill(`${role}@reviews.example.invalid`)
 await p.locator('input[type=password]').fill('Fictional-review-demo-47!')
 await p.getByRole('button',{name:'Log in',exact:true}).click()
 await p.waitForURL(u=>!u.pathname.includes('/login'))
 return p
}
try{
 const customer=await pageFor('customer')
 await customer.goto('http://127.0.0.1:4190/services/review-demo-business-v1',{waitUntil:'domcontentloaded'})
 const section=customer.locator('section.customer-reviews').first()
 await section.getByRole('button',{name:'Write a review',exact:true}).click()
 const name=section.locator('input[name=displayName]')
 assert.equal(await name.inputValue(),'')
 assert.ok((await section.innerText()).includes('This name will be public'))
 assert.ok((await section.innerText()).includes('does not prove a purchase or service'))
 await section.getByRole('button',{name:'Submit review',exact:true}).click()
 assert.equal(await name.evaluate(n=>n===document.activeElement),true)
 const chosen='Éloise <script> & neighbours'
 await name.fill(chosen)
 await section.getByRole('radio',{name:'Rating: 4 / 5',exact:true}).check()
 await section.locator('textarea').fill('A carefully completed synthetic service for this isolated browser test.')
 await name.scrollIntoViewIfNeeded()
 await customer.screenshot({path:resolve(evidence,'public-name-mobile.png')})
 const sent=[];let drop=true
 await customer.route('**/submitCustomerReview',async route=>{
  if(route.request().method()!=='POST')return route.continue()
  sent.push(route.request().postDataJSON().data)
  if(drop){drop=false;const response=await route.fetch();assert.equal(response.status(),200);await route.abort('failed')}else await route.continue()
 })
 await section.getByRole('button',{name:'Submit review',exact:true}).click()
 await section.getByRole('button',{name:'Retry',exact:true}).click()
 await section.getByText('Awaiting approval',{exact:true}).waitFor()
 assert.equal(sent.length,2);assert.deepEqual(sent[0],sent[1]);assert.equal(sent[0].displayName,chosen)
 const slots=await db.collection('customerReviewSlots').where('authorUid','==','review-demo-customer-v1').get()
 assert.equal(slots.size,1)
 const slot=slots.docs[0];assert.equal(slot.data().revisionCount,1)
 assert.equal((await slot.ref.collection('revisions').get()).size,1)
 assert.equal((await db.collection('customerReviewsPublic').get()).size,0)
 const admin=await pageFor('admin',1440)
 await admin.goto('http://127.0.0.1:4190/admin/customer-reviews',{waitUntil:'domcontentloaded'})
 await admin.getByRole('button',{name:'Open case',exact:true}).click()
 await admin.getByText(`Public display name: ${chosen}`,{exact:true}).waitFor()
 await admin.getByRole('button',{name:'Approve',exact:true}).click()
 await admin.getByRole('dialog').press('Escape')
 await admin.getByRole('button',{name:'Approve',exact:true}).waitFor()
 await admin.getByRole('button',{name:'Approve',exact:true}).click()
 await admin.getByRole('dialog').getByRole('button',{name:'Confirm',exact:true}).click()
 await customer.reload({waitUntil:'domcontentloaded'})
 await section.getByRole('heading',{name:chosen,exact:true}).waitFor()
 assert.equal(await section.locator('script').count(),0)
 assert.ok(!(await section.innerText()).includes('PRIVATE ACCOUNT NAME'))
 await section.getByRole('button',{name:'Edit your review',exact:true}).click()
 assert.equal(await name.inputValue(),chosen)
 await name.fill('Replacement public name')
 await section.getByRole('button',{name:'Submit edit',exact:true}).click()
 await section.getByText('Published; edit awaiting approval',{exact:true}).waitFor()
 await customer.reload({waitUntil:'domcontentloaded'})
 await section.getByRole('heading',{name:chosen,exact:true}).waitFor()
 assert.equal((await db.doc(`customerReviewsPublic/${slot.data().publicReviewId}`).get()).data().reviewerAlias,chosen)
 assert.equal(await customer.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)
 await admin.reload({waitUntil:'domcontentloaded'})
 await admin.getByRole('button',{name:'Open case',exact:true}).click()
 await admin.getByText('Public display name: Replacement public name',{exact:true}).waitFor()
 await admin.getByText(`Public display name: ${chosen}`,{exact:true}).waitFor()
 await admin.screenshot({path:resolve(evidence,'moderated-name-desktop.png'),fullPage:true})
 await admin.getByRole('button',{name:'Approve',exact:true}).click()
 await admin.getByRole('dialog').getByRole('button',{name:'Confirm',exact:true}).click()
 await customer.reload({waitUntil:'domcontentloaded'})
 await section.getByRole('heading',{name:'Replacement public name',exact:true}).waitFor()
 assert.equal((await slot.ref.collection('revisions').get()).size,2)
 // Rejected edits retain the approved review; private admin notes never reach the customer.
 await section.getByRole('button',{name:'Edit your review',exact:true}).click()
 await name.fill('Rejected proposed name')
 await section.getByRole('button',{name:'Submit edit',exact:true}).click()
 await section.getByText('Published; edit awaiting approval',{exact:true}).waitFor()
 await admin.setViewportSize({width:390,height:900})
 await admin.reload({waitUntil:'domcontentloaded'})
 await admin.getByRole('button',{name:'Open case',exact:true}).click()
 const reasonChoice=admin.locator('.admin-customer-reviews [role=combobox]')
 await reasonChoice.focus();await reasonChoice.press('Home');await reasonChoice.press('ArrowDown');await reasonChoice.press('Enter')
 await admin.locator('.admin-customer-reviews textarea').fill('PRIVATE SYNTHETIC MODERATION NOTE')
 await admin.getByRole('button',{name:'Reject',exact:true}).click()
 await admin.getByRole('dialog').getByRole('button',{name:'Confirm',exact:true}).click()
 await customer.reload({waitUntil:'domcontentloaded'})
 await section.getByRole('heading',{name:'Replacement public name',exact:true}).waitFor()
 await section.getByText('This submission was rejected for: Spam. Revise your review before submitting it again.',{exact:true}).waitFor()
 assert.ok(!(await section.innerText()).includes('PRIVATE SYNTHETIC MODERATION NOTE'))
 assert.equal(await admin.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)
 await admin.screenshot({path:resolve(evidence,'rejection-mobile.png'),fullPage:true})
 await admin.setViewportSize({width:1440,height:900})
 // Combined policy journey: seed only the boundary counter; all actions below use real UI/callables.
 const {customerReviewReportQuotaId}=await import(resolve(root,'functions/src/customerReviewReports.js'))
 const {customerReviewQuotaKey}=await import(resolve(root,'functions/src/customerReviewCommands.js'))
 const reporter=await pageFor('reporter')
 const reportQuota=db.doc(`customerReviewReportQuotas/${customerReviewReportQuotaId('review-demo-reporter-v1')}`)
 await reportQuota.set({schemaVersion:1,acceptedAt:Array(9).fill(Date.now())})
 await reporter.goto('http://127.0.0.1:4190/services/review-demo-business-v1',{waitUntil:'domcontentloaded'})
 const reportSent=[];let dropReport=true
 await reporter.route('**/submitCustomerReviewReport',async route=>{
  if(route.request().method()!=='POST')return route.continue()
  reportSent.push(route.request().postDataJSON().data)
  if(dropReport){dropReport=false;assert.equal((await route.fetch()).status(),200);await route.abort('failed')}else await route.continue()
 })
 const openReport=async()=>{
  await reporter.locator('section.customer-reviews').getByRole('button',{name:'Report review',exact:true}).click()
  const dialog=reporter.getByRole('dialog')
  await dialog.getByRole('radio',{name:'Spam',exact:true}).check()
  await dialog.locator('textarea').fill('Private synthetic details for retention verification.')
  await dialog.getByRole('button',{name:'Send report',exact:true}).click()
  return dialog
 }
 let dialog=await openReport()
 await dialog.getByRole('button',{name:'Retry',exact:true}).click()
 await dialog.getByText('Report sent to moderation. The review has not been removed.',{exact:true}).waitFor()
 assert.equal(reportSent.length,2);assert.deepEqual(reportSent[0],reportSent[1])
 assert.equal((await reportQuota.get()).data().acceptedAt.length,10)
 const reportRows=await db.collection('customerReviewReports').where('reporterUid','==','review-demo-reporter-v1').get()
 assert.equal(reportRows.size,1);const reportRef=reportRows.docs[0].ref
 await reportRef.update({createdAt:Timestamp.fromMillis(Date.now()-7*86400000)})
 await admin.goto('http://127.0.0.1:4190/admin/customer-review-reports',{waitUntil:'domcontentloaded'})
 await admin.getByText('Overdue — open for 7 days or more',{exact:true}).waitFor()
 await admin.getByRole('button',{name:'Open case',exact:true}).click()
 await admin.getByText('Private synthetic details for retention verification.',{exact:true}).waitFor()
 const businessLink=admin.locator('.admin-customer-reviews__identity a')
 assert.equal(await businessLink.getAttribute('href'),'/services/review-demo-business-v1')
 assert.equal(await businessLink.innerText(),(await db.doc('businesses/review-demo-business-v1').get()).data().name)
 await businessLink.focus()
 assert.equal(await businessLink.evaluate(n=>n===document.activeElement),true)
 await admin.locator('.admin-customer-reviews textarea').fill('Handled this synthetic report without removing the review.')
 await admin.getByRole('button',{name:'Resolve',exact:true}).click()
 await admin.getByRole('dialog').press('Escape')
 assert.equal((await reportRef.get()).data().status,'open')
 await admin.getByRole('button',{name:'Resolve',exact:true}).click()
 await admin.getByRole('dialog').getByRole('button',{name:'Confirm',exact:true}).click()
 await admin.getByText('Report resolved',{exact:true}).waitFor()
 assert.equal((await reportRef.get()).data().status,'resolved')
 for(const collection of ['customerReviewReportRequests','customerReviewReportAudits']){
  const rows=await db.collection(collection).where('reportId','==',reportRef.id).get();assert.equal(rows.size,2)
  for(const row of rows.docs)assert.ok(row.data().expiresAt instanceof Timestamp)
 }
 await reporter.reload({waitUntil:'domcontentloaded'})
 await reporter.getByRole('heading',{name:'Replacement public name',exact:true}).waitFor()
 dialog=await openReport()
 await dialog.getByRole('alert').waitFor()
 assert.equal((await reportRef.get()).data().status,'resolved','quota rejection cannot reopen a resolved report')
 assert.equal((await reportQuota.get()).data().acceptedAt.length,10)
 await reporter.screenshot({path:resolve(evidence,'report-quota-mobile.png')})
 await dialog.getByRole('button',{name:'Close',exact:true}).scrollIntoViewIfNeeded()
 await dialog.getByRole('button',{name:'Close',exact:true}).click()
 await dialog.waitFor({state:'hidden'})
 await reportQuota.set({schemaVersion:1,acceptedAt:Array(10).fill(Date.now()-86400000)})
 await reporter.reload({waitUntil:'domcontentloaded'})
 dialog=await openReport()
 await dialog.getByText('Report sent to moderation. The review has not been removed.',{exact:true}).waitFor()
 assert.equal((await reportRef.get()).data().status,'open')
 assert.equal((await reportQuota.get()).data().acceptedAt.length,1)
 // Editing at the review quota must leave the published review unchanged and withdrawal usable.
 await db.doc(`customerReviewQuotas/${customerReviewQuotaKey('review-demo-customer-v1')}`).set({schemaVersion:1,acceptedAt:Array(5).fill(Date.now())})
 await customer.reload({waitUntil:'domcontentloaded'})
 await section.getByRole('button',{name:'Edit your review',exact:true}).click()
 await name.fill('Must not be published')
 await section.getByRole('button',{name:'Submit edit',exact:true}).click()
 await section.getByRole('alert').waitFor()
 assert.equal((await db.doc(`customerReviewsPublic/${slot.data().publicReviewId}`).get()).data().reviewerAlias,'Replacement public name')
 const withdraw=section.getByRole('button',{name:'Withdraw review',exact:true})
 assert.equal(await withdraw.isEnabled(),true)
 await withdraw.click()
 await customer.getByRole('dialog').getByRole('button',{name:'Withdraw review',exact:true}).click()
 await section.getByText('Review withdrawn. Any pending submission has been cancelled.',{exact:true}).waitFor()
 await customer.reload({waitUntil:'domcontentloaded'})
 assert.equal((await db.doc(`customerReviewsPublic/${slot.data().publicReviewId}`).get()).exists,false)
 assert.equal((await slot.ref.collection('revisions').get()).size,3)
 assert.equal(await reporter.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)
 assert.deepEqual(errors,[])
 console.log('PASS: combined report lost-response retry, quota rejection/recovery, overdue admin resolution/cancel, retained linked expiry, published visibility, review quota and withdrawal/reload.')
 console.log('PASS: real customer submit/lost-response/retry, single revision, admin name approval, escaped display/reload, moderated name edit, private account isolation, mobile/desktop.')
} finally {await b.close()}
