// Run only against scripts/runCustomerReviewDemo.mjs. Synthetic data and loopback services only.
import assert from 'node:assert/strict'
import {chromium} from 'playwright'
import {createRequire} from 'node:module'
import {resolve} from 'node:path'
import {mkdir} from 'node:fs/promises'
const root=resolve(import.meta.dirname,'../../../..')
const require=createRequire(resolve(root,'functions/package.json'))
for(const key of ['GOOGLE_APPLICATION_CREDENTIALS','FIREBASE_TOKEN','GOOGLE_OAUTH_ACCESS_TOKEN'])assert.ok(!process.env[key])
const hub=await fetch('http://127.0.0.1:4400/emulators',{redirect:'error'}).then(r=>r.json())
for(const [name,port] of Object.entries({auth:9099,firestore:8080,functions:5001,storage:9199}))assert.deepEqual([hub[name]?.host,hub[name]?.port],['127.0.0.1',port])
process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080';process.env.FIREBASE_AUTH_EMULATOR_HOST='127.0.0.1:9099'
const {initializeApp}=require('firebase-admin/app'),{getFirestore}=require('firebase-admin/firestore')
const db=getFirestore(initializeApp({projectId:'demo-holalocal-functions'}))
for(const id of ['customer','admin'])await db.doc(`users/review-demo-${id}-v1`).update({firstName:'Private',lastName:'Account',displayName:'PRIVATE ACCOUNT NAME',displayNameNormalized:'private account name',city:'Málaga',country:'Spain',profileCompleted:true})
const evidence=resolve(root,'../review-evidence/display-browser');await mkdir(evidence,{recursive:true})
const b=await chromium.launch({headless:true,args:['--disable-dev-shm-usage']})
const errors=[]
async function pageFor(role,width=390){
 const context=await b.newContext({viewport:{width,height:900}})
 await context.route('**/*',route=>/^http:\/\/127\.0\.0\.1:/.test(route.request().url())?route.continue():route.abort())
 const p=await context.newPage();p.setDefaultTimeout(20000);p.on('pageerror',e=>errors.push(e.message))
 await p.goto('http://127.0.0.1:4190/login',{waitUntil:'domcontentloaded'})
 await p.locator('input[type=email]').fill(`${role}@reviews.example.invalid`)
 await p.locator('input[type=password]').fill('Fictional-review-demo-47!')
 await p.getByRole('button',{name:'Log in',exact:true}).click()
 await p.waitForURL(u=>!u.pathname.includes('/login'))
 return p
}
try{
 const customer=await pageFor('customer')
 await customer.goto('http://127.0.0.1:4190/services/review-demo-business-v1',{waitUntil:'domcontentloaded'})
 const section=customer.locator('section.customer-reviews').first()
 await section.getByRole('button',{name:'Write a review',exact:true}).click()
 const name=section.locator('input[name=displayName]')
 assert.equal(await name.inputValue(),'')
 assert.ok((await section.innerText()).includes('This name will be public'))
 assert.ok((await section.innerText()).includes('does not prove a purchase or service'))
 await section.getByRole('button',{name:'Submit review',exact:true}).click()
 assert.equal(await name.evaluate(n=>n===document.activeElement),true)
 const chosen='Éloise <script> & neighbours'
 await name.fill(chosen)
 await section.getByRole('radio',{name:'Rating: 4 / 5',exact:true}).check()
 await section.locator('textarea').fill('A carefully completed synthetic service for this isolated browser test.')
 await name.scrollIntoViewIfNeeded()
 await customer.screenshot({path:resolve(evidence,'public-name-mobile.png')})
 const sent=[];let drop=true
 await customer.route('**/submitCustomerReview',async route=>{
  if(route.request().method()!=='POST')return route.continue()
  sent.push(route.request().postDataJSON().data)
  if(drop){drop=false;const response=await route.fetch();assert.equal(response.status(),200);await route.abort('failed')}else await route.continue()
 })
 await section.getByRole('button',{name:'Submit review',exact:true}).click()
 await section.getByRole('button',{name:'Retry',exact:true}).click()
 await section.getByText('Awaiting approval',{exact:true}).waitFor()
 assert.equal(sent.length,2);assert.deepEqual(sent[0],sent[1]);assert.equal(sent[0].displayName,chosen)
 const slots=await db.collection('customerReviewSlots').where('authorUid','==','review-demo-customer-v1').get()
 assert.equal(slots.size,1)
 const slot=slots.docs[0];assert.equal(slot.data().revisionCount,1)
 assert.equal((await slot.ref.collection('revisions').get()).size,1)
 assert.equal((await db.collection('customerReviewsPublic').get()).size,0)
 const admin=await pageFor('admin',1440)
 await admin.goto('http://127.0.0.1:4190/admin/customer-reviews',{waitUntil:'domcontentloaded'})
 await admin.getByRole('button',{name:'Open case',exact:true}).click()
 await admin.getByText(`Public display name: ${chosen}`,{exact:true}).waitFor()
 await admin.getByRole('button',{name:'Approve',exact:true}).click()
 await admin.getByRole('dialog').press('Escape')
 await admin.getByRole('button',{name:'Approve',exact:true}).waitFor()
 await admin.getByRole('button',{name:'Approve',exact:true}).click()
 await admin.getByRole('dialog').getByRole('button',{name:'Confirm',exact:true}).click()
 await customer.reload({waitUntil:'domcontentloaded'})
 await section.getByRole('heading',{name:chosen,exact:true}).waitFor()
 assert.equal(await section.locator('script').count(),0)
 assert.ok(!(await section.innerText()).includes('PRIVATE ACCOUNT NAME'))
 await section.getByRole('button',{name:'Edit your review',exact:true}).click()
 assert.equal(await name.inputValue(),chosen)
 await name.fill('Replacement public name')
 await section.getByRole('button',{name:'Submit edit',exact:true}).click()
 await section.getByText('Published; edit awaiting approval',{exact:true}).waitFor()
 await customer.reload({waitUntil:'domcontentloaded'})
 await section.getByRole('heading',{name:chosen,exact:true}).waitFor()
 assert.equal((await db.doc(`customerReviewsPublic/${slot.data().publicReviewId}`).get()).data().reviewerAlias,chosen)
 assert.equal(await customer.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)
 await admin.reload({waitUntil:'domcontentloaded'})
 await admin.getByRole('button',{name:'Open case',exact:true}).click()
 await admin.getByText('Public display name: Replacement public name',{exact:true}).waitFor()
 await admin.getByText(`Public display name: ${chosen}`,{exact:true}).waitFor()
 await admin.screenshot({path:resolve(evidence,'moderated-name-desktop.png'),fullPage:true})
 await admin.getByRole('button',{name:'Approve',exact:true}).click()
 await admin.getByRole('dialog').getByRole('button',{name:'Confirm',exact:true}).click()
 await customer.reload({waitUntil:'domcontentloaded'})
 await section.getByRole('heading',{name:'Replacement public name',exact:true}).waitFor()
 assert.equal((await slot.ref.collection('revisions').get()).size,2)
 assert.deepEqual(errors,[])
 console.log('PASS: real customer submit/lost-response/retry, single revision, admin name approval, escaped display/reload, moderated name edit, private account isolation, mobile/desktop.')
} finally {await b.close()}
