const editor = (taxonomyEditor) => ({ business: { taxonomyEditor } })

export const businessTaxonomyEditorTranslations = Object.freeze({
  en: editor({ title: 'Services', description: 'Choose the services that best describe your work.', serviceGroup: 'Service group', chooseGroup: 'Choose a service group', mainService: 'What is your main service?', chooseMain: 'Choose your main service', additionalServices: 'What else do you offer?', additionalLimit: '{{selected}} selected · choose up to {{count}} additional services', customDescription: 'Describe your service', customDescriptionLimit: 'Maximum {{count}} characters', legacyTitle: 'Your current services use an older format', legacyDescription: 'You can keep them for now, or update your services. Unrelated profile changes will not alter them.', currentLegacyValues: 'Current unresolved services', updateServices: 'Update services' }),
  es: editor({ title: 'Servicios', description: 'Elige los servicios que mejor describen tu trabajo.', serviceGroup: 'Grupo de servicios', chooseGroup: 'Elige un grupo de servicios', mainService: '¿Cuál es tu servicio principal?', chooseMain: 'Elige tu servicio principal', additionalServices: '¿Qué más ofreces?', additionalLimit: '{{selected}} seleccionados · elige hasta {{count}} servicios adicionales', customDescription: 'Describe tu servicio', customDescriptionLimit: 'Máximo {{count}} caracteres', legacyTitle: 'Tus servicios actuales usan un formato anterior', legacyDescription: 'Puedes conservarlos por ahora o actualizarlos. Otros cambios del perfil no los modificarán.', currentLegacyValues: 'Servicios actuales sin resolver', updateServices: 'Actualizar servicios' }),
  fr: editor({ title: 'Services', description: 'Choisissez les services qui décrivent le mieux votre activité.', serviceGroup: 'Groupe de services', chooseGroup: 'Choisissez un groupe de services', mainService: 'Quel est votre service principal ?', chooseMain: 'Choisissez votre service principal', additionalServices: 'Que proposez-vous d’autre ?', additionalLimit: '{{selected}} sélectionnés · choisissez jusqu’à {{count}} services supplémentaires', customDescription: 'Décrivez votre service', customDescriptionLimit: '{{count}} caractères maximum', legacyTitle: 'Vos services actuels utilisent un ancien format', legacyDescription: 'Vous pouvez les conserver ou les mettre à jour. Les autres modifications du profil ne les changeront pas.', currentLegacyValues: 'Services actuels non résolus', updateServices: 'Mettre à jour les services' }),
  de: editor({ title: 'Dienstleistungen', description: 'Wählen Sie die Dienstleistungen, die Ihre Arbeit am besten beschreiben.', serviceGroup: 'Dienstleistungsgruppe', chooseGroup: 'Dienstleistungsgruppe auswählen', mainService: 'Was ist Ihre Hauptdienstleistung?', chooseMain: 'Hauptdienstleistung auswählen', additionalServices: 'Was bieten Sie außerdem an?', additionalLimit: '{{selected}} ausgewählt · bis zu {{count}} zusätzliche Dienstleistungen', customDescription: 'Dienstleistung beschreiben', customDescriptionLimit: 'Maximal {{count}} Zeichen', legacyTitle: 'Ihre aktuellen Dienstleistungen verwenden ein älteres Format', legacyDescription: 'Sie können sie vorerst behalten oder aktualisieren. Andere Profiländerungen ändern sie nicht.', currentLegacyValues: 'Aktuelle nicht zugeordnete Dienstleistungen', updateServices: 'Dienstleistungen aktualisieren' }),
  nl: editor({ title: 'Diensten', description: 'Kies de diensten die uw werk het beste beschrijven.', serviceGroup: 'Dienstengroep', chooseGroup: 'Kies een dienstengroep', mainService: 'Wat is uw belangrijkste dienst?', chooseMain: 'Kies uw belangrijkste dienst', additionalServices: 'Wat biedt u nog meer aan?', additionalLimit: '{{selected}} geselecteerd · kies maximaal {{count}} extra diensten', customDescription: 'Beschrijf uw dienst', customDescriptionLimit: 'Maximaal {{count}} tekens', legacyTitle: 'Uw huidige diensten gebruiken een ouder formaat', legacyDescription: 'U kunt ze voorlopig behouden of bijwerken. Andere profielwijzigingen veranderen ze niet.', currentLegacyValues: 'Huidige niet-herkende diensten', updateServices: 'Diensten bijwerken' }),
  pt: editor({ title: 'Serviços', description: 'Escolha os serviços que melhor descrevem o seu trabalho.', serviceGroup: 'Grupo de serviços', chooseGroup: 'Escolha um grupo de serviços', mainService: 'Qual é o seu serviço principal?', chooseMain: 'Escolha o seu serviço principal', additionalServices: 'Que outros serviços presta?', additionalLimit: '{{selected}} selecionados · escolha até {{count}} serviços adicionais', customDescription: 'Descreva o seu serviço', customDescriptionLimit: 'Máximo de {{count}} caracteres', legacyTitle: 'Os seus serviços atuais usam um formato antigo', legacyDescription: 'Pode mantê-los por agora ou atualizá-los. Outras alterações ao perfil não os modificarão.', currentLegacyValues: 'Serviços atuais não reconhecidos', updateServices: 'Atualizar serviços' }),
})
