const taxonomy = (groups, services) => ({ services: { taxonomy: { groups, services } } })

export const serviceTaxonomyTranslations = Object.freeze({
  en: taxonomy(
    { homeProperty: 'Home & Property', professionalServices: 'Professional Services', healthBeautyLifestyle: 'Health, Beauty & Lifestyle', learningFamily: 'Learning & Family', pets: 'Pets', otherLocalServices: 'Other Local Services' },
    { plumber: 'Plumber', electrician: 'Electrician', cleaner: 'Cleaner', gardener: 'Gardener', builderRenovation: 'Builder & Renovation', painterDecorator: 'Painter & Decorator', handyman: 'Handyman', airConditioning: 'Air Conditioning', poolServices: 'Pool Services', pestControl: 'Pest Control', locksmith: 'Locksmith', removals: 'Removals', lawyer: 'Lawyer', accountant: 'Accountant', translatorInterpreter: 'Translator & Interpreter', graphicDesigner: 'Graphic Designer', webDesignerDeveloper: 'Web Designer & Developer', photographer: 'Photographer', marketing: 'Marketing', businessConsultant: 'Business Consultant', personalTrainer: 'Personal Trainer', hairdresser: 'Hairdresser', beautyServices: 'Beauty Services', massageWellness: 'Massage & Wellness', nutrition: 'Nutrition', yogaFitness: 'Yoga & Fitness', tutor: 'Tutor', languageTeacher: 'Language Teacher', musicTeacher: 'Music Teacher', childcareBabysitting: 'Childcare & Babysitting', dogWalker: 'Dog Walker', petSitter: 'Pet Sitter', petGroomer: 'Pet Groomer', dogTrainer: 'Dog Trainer', otherLocalService: 'Other Local Service' },
  ),
  es: taxonomy(
    { homeProperty: 'Hogar y propiedad', professionalServices: 'Servicios profesionales', healthBeautyLifestyle: 'Salud, belleza y bienestar', learningFamily: 'Aprendizaje y familia', pets: 'Mascotas', otherLocalServices: 'Otros servicios locales' },
    { plumber: 'Fontanero', electrician: 'Electricista', cleaner: 'Profesional de limpieza', gardener: 'Jardinero', builderRenovation: 'Construcción y reformas', painterDecorator: 'Pintor y decorador', handyman: 'Manitas', airConditioning: 'Aire acondicionado', poolServices: 'Servicios de piscinas', pestControl: 'Control de plagas', locksmith: 'Cerrajero', removals: 'Mudanzas', lawyer: 'Abogado', accountant: 'Contable', translatorInterpreter: 'Traductor e intérprete', graphicDesigner: 'Diseñador gráfico', webDesignerDeveloper: 'Diseñador y desarrollador web', photographer: 'Fotógrafo', marketing: 'Marketing', businessConsultant: 'Consultor empresarial', personalTrainer: 'Entrenador personal', hairdresser: 'Peluquero', beautyServices: 'Servicios de belleza', massageWellness: 'Masajes y bienestar', nutrition: 'Nutrición', yogaFitness: 'Yoga y fitness', tutor: 'Profesor particular', languageTeacher: 'Profesor de idiomas', musicTeacher: 'Profesor de música', childcareBabysitting: 'Cuidado infantil y canguro', dogWalker: 'Paseador de perros', petSitter: 'Cuidador de mascotas', petGroomer: 'Peluquero de mascotas', dogTrainer: 'Adiestrador canino', otherLocalService: 'Otro servicio local' },
  ),
  fr: taxonomy(
    { homeProperty: 'Maison et propriété', professionalServices: 'Services professionnels', healthBeautyLifestyle: 'Santé, beauté et bien-être', learningFamily: 'Apprentissage et famille', pets: 'Animaux', otherLocalServices: 'Autres services locaux' },
    { plumber: 'Plombier', electrician: 'Électricien', cleaner: 'Professionnel du nettoyage', gardener: 'Jardinier', builderRenovation: 'Construction et rénovation', painterDecorator: 'Peintre et décorateur', handyman: 'Bricoleur', airConditioning: 'Climatisation', poolServices: 'Services de piscine', pestControl: 'Lutte antiparasitaire', locksmith: 'Serrurier', removals: 'Déménagement', lawyer: 'Avocat', accountant: 'Comptable', translatorInterpreter: 'Traducteur et interprète', graphicDesigner: 'Graphiste', webDesignerDeveloper: 'Concepteur et développeur web', photographer: 'Photographe', marketing: 'Marketing', businessConsultant: 'Conseiller d’entreprise', personalTrainer: 'Coach personnel', hairdresser: 'Coiffeur', beautyServices: 'Services de beauté', massageWellness: 'Massage et bien-être', nutrition: 'Nutrition', yogaFitness: 'Yoga et fitness', tutor: 'Professeur particulier', languageTeacher: 'Professeur de langues', musicTeacher: 'Professeur de musique', childcareBabysitting: 'Garde d’enfants et baby-sitting', dogWalker: 'Promeneur de chiens', petSitter: 'Garde d’animaux', petGroomer: 'Toiletteur pour animaux', dogTrainer: 'Éducateur canin', otherLocalService: 'Autre service local' },
  ),
  de: taxonomy(
    { homeProperty: 'Haus und Grundstück', professionalServices: 'Professionelle Dienstleistungen', healthBeautyLifestyle: 'Gesundheit, Schönheit und Lebensstil', learningFamily: 'Lernen und Familie', pets: 'Haustiere', otherLocalServices: 'Andere lokale Dienstleistungen' },
    { plumber: 'Installateur', electrician: 'Elektriker', cleaner: 'Reinigungskraft', gardener: 'Gärtner', builderRenovation: 'Bau und Renovierung', painterDecorator: 'Maler und Dekorateur', handyman: 'Handwerker', airConditioning: 'Klimaanlagen', poolServices: 'Poolservice', pestControl: 'Schädlingsbekämpfung', locksmith: 'Schlüsseldienst', removals: 'Umzüge', lawyer: 'Rechtsanwalt', accountant: 'Buchhalter', translatorInterpreter: 'Übersetzer und Dolmetscher', graphicDesigner: 'Grafikdesigner', webDesignerDeveloper: 'Webdesigner und -entwickler', photographer: 'Fotograf', marketing: 'Marketing', businessConsultant: 'Unternehmensberater', personalTrainer: 'Personal Trainer', hairdresser: 'Friseur', beautyServices: 'Kosmetikdienstleistungen', massageWellness: 'Massage und Wellness', nutrition: 'Ernährungsberatung', yogaFitness: 'Yoga und Fitness', tutor: 'Nachhilfelehrer', languageTeacher: 'Sprachlehrer', musicTeacher: 'Musiklehrer', childcareBabysitting: 'Kinderbetreuung und Babysitting', dogWalker: 'Hundeausführer', petSitter: 'Tiersitter', petGroomer: 'Tierfriseur', dogTrainer: 'Hundetrainer', otherLocalService: 'Andere lokale Dienstleistung' },
  ),
  nl: taxonomy(
    { homeProperty: 'Huis en woning', professionalServices: 'Professionele diensten', healthBeautyLifestyle: 'Gezondheid, schoonheid en lifestyle', learningFamily: 'Leren en gezin', pets: 'Huisdieren', otherLocalServices: 'Andere lokale diensten' },
    { plumber: 'Loodgieter', electrician: 'Elektricien', cleaner: 'Schoonmaker', gardener: 'Tuinman', builderRenovation: 'Bouw en renovatie', painterDecorator: 'Schilder en decorateur', handyman: 'Klusjesman', airConditioning: 'Airconditioning', poolServices: 'Zwembaddiensten', pestControl: 'Ongediertebestrijding', locksmith: 'Slotenmaker', removals: 'Verhuizingen', lawyer: 'Advocaat', accountant: 'Boekhouder', translatorInterpreter: 'Vertaler en tolk', graphicDesigner: 'Grafisch ontwerper', webDesignerDeveloper: 'Webdesigner en -ontwikkelaar', photographer: 'Fotograaf', marketing: 'Marketing', businessConsultant: 'Bedrijfsadviseur', personalTrainer: 'Personal trainer', hairdresser: 'Kapper', beautyServices: 'Schoonheidsdiensten', massageWellness: 'Massage en wellness', nutrition: 'Voedingsadvies', yogaFitness: 'Yoga en fitness', tutor: 'Bijlesdocent', languageTeacher: 'Taaldocent', musicTeacher: 'Muziekdocent', childcareBabysitting: 'Kinderopvang en oppas', dogWalker: 'Hondenuitlater', petSitter: 'Dierenoppas', petGroomer: 'Dierentrimmer', dogTrainer: 'Hondentrainer', otherLocalService: 'Andere lokale dienst' },
  ),
  pt: taxonomy(
    { homeProperty: 'Casa e propriedade', professionalServices: 'Serviços profissionais', healthBeautyLifestyle: 'Saúde, beleza e estilo de vida', learningFamily: 'Aprendizagem e família', pets: 'Animais de estimação', otherLocalServices: 'Outros serviços locais' },
    { plumber: 'Canalizador', electrician: 'Eletricista', cleaner: 'Profissional de limpeza', gardener: 'Jardineiro', builderRenovation: 'Construção e renovação', painterDecorator: 'Pintor e decorador', handyman: 'Faz-tudo', airConditioning: 'Ar condicionado', poolServices: 'Serviços de piscina', pestControl: 'Controlo de pragas', locksmith: 'Serralheiro', removals: 'Mudanças', lawyer: 'Advogado', accountant: 'Contabilista', translatorInterpreter: 'Tradutor e intérprete', graphicDesigner: 'Designer gráfico', webDesignerDeveloper: 'Designer e programador web', photographer: 'Fotógrafo', marketing: 'Marketing', businessConsultant: 'Consultor empresarial', personalTrainer: 'Treinador pessoal', hairdresser: 'Cabeleireiro', beautyServices: 'Serviços de beleza', massageWellness: 'Massagem e bem-estar', nutrition: 'Nutrição', yogaFitness: 'Yoga e fitness', tutor: 'Explicador', languageTeacher: 'Professor de línguas', musicTeacher: 'Professor de música', childcareBabysitting: 'Cuidados infantis e babysitting', dogWalker: 'Passeador de cães', petSitter: 'Cuidador de animais', petGroomer: 'Tosquiador de animais', dogTrainer: 'Treinador de cães', otherLocalService: 'Outro serviço local' },
  ),
})
