export const AUDIT_SCHEMA_VERSION = 'phase-1a-batch-3-read-only-v1'
export const AUDIT_TOOL_VERSION = '1.0.0'

export const AUDIT_ISSUE_CODES = Object.freeze({
  AUDIT_USER_UID_MISMATCH: 'AUDIT_USER_UID_MISMATCH',
  AUDIT_USER_REQUIRED_FIELD_MISSING: 'AUDIT_USER_REQUIRED_FIELD_MISSING',
  AUDIT_USER_INVALID_ROLES: 'AUDIT_USER_INVALID_ROLES',
  AUDIT_USER_DUPLICATE_ROLES: 'AUDIT_USER_DUPLICATE_ROLES',
  AUDIT_USER_PRIVILEGED_ROLE: 'AUDIT_USER_PRIVILEGED_ROLE',
  AUDIT_USER_ACCOUNT_TYPE_CONFLICT: 'AUDIT_USER_ACCOUNT_TYPE_CONFLICT',
  AUDIT_USER_ACCOUNT_STATUS_INVALID: 'AUDIT_USER_ACCOUNT_STATUS_INVALID',
  AUDIT_USER_COMPLETION_CONFLICT: 'AUDIT_USER_COMPLETION_CONFLICT',
  AUDIT_USER_LOCALE_INVALID: 'AUDIT_USER_LOCALE_INVALID',
  AUDIT_USER_LEGACY_LANGUAGE: 'AUDIT_USER_LEGACY_LANGUAGE',
  AUDIT_USER_BUSINESS_POINTER_MISSING: 'AUDIT_USER_BUSINESS_POINTER_MISSING',
  AUDIT_USER_BUSINESS_POINTER_INVALID: 'AUDIT_USER_BUSINESS_POINTER_INVALID',
  AUDIT_USER_BUSINESS_POINTER_OWNER_MISMATCH: 'AUDIT_USER_BUSINESS_POINTER_OWNER_MISMATCH',
  AUDIT_USER_BUSINESS_POINTER_UNEXPECTED: 'AUDIT_USER_BUSINESS_POINTER_UNEXPECTED',
  AUDIT_USER_LEGACY_TRUST_FIELD: 'AUDIT_USER_LEGACY_TRUST_FIELD',
  AUDIT_USER_CONSENT_INVALID: 'AUDIT_USER_CONSENT_INVALID',
  AUDIT_USER_DELETION_LIFECYCLE_INVALID: 'AUDIT_USER_DELETION_LIFECYCLE_INVALID',

  AUDIT_BUSINESS_LEGACY_UID_ID: 'AUDIT_BUSINESS_LEGACY_UID_ID',
  AUDIT_BUSINESS_OWNER_MISSING: 'AUDIT_BUSINESS_OWNER_MISSING',
  AUDIT_BUSINESS_OWNER_USER_MISSING: 'AUDIT_BUSINESS_OWNER_USER_MISSING',
  AUDIT_BUSINESS_MANAGER_IDS_INVALID: 'AUDIT_BUSINESS_MANAGER_IDS_INVALID',
  AUDIT_BUSINESS_MANAGER_IDS_DUPLICATE: 'AUDIT_BUSINESS_MANAGER_IDS_DUPLICATE',
  AUDIT_BUSINESS_OWNER_NOT_MANAGER: 'AUDIT_BUSINESS_OWNER_NOT_MANAGER',
  AUDIT_BUSINESS_REFERENCED_BY_MULTIPLE_USERS: 'AUDIT_BUSINESS_REFERENCED_BY_MULTIPLE_USERS',
  AUDIT_OWNER_BUSINESS_MISSING: 'AUDIT_OWNER_BUSINESS_MISSING',
  AUDIT_OWNER_SINGLE_BUSINESS: 'AUDIT_OWNER_SINGLE_BUSINESS',
  AUDIT_OWNER_MULTIPLE_BUSINESSES: 'AUDIT_OWNER_MULTIPLE_BUSINESSES',
  AUDIT_DUPLICATE_MANUAL_REVIEW_REQUIRED: 'AUDIT_DUPLICATE_MANUAL_REVIEW_REQUIRED',
  AUDIT_BUSINESS_CANONICAL_LEGACY_CONFLICT: 'AUDIT_BUSINESS_CANONICAL_LEGACY_CONFLICT',
  AUDIT_BUSINESS_LEGACY_TRUST_FIELD: 'AUDIT_BUSINESS_LEGACY_TRUST_FIELD',
  AUDIT_BUSINESS_STATUS_INVALID: 'AUDIT_BUSINESS_STATUS_INVALID',
  AUDIT_BUSINESS_VERIFICATION_STATUS_INVALID: 'AUDIT_BUSINESS_VERIFICATION_STATUS_INVALID',
  AUDIT_BUSINESS_SUBSCRIPTION_STATUS_INVALID: 'AUDIT_BUSINESS_SUBSCRIPTION_STATUS_INVALID',
  AUDIT_BUSINESS_PUBLICATION_TIMESTAMP_MISSING: 'AUDIT_BUSINESS_PUBLICATION_TIMESTAMP_MISSING',
  AUDIT_BUSINESS_VERIFICATION_TIMESTAMP_MISSING: 'AUDIT_BUSINESS_VERIFICATION_TIMESTAMP_MISSING',
  AUDIT_BUSINESS_DERIVED_FIELD_PRESENT: 'AUDIT_BUSINESS_DERIVED_FIELD_PRESENT',
  AUDIT_BUSINESS_DERIVED_FIELD_STALE: 'AUDIT_BUSINESS_DERIVED_FIELD_STALE',
  AUDIT_BUSINESS_TIMESTAMP_MISSING: 'AUDIT_BUSINESS_TIMESTAMP_MISSING',

  AUDIT_BUSINESS_PRIVATE_MISSING: 'AUDIT_BUSINESS_PRIVATE_MISSING',
  AUDIT_BUSINESS_PRIVATE_ORPHAN: 'AUDIT_BUSINESS_PRIVATE_ORPHAN',
  AUDIT_BUSINESS_PRIVATE_OWNER_MISMATCH: 'AUDIT_BUSINESS_PRIVATE_OWNER_MISMATCH',
  AUDIT_BUSINESS_PRIVATE_MANAGERS_MISMATCH: 'AUDIT_BUSINESS_PRIVATE_MANAGERS_MISMATCH',
  AUDIT_BUSINESS_PRIVATE_CONTACT_INVALID: 'AUDIT_BUSINESS_PRIVATE_CONTACT_INVALID',
  AUDIT_PUBLIC_CONTACT_VALUE_HIDDEN: 'AUDIT_PUBLIC_CONTACT_VALUE_HIDDEN',
  AUDIT_PUBLIC_CONTACT_VISIBILITY_MISSING: 'AUDIT_PUBLIC_CONTACT_VISIBILITY_MISSING',
  AUDIT_PUBLIC_CONTACT_VALUE_WITHOUT_PRIVATE: 'AUDIT_PUBLIC_CONTACT_VALUE_WITHOUT_PRIVATE',
  AUDIT_LEGACY_PUBLIC_CONTACT: 'AUDIT_LEGACY_PUBLIC_CONTACT',
  AUDIT_CONTACT_UNKNOWN_STRUCTURE: 'AUDIT_CONTACT_UNKNOWN_STRUCTURE',
  AUDIT_CONTACT_PREFERRED_METHOD_INVALID: 'AUDIT_CONTACT_PREFERRED_METHOD_INVALID',
  AUDIT_CONTACT_WEBSITE_VISIBILITY_UNSUPPORTED_BY_RULES: 'AUDIT_CONTACT_WEBSITE_VISIBILITY_UNSUPPORTED_BY_RULES',

  AUDIT_LANGUAGE_UNKNOWN: 'AUDIT_LANGUAGE_UNKNOWN',
  AUDIT_LANGUAGE_CUSTOM_LABEL_MISSING: 'AUDIT_LANGUAGE_CUSTOM_LABEL_MISSING',
  AUDIT_PRIMARY_LANGUAGE_INVALID: 'AUDIT_PRIMARY_LANGUAGE_INVALID',
  AUDIT_SERVICE_AREA_UNKNOWN: 'AUDIT_SERVICE_AREA_UNKNOWN',
  AUDIT_SERVICE_AREA_CUSTOM_LABEL_MISSING: 'AUDIT_SERVICE_AREA_CUSTOM_LABEL_MISSING',
  AUDIT_CATEGORY_UNKNOWN: 'AUDIT_CATEGORY_UNKNOWN',
  AUDIT_LOCATION_SERVICE_AREA_REVIEW: 'AUDIT_LOCATION_SERVICE_AREA_REVIEW',

  AUDIT_MEDIA_LEGACY_URL_PRESENT: 'AUDIT_MEDIA_LEGACY_URL_PRESENT',
  AUDIT_MEDIA_METADATA_INVALID: 'AUDIT_MEDIA_METADATA_INVALID',
  AUDIT_MEDIA_OWNER_PATH_MISMATCH: 'AUDIT_MEDIA_OWNER_PATH_MISMATCH',
  AUDIT_MEDIA_DUPLICATE_REFERENCE: 'AUDIT_MEDIA_DUPLICATE_REFERENCE',
  AUDIT_GALLERY_COUNT_INCONSISTENT: 'AUDIT_GALLERY_COUNT_INCONSISTENT',
  AUDIT_STORAGE_REFERENCE_MISSING: 'AUDIT_STORAGE_REFERENCE_MISSING',
  AUDIT_STORAGE_REFERENCE_UNREADABLE: 'AUDIT_STORAGE_REFERENCE_UNREADABLE',

  AUDIT_CONVERSATION_BUSINESS_MISSING: 'AUDIT_CONVERSATION_BUSINESS_MISSING',
  AUDIT_CONVERSATION_DUPLICATE_BUSINESS_REFERENCE: 'AUDIT_CONVERSATION_DUPLICATE_BUSINESS_REFERENCE',
  AUDIT_CONVERSATION_CUSTOMER_MISSING: 'AUDIT_CONVERSATION_CUSTOMER_MISSING',
  AUDIT_CONVERSATION_PARTICIPANT_MISSING: 'AUDIT_CONVERSATION_PARTICIPANT_MISSING',
  AUDIT_CONVERSATION_PARTICIPANTS_INVALID: 'AUDIT_CONVERSATION_PARTICIPANTS_INVALID',
  AUDIT_CONVERSATION_BUSINESS_PARTICIPANT_INVALID: 'AUDIT_CONVERSATION_BUSINESS_PARTICIPANT_INVALID',
  AUDIT_CONVERSATION_STATUS_INVALID: 'AUDIT_CONVERSATION_STATUS_INVALID',
  AUDIT_REPORT_TARGET_MISSING: 'AUDIT_REPORT_TARGET_MISSING',
  AUDIT_REPORT_REPORTER_MISSING: 'AUDIT_REPORT_REPORTER_MISSING',
  AUDIT_REPORT_TARGET_TYPE_INVALID: 'AUDIT_REPORT_TARGET_TYPE_INVALID',
  AUDIT_REPORT_STATUS_INVALID: 'AUDIT_REPORT_STATUS_INVALID',
  AUDIT_REPORT_PRIORITY_INVALID: 'AUDIT_REPORT_PRIORITY_INVALID',
  AUDIT_COLLECTION_READ_FAILED: 'AUDIT_COLLECTION_READ_FAILED',
  AUDIT_MANUAL_REVIEW_REQUIRED: 'AUDIT_MANUAL_REVIEW_REQUIRED',
})

const metadata = {
  identity: ['AUDIT_USER_UID_MISMATCH', 'AUDIT_USER_REQUIRED_FIELD_MISSING', 'AUDIT_BUSINESS_LEGACY_UID_ID', 'AUDIT_BUSINESS_OWNER_MISSING', 'AUDIT_BUSINESS_OWNER_USER_MISSING'],
  access: ['AUDIT_USER_INVALID_ROLES', 'AUDIT_USER_DUPLICATE_ROLES', 'AUDIT_USER_PRIVILEGED_ROLE', 'AUDIT_USER_ACCOUNT_TYPE_CONFLICT', 'AUDIT_USER_ACCOUNT_STATUS_INVALID'],
  language: ['AUDIT_USER_LOCALE_INVALID', 'AUDIT_USER_LEGACY_LANGUAGE', 'AUDIT_LANGUAGE_UNKNOWN', 'AUDIT_LANGUAGE_CUSTOM_LABEL_MISSING', 'AUDIT_PRIMARY_LANGUAGE_INVALID'],
  ownership: ['AUDIT_USER_BUSINESS_POINTER_MISSING', 'AUDIT_USER_BUSINESS_POINTER_INVALID', 'AUDIT_USER_BUSINESS_POINTER_OWNER_MISMATCH', 'AUDIT_USER_BUSINESS_POINTER_UNEXPECTED', 'AUDIT_OWNER_BUSINESS_MISSING', 'AUDIT_OWNER_SINGLE_BUSINESS', 'AUDIT_OWNER_MULTIPLE_BUSINESSES', 'AUDIT_DUPLICATE_MANUAL_REVIEW_REQUIRED', 'AUDIT_BUSINESS_REFERENCED_BY_MULTIPLE_USERS'],
  trust: ['AUDIT_USER_LEGACY_TRUST_FIELD', 'AUDIT_BUSINESS_LEGACY_TRUST_FIELD', 'AUDIT_BUSINESS_STATUS_INVALID', 'AUDIT_BUSINESS_VERIFICATION_STATUS_INVALID', 'AUDIT_BUSINESS_SUBSCRIPTION_STATUS_INVALID', 'AUDIT_BUSINESS_DERIVED_FIELD_PRESENT', 'AUDIT_BUSINESS_DERIVED_FIELD_STALE'],
  privacy: ['AUDIT_BUSINESS_PRIVATE_MISSING', 'AUDIT_BUSINESS_PRIVATE_ORPHAN', 'AUDIT_BUSINESS_PRIVATE_OWNER_MISMATCH', 'AUDIT_BUSINESS_PRIVATE_MANAGERS_MISMATCH', 'AUDIT_BUSINESS_PRIVATE_CONTACT_INVALID', 'AUDIT_PUBLIC_CONTACT_VALUE_HIDDEN', 'AUDIT_PUBLIC_CONTACT_VISIBILITY_MISSING', 'AUDIT_PUBLIC_CONTACT_VALUE_WITHOUT_PRIVATE', 'AUDIT_LEGACY_PUBLIC_CONTACT', 'AUDIT_CONTACT_UNKNOWN_STRUCTURE', 'AUDIT_CONTACT_PREFERRED_METHOD_INVALID', 'AUDIT_CONTACT_WEBSITE_VISIBILITY_UNSUPPORTED_BY_RULES'],
  taxonomy: ['AUDIT_SERVICE_AREA_UNKNOWN', 'AUDIT_SERVICE_AREA_CUSTOM_LABEL_MISSING', 'AUDIT_CATEGORY_UNKNOWN', 'AUDIT_LOCATION_SERVICE_AREA_REVIEW'],
  media: ['AUDIT_MEDIA_LEGACY_URL_PRESENT', 'AUDIT_MEDIA_METADATA_INVALID', 'AUDIT_MEDIA_OWNER_PATH_MISMATCH', 'AUDIT_MEDIA_DUPLICATE_REFERENCE', 'AUDIT_GALLERY_COUNT_INCONSISTENT', 'AUDIT_STORAGE_REFERENCE_MISSING', 'AUDIT_STORAGE_REFERENCE_UNREADABLE'],
  references: ['AUDIT_CONVERSATION_BUSINESS_MISSING', 'AUDIT_CONVERSATION_DUPLICATE_BUSINESS_REFERENCE', 'AUDIT_CONVERSATION_CUSTOMER_MISSING', 'AUDIT_CONVERSATION_PARTICIPANT_MISSING', 'AUDIT_CONVERSATION_PARTICIPANTS_INVALID', 'AUDIT_CONVERSATION_BUSINESS_PARTICIPANT_INVALID', 'AUDIT_CONVERSATION_STATUS_INVALID', 'AUDIT_REPORT_TARGET_MISSING', 'AUDIT_REPORT_REPORTER_MISSING', 'AUDIT_REPORT_TARGET_TYPE_INVALID', 'AUDIT_REPORT_STATUS_INVALID', 'AUDIT_REPORT_PRIORITY_INVALID'],
  execution: ['AUDIT_COLLECTION_READ_FAILED', 'AUDIT_MANUAL_REVIEW_REQUIRED', 'AUDIT_USER_COMPLETION_CONFLICT', 'AUDIT_USER_CONSENT_INVALID', 'AUDIT_USER_DELETION_LIFECYCLE_INVALID', 'AUDIT_BUSINESS_CANONICAL_LEGACY_CONFLICT', 'AUDIT_BUSINESS_MANAGER_IDS_INVALID', 'AUDIT_BUSINESS_MANAGER_IDS_DUPLICATE', 'AUDIT_BUSINESS_OWNER_NOT_MANAGER', 'AUDIT_BUSINESS_SUBSCRIPTION_STATUS_INVALID', 'AUDIT_BUSINESS_PUBLICATION_TIMESTAMP_MISSING', 'AUDIT_BUSINESS_VERIFICATION_TIMESTAMP_MISSING', 'AUDIT_BUSINESS_TIMESTAMP_MISSING'],
}

const errorCodes = new Set([
  'AUDIT_USER_REQUIRED_FIELD_MISSING', 'AUDIT_USER_INVALID_ROLES', 'AUDIT_USER_PRIVILEGED_ROLE',
  'AUDIT_USER_ACCOUNT_STATUS_INVALID', 'AUDIT_USER_BUSINESS_POINTER_INVALID',
  'AUDIT_USER_BUSINESS_POINTER_OWNER_MISMATCH', 'AUDIT_BUSINESS_OWNER_MISSING',
  'AUDIT_BUSINESS_OWNER_USER_MISSING', 'AUDIT_BUSINESS_MANAGER_IDS_INVALID',
  'AUDIT_BUSINESS_STATUS_INVALID', 'AUDIT_BUSINESS_VERIFICATION_STATUS_INVALID',
  'AUDIT_BUSINESS_PRIVATE_ORPHAN', 'AUDIT_PUBLIC_CONTACT_VALUE_HIDDEN',
  'AUDIT_LEGACY_PUBLIC_CONTACT', 'AUDIT_CONTACT_UNKNOWN_STRUCTURE',
  'AUDIT_CONVERSATION_BUSINESS_MISSING', 'AUDIT_REPORT_TARGET_MISSING',
  'AUDIT_COLLECTION_READ_FAILED',
])

export const AUDIT_ISSUE_METADATA = Object.freeze(Object.fromEntries(
  Object.values(AUDIT_ISSUE_CODES).map((code) => {
    const category = Object.entries(metadata).find(([, codes]) => codes.includes(code))?.[0] ?? 'general'
    const severity = errorCodes.has(code) ? 'error'
      : code.includes('MANUAL_REVIEW') || code.includes('MULTIPLE') || code.includes('CONFLICT')
        ? 'warning' : 'info'
    return [code, Object.freeze({ category, severity })]
  }),
))

export function assertKnownAuditCode(code) {
  if (!AUDIT_ISSUE_METADATA[code]) throw new Error(`Unknown audit issue code: ${code}`)
}
